/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import React from 'react';

import styles from '@/components/AgentTerminal/StatusConnecting/index.module.css';

const StatusConnecting: React.FC = () => (
  <div className={styles.statusMessage}>Connecting to agent...</div>
);

export default StatusConnecting;
