/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { api } from '@eclipse-che/common';
import { fireEvent, render, screen } from '@testing-library/react';
import React from 'react';

import { AiProviderKeysList, Props } from '@/pages/UserPreferences/AiProviderKeys/List';

jest.mock('@/pages/UserPreferences/AiProviderKeys/List/index.module.css', () => ({
  providerIcon: 'providerIcon',
  envVarColumn: 'envVarColumn',
  envVarCell: 'envVarCell',
  noKeyLabel: 'noKeyLabel',
  actionsCell: 'actionsCell',
}));

const mockTool1: api.AiToolDefinition = {
  providerId: 'anthropic/claude',
  tag: 'latest',
  name: 'Claude Code',
  url: 'https://example.com/claude',
  binary: 'claude',
  pattern: 'init',
  injectorImage: 'quay.io/example/claude:latest',
  envVarName: 'ANTHROPIC_API_KEY',
};

const mockTool2: api.AiToolDefinition = {
  providerId: 'openai/gpt',
  tag: 'latest',
  name: 'GPT',
  url: 'https://example.com/gpt',
  binary: 'gpt',
  pattern: 'init',
  injectorImage: 'quay.io/example/gpt:latest',
  envVarName: 'OPENAI_API_KEY',
};

const mockAiProviders: api.AiProviderDefinition[] = [
  {
    id: 'anthropic/claude',
    name: 'Anthropic',
    publisher: 'Anthropic',
    icon: 'https://example.com/anthropic.svg',
  },
  {
    id: 'openai/gpt',
    name: 'OpenAI',
    publisher: 'OpenAI',
  },
];

describe('AiProviderKeysList', () => {
  const mockOnAddKey = jest.fn();
  const mockOnUpdateKey = jest.fn();
  const mockOnDeleteKey = jest.fn();

  function getDefaultProps(overrides: Partial<Props> = {}): Props {
    return {
      isDisabled: false,
      providers: [mockTool1, mockTool2],
      aiProviders: mockAiProviders,
      providerKeyExists: {
        'anthropic/claude': true,
        'openai/gpt': true,
      },
      canAddMore: true,
      onAddKey: mockOnAddKey,
      onUpdateKey: mockOnUpdateKey,
      onDeleteKey: mockOnDeleteKey,
      ...overrides,
    };
  }

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should render the table with provider rows', () => {
    render(<AiProviderKeysList {...getDefaultProps()} />);

    expect(screen.getByText('Claude Code')).toBeTruthy();
    expect(screen.getByText('GPT')).toBeTruthy();
  });

  it('should show "Add AI Provider Key" button', () => {
    render(<AiProviderKeysList {...getDefaultProps()} />);

    const addButton = screen.getByTestId('add-ai-provider-key-button');
    expect(addButton).toBeTruthy();
    expect(addButton).not.toBeDisabled();
  });

  it('should disable "Add AI Provider Key" when canAddMore is false', () => {
    render(<AiProviderKeysList {...getDefaultProps({ canAddMore: false })} />);

    const addButton = screen.getByTestId('add-ai-provider-key-button');
    expect(addButton).toBeDisabled();
  });

  it('should show environment variable name in code tag', () => {
    render(<AiProviderKeysList {...getDefaultProps()} />);

    const codeElements = screen.getAllByText(/API_KEY/);
    expect(codeElements.length).toBeGreaterThanOrEqual(2);

    const anthropicCode = screen.getByText('ANTHROPIC_API_KEY');
    expect(anthropicCode.tagName).toBe('CODE');

    const openaiCode = screen.getByText('OPENAI_API_KEY');
    expect(openaiCode.tagName).toBe('CODE');
  });

  it('should call onAddKey when add button is clicked', () => {
    render(<AiProviderKeysList {...getDefaultProps()} />);

    const addButton = screen.getByTestId('add-ai-provider-key-button');
    fireEvent.click(addButton);

    expect(mockOnAddKey).toHaveBeenCalledTimes(1);
  });

  it('should have Delete button disabled when nothing is selected', () => {
    render(<AiProviderKeysList {...getDefaultProps()} />);

    const deleteButton = screen.getByTestId('bulk-delete-ai-key-button');
    expect(deleteButton).toBeDisabled();
  });
});
