/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupItem, BackupStatus, DEVWORKSPACE_BACKUP_ANNOTATIONS } from '@eclipse-che/common';
import {
  Button,
  Dropdown,
  DropdownItem,
  DropdownList,
  Label,
  MenuToggle,
  MenuToggleElement,
} from '@patternfly/react-core';
import { EllipsisVIcon } from '@patternfly/react-icons';
import React from 'react';
import { Link } from 'react-router-dom';

import { BackupStatusBadge } from '@/components/BackupStatusBadge';
import { CheTooltip } from '@/components/CheTooltip';
import { formatDate, formatRelativeDate } from '@/services/helpers/dates';
import { buildDetailsLocation } from '@/services/helpers/location';
import { WorkspaceDetailsTab } from '@/services/helpers/types';

export type RowData = {
  cells: { title: React.ReactNode; key: string }[];
};

export function deriveBackupStatus(backup: BackupItem): BackupStatus {
  const successLabel = backup.labels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
  if (successLabel === undefined) {
    return BackupStatus.NEVER;
  }
  if (successLabel === BackupStatus.UNAVAILABLE) {
    return BackupStatus.UNAVAILABLE;
  }
  if (successLabel === 'false') {
    return BackupStatus.FAILED;
  }
  return BackupStatus.SUCCESS;
}

export function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  const index = Math.min(i, units.length - 1);
  const value = bytes / Math.pow(1024, index);
  return `${value.toFixed(index === 0 ? 0 : 1)} ${units[index]}`;
}

export function buildBackupRows(
  backups: BackupItem[],
  namespace: string,
  expandedDropdowns: Record<string, boolean>,
  onDropdownToggle: (imageUrl: string, isOpen: boolean) => void,
  onCreateFromBackup: (backup: BackupItem) => void,
): RowData[] {
  return backups.map(backup => ({
    cells: [
      { title: renderWorkspaceName(backup, namespace), key: 'workspace-name' },
      { title: renderBackupTime(backup), key: 'backup-time' },
      { title: renderSize(backup), key: 'size' },
      { title: renderStatus(backup), key: 'status' },
      {
        title: renderActions(
          backup,
          expandedDropdowns[backup.imageUrl] || false,
          onDropdownToggle,
          onCreateFromBackup,
        ),
        key: 'actions',
      },
    ],
  }));
}

function renderWorkspaceName(backup: BackupItem, namespace: string): React.ReactElement {
  const detailsLocation = buildDetailsLocation(
    namespace,
    backup.workspaceName,
    WorkspaceDetailsTab.BACKUP,
  );

  return (
    <span data-testid="backup-workspace-name">
      {backup.workspaceExists ? (
        <Button variant="link" component={props => <Link {...props} to={detailsLocation} />}>
          {backup.workspaceName}
        </Button>
      ) : (
        <Button variant="link" isDisabled>
          {backup.workspaceName}
        </Button>
      )}{' '}
      {backup.workspaceExists ? (
        <CheTooltip content="This workspace currently exists and can be started">
          <Label color="green" isCompact data-testid="backup-workspace-active">
            Active
          </Label>
        </CheTooltip>
      ) : (
        <CheTooltip content="This workspace has been deleted, but its backup is still available">
          <Label color="grey" isCompact data-testid="backup-workspace-deleted">
            Deleted
          </Label>
        </CheTooltip>
      )}
    </span>
  );
}

function renderBackupTime(backup: BackupItem): React.ReactElement {
  return (
    <span
      data-testid="backup-time"
      title={backup.timestamp ? formatDate(new Date(backup.timestamp)) : ''}
    >
      {backup.timestamp ? formatRelativeDate(new Date(backup.timestamp)) : '-'}
    </span>
  );
}

function renderSize(backup: BackupItem): React.ReactElement {
  return (
    <span data-testid="backup-size">
      {backup.sizeBytes === 0 ? '-' : formatBytes(backup.sizeBytes)}
    </span>
  );
}

function renderStatus(backup: BackupItem): React.ReactElement {
  return (
    <span data-testid="backup-status">
      <BackupStatusBadge
        status={deriveBackupStatus(backup)}
        lastBackupTime={backup.timestamp}
        backupImageUrl={backup.imageUrl || undefined}
      />
    </span>
  );
}

function renderActions(
  backup: BackupItem,
  isExpanded: boolean,
  onDropdownToggle: (imageUrl: string, isOpen: boolean) => void,
  onCreateFromBackup: (backup: BackupItem) => void,
): React.ReactElement {
  const hasImage = backup.imageUrl !== '';

  const dropdown = (
    <Dropdown
      isOpen={isExpanded}
      onOpenChange={isOpen => onDropdownToggle(backup.imageUrl, isOpen)}
      onSelect={() => {
        onDropdownToggle(backup.imageUrl, false);
        onCreateFromBackup(backup);
      }}
      toggle={(toggleRef: React.Ref<MenuToggleElement>) => (
        <MenuToggle
          ref={toggleRef}
          variant="plain"
          isDisabled={!hasImage}
          isExpanded={isExpanded}
          onClick={() => onDropdownToggle(backup.imageUrl, !isExpanded)}
          aria-label={`Actions for ${backup.workspaceName}`}
          data-testid={`actions-dropdown-toggle-${backup.workspaceName}`}
        >
          <EllipsisVIcon />
        </MenuToggle>
      )}
      popperProps={{ position: 'right' }}
    >
      <DropdownList>
        <DropdownItem
          key="create-from-backup"
          data-testid={`create-from-backup-${backup.workspaceName}`}
        >
          Create from Backup
        </DropdownItem>
      </DropdownList>
    </Dropdown>
  );

  if (hasImage) {
    return dropdown;
  }

  return <CheTooltip content="No backup image available yet">{dropdown}</CheTooltip>;
}
