/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupItem, BackupStatus, DEVWORKSPACE_BACKUP_ANNOTATIONS } from '@eclipse-che/common';
import {
  Dropdown,
  DropdownItem,
  KebabToggle,
  Label,
  PageSection,
  PageSectionVariants,
} from '@patternfly/react-core';
import { ICell, sortable, SortByDirection } from '@patternfly/react-table';
import React from 'react';

import { BackupStatusBadge } from '@/components/BackupStatusBadge';
import { BackupsTable } from '@/pages/WorkspacesList/BackupsView/BackupsTable';
import BackupsListToolbar from '@/pages/WorkspacesList/BackupsView/Toolbar';
import { formatDate, formatRelativeDate } from '@/services/helpers/dates';
import { buildRestoreFromBackupLocation } from '@/services/helpers/location';

const COLUMNS: (ICell | string)[] = [
  {
    title: 'Workspace Name',
    dataLabel: 'Workspace Name',
    transforms: [sortable],
  },
  {
    title: 'Backup Time',
    dataLabel: 'Backup Time',
    transforms: [sortable],
  },
  {
    title: 'Size',
    dataLabel: 'Size',
    transforms: [sortable],
  },
  {
    title: 'Status',
    dataLabel: 'Status',
  },
  {
    title: '',
    dataLabel: 'Actions',
  },
];

type RowData = {
  cells: { title: React.ReactNode; key: string }[];
};

type Props = {
  backups: BackupItem[];
  navigate: (location: ReturnType<typeof buildRestoreFromBackupLocation>) => void;
  nextScheduledBackup: string | undefined;
};

type State = {
  filterValue: string;
  sortBy: {
    index: number;
    direction: SortByDirection;
  };
  expandedDropdowns: Record<string, boolean>;
};

// Generated by Claude Sonnet 4.5
function deriveBackupStatus(backup: BackupItem): BackupStatus {
  const successLabel = backup.labels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
  if (successLabel === undefined) {
    return BackupStatus.NEVER;
  }
  if (successLabel === BackupStatus.UNAVAILABLE) {
    return BackupStatus.UNAVAILABLE;
  }
  if (successLabel === 'false') {
    return BackupStatus.FAILED;
  }
  return BackupStatus.SUCCESS;
}

// Generated by Claude Sonnet 4.5
function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  const index = Math.min(i, units.length - 1);
  const value = bytes / Math.pow(1024, index);
  return `${value.toFixed(index === 0 ? 0 : 1)} ${units[index]}`;
}

export class BackupsTableView extends React.PureComponent<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      filterValue: '',
      sortBy: {
        index: 1,
        direction: SortByDirection.desc,
      },
      expandedDropdowns: {},
    };
  }

  private handleFilterChange(value: string): void {
    this.setState({ filterValue: value });
  }

  private handleSort(_event: React.MouseEvent, index: number, direction: SortByDirection): void {
    this.setState({
      sortBy: { index, direction },
    });
  }

  private handleDropdownToggle(imageUrl: string, isOpen: boolean): void {
    this.setState(prevState => ({
      expandedDropdowns: {
        ...prevState.expandedDropdowns,
        [imageUrl]: isOpen,
      },
    }));
  }

  private handleCreateFromBackup(backup: BackupItem): void {
    const location = buildRestoreFromBackupLocation(backup.imageUrl);
    this.props.navigate(location);
  }

  private handleRestoreFromBackup(): void {
    const location = buildRestoreFromBackupLocation();
    this.props.navigate(location);
  }

  private getFilteredBackups(): BackupItem[] {
    const { backups } = this.props;
    const { filterValue } = this.state;

    if (!filterValue) {
      return backups;
    }

    const lowerFilter = filterValue.toLowerCase();
    return backups.filter(backup => backup.workspaceName.toLowerCase().includes(lowerFilter));
  }

  private getSortedBackups(backups: BackupItem[]): BackupItem[] {
    const { sortBy } = this.state;
    const sorted = [...backups];

    sorted.sort((a, b) => {
      let comparison = 0;
      switch (sortBy.index) {
        case 0: // Workspace Name
          comparison = a.workspaceName.localeCompare(b.workspaceName);
          break;
        case 1: // Backup Time
          comparison = new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime();
          break;
        case 2: // Size
          comparison = a.sizeBytes - b.sizeBytes;
          break;
        default:
          comparison = 0;
      }
      return sortBy.direction === SortByDirection.asc ? comparison : -comparison;
    });

    return sorted;
  }

  private buildRows(backups: BackupItem[]): RowData[] {
    return backups.map(backup => ({
      cells: [
        {
          title: (
            <span data-testid="backup-workspace-name">
              {backup.workspaceName}{' '}
              {backup.workspaceExists ? (
                <Label color="green" isCompact data-testid="backup-workspace-active">
                  Active
                </Label>
              ) : (
                <Label color="grey" isCompact data-testid="backup-workspace-deleted">
                  Deleted
                </Label>
              )}
            </span>
          ),
          key: 'workspace-name',
        },
        {
          title: (
            <span
              data-testid="backup-time"
              title={backup.timestamp ? formatDate(new Date(backup.timestamp)) : ''}
            >
              {backup.timestamp ? formatRelativeDate(new Date(backup.timestamp)) : '-'}
            </span>
          ),
          key: 'backup-time',
        },
        {
          title: (
            <span data-testid="backup-size">
              {backup.sizeBytes === 0 ? '-' : formatBytes(backup.sizeBytes)}
            </span>
          ),
          key: 'size',
        },
        {
          title: (
            <span data-testid="backup-status">
              <BackupStatusBadge
                status={deriveBackupStatus(backup)}
                lastBackupTime={backup.timestamp || undefined}
                backupImageUrl={backup.imageUrl || undefined}
              />
            </span>
          ),
          key: 'status',
        },
        {
          title: this.buildActionsDropdown(backup),
          key: 'actions',
        },
      ],
    }));
  }

  private buildActionsDropdown(backup: BackupItem): React.ReactElement {
    const isExpanded = this.state.expandedDropdowns[backup.imageUrl] || false;

    return (
      <Dropdown
        isPlain
        position="right"
        isOpen={isExpanded}
        toggle={
          <KebabToggle
            aria-label={`Actions for ${backup.workspaceName}`}
            data-testid={`actions-dropdown-toggle-${backup.workspaceName}`}
            onToggle={isOpen => this.handleDropdownToggle(backup.imageUrl, isOpen)}
          />
        }
        dropdownItems={[
          <DropdownItem
            key="create-from-backup"
            component="button"
            data-testid={`create-from-backup-${backup.workspaceName}`}
            isDisabled={backup.imageUrl === ''}
            tooltip={backup.imageUrl === '' ? 'No backup image available' : undefined}
            onClick={() => this.handleCreateFromBackup(backup)}
          >
            Create from Backup
          </DropdownItem>,
        ]}
      />
    );
  }

  public render(): React.ReactElement {
    const { backups, nextScheduledBackup } = this.props;
    const { sortBy, filterValue } = this.state;

    const filtered = this.getFilteredBackups();
    const sorted = this.getSortedBackups(filtered);
    const rows = this.buildRows(sorted);

    const toolbar = (
      <BackupsListToolbar
        filterValue={filterValue}
        nextScheduledBackup={nextScheduledBackup}
        onFilterChange={value => this.handleFilterChange(value)}
        onRestoreClick={() => this.handleRestoreFromBackup()}
      />
    );

    return (
      <>
        <BackupsTable
          columns={COLUMNS}
          rows={rows}
          sortBy={sortBy}
          onSort={(event, index, direction) => this.handleSort(event, index, direction)}
          toolbar={toolbar}
        />
        {rows.length === 0 && backups.length > 0 && (
          <PageSection variant={PageSectionVariants.light} isFilled={true}>
            <span data-testid="backups-nothing-found">No backups match the filter criteria.</span>
          </PageSection>
        )}
      </>
    );
  }
}
