/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { ValidatedOptions } from '@patternfly/react-core';

export type RestoreMode = 'default-registry' | 'external-registry';

export type ValidationState = 'idle' | 'valid' | 'invalid';

const WORKSPACE_NAME_PATTERN = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;

export function sanitizeWorkspaceName(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9-]/g, '');
}

export function sanitizeImageUrl(value: string): string {
  return value.replace(/[<>"'`;|&$]/g, '');
}

export function validateWorkspaceName(name: string): {
  validated: ValidatedOptions;
  error: string;
} {
  if (!name) {
    return { validated: ValidatedOptions.default, error: '' };
  }
  if (name.length > 63) {
    return {
      validated: ValidatedOptions.error,
      error: 'Workspace name must be 63 characters or less.',
    };
  }
  if (!WORKSPACE_NAME_PATTERN.test(name)) {
    return {
      validated: ValidatedOptions.error,
      error:
        'Must contain only lowercase letters, numbers, and hyphens. Must start and end with a letter or number.',
    };
  }
  return { validated: ValidatedOptions.success, error: '' };
}

export function validateWorkspaceNameWithConflicts(
  name: string,
  existingWorkspaceNames: Set<string>,
  existingBackupNames?: Set<string>,
): {
  validated: ValidatedOptions;
  error: string;
  warning: string;
  isValid: boolean;
} {
  const { validated, error } = validateWorkspaceName(name);

  if (validated === ValidatedOptions.success && existingWorkspaceNames.has(name)) {
    return {
      validated: ValidatedOptions.error,
      error: 'A workspace with this name already exists.',
      warning: '',
      isValid: false,
    };
  }

  if (validated === ValidatedOptions.success && existingBackupNames?.has(name)) {
    return {
      validated: ValidatedOptions.warning,
      error: '',
      warning: `A backup named "${name}" already exists. The new workspace will be associated with that backup.`,
      isValid: true,
    };
  }

  return {
    validated,
    error,
    warning: '',
    isValid: validated === ValidatedOptions.success,
  };
}
