/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by AI Assistant

import {
  Alert,
  AlertVariant,
  Button,
  ButtonVariant,
  Divider,
  PageSection,
  PageSectionVariants,
  Title,
} from '@patternfly/react-core';
import React, { useCallback, useEffect, useState } from 'react';
import { connect, ConnectedProps } from 'react-redux';
import { NavigateFunction } from 'react-router-dom';

import EditorSelector from '@/components/EditorSelector';
import Head from '@/components/Head';
import { Spacer } from '@/components/Spacer';
import { ConfirmationModal } from '@/pages/RestoreFromBackup/ConfirmationModal';
import { DefaultRegistryRestoreData } from '@/pages/RestoreFromBackup/DefaultRegistryForm';
import { ExternalRegistryRestoreData } from '@/pages/RestoreFromBackup/ExternalRegistryForm';
import { RestoreMode } from '@/pages/RestoreFromBackup/helpers';
import { ResourceLimitsPanel } from '@/pages/RestoreFromBackup/ResourceLimitsPanel';
import { RestoreModeAccordion } from '@/pages/RestoreFromBackup/RestoreModeAccordion';
import { buildIdeLoaderLocation, toHref } from '@/services/helpers/location';
import { Workspace } from '@/services/workspace-adapter';
import { AppDispatch, RootState } from '@/store';
import { fetchBackupConfig, fetchBackupList } from '@/store/Backups/actions';
import { selectBackupConfig, selectNamespaceBackups } from '@/store/Backups/selectors';
import { selectDefaultNamespace } from '@/store/InfrastructureNamespaces/selectors';
import { selectDefaultEditor } from '@/store/ServerConfig/selectors';
import { workspacesActionCreators } from '@/store/Workspaces';
import { selectAllWorkspaces } from '@/store/Workspaces/selectors';

type MappedProps = ConnectedProps<typeof connector>;

type Props = MappedProps & {
  navigate: NavigateFunction;
  initialBackupImageUrl?: string;
  initialExternalImageUrl?: string;
};

type RestoreData = DefaultRegistryRestoreData | ExternalRegistryRestoreData | null;

export const RestoreFromBackupPage: React.FC<Props> = props => {
  const {
    initialBackupImageUrl,
    initialExternalImageUrl,
    defaultNamespace,
    defaultEditor,
    backups,
    existingWorkspaceNames,
    existingBackupNames,
    navigate,
  } = props;

  const isBackupConfigured = Boolean(props.backupConfig?.registry);

  const initialMode: RestoreMode =
    isBackupConfigured && (initialBackupImageUrl || !initialExternalImageUrl)
      ? 'default-registry'
      : 'external-registry';

  const [editorDefinition, setEditorDefinition] = useState<string | undefined>(undefined);
  const [memoryLimit, setMemoryLimit] = useState<number>(0);
  const [cpuLimit, setCpuLimit] = useState<number>(0);
  const [restoreMode, setRestoreMode] = useState<RestoreMode>(initialMode);
  const [isConfirmModalOpen, setIsConfirmModalOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState('');
  const [restoreData, setRestoreData] = useState<RestoreData>(null);
  const [isFormValid, setIsFormValid] = useState(false);

  // Fetch backup list and config on mount — thunk-level TTL caching prevents duplicate requests
  useEffect(() => {
    const namespace = defaultNamespace.name;
    if (namespace) {
      props.fetchBackupList({ namespace });
      props.fetchBackupConfig({ namespace });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleEditorSelect = useCallback((editorDef: string | undefined) => {
    setEditorDefinition(editorDef);
  }, []);

  const handleModeChange = useCallback((mode: RestoreMode) => {
    setRestoreMode(mode);
    setRestoreData(null);
    setIsFormValid(false);
  }, []);

  // Item 2: Single handler for both default and external registry validation
  const handleValidationChange = useCallback((isValid: boolean, data: RestoreData) => {
    setIsFormValid(isValid);
    setRestoreData(data);
  }, []);

  const handleConfirmCancel = useCallback(() => {
    setIsConfirmModalOpen(false);
  }, []);

  const handleConfirmRestore = useCallback(async () => {
    setIsConfirmModalOpen(false);
    setIsSubmitting(true);
    setSubmitError('');

    try {
      if (!restoreData) {
        throw new Error('No restore data available');
      }

      const { workspaceName, imageUrl } = restoreData;
      const namespace = defaultNamespace.name;
      const resolvedEditorId = editorDefinition ?? defaultEditor;

      await props.restoreFromBackup(
        namespace,
        workspaceName,
        imageUrl,
        resolvedEditorId,
        memoryLimit > 0 ? memoryLimit : undefined,
        cpuLimit > 0 ? cpuLimit : undefined,
      );

      const location = buildIdeLoaderLocation({ namespace, name: workspaceName } as Workspace);
      window.open(toHref(location), '_blank');

      // Navigate current tab back to the backups list — the restore form is now stale.
      navigate('/workspaces?view=backups');
    } catch (e: unknown) {
      const errorMessage = e instanceof Error ? e.message : 'Failed to initiate restore.';
      setIsSubmitting(false);
      setSubmitError(errorMessage);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    restoreData,
    defaultNamespace.name,
    editorDefinition,
    defaultEditor,
    memoryLimit,
    cpuLimit,
    navigate,
  ]);

  const handleRestoreClick = useCallback(() => {
    if (restoreData && existingBackupNames.has(restoreData.workspaceName)) {
      setIsConfirmModalOpen(true);
    } else {
      handleConfirmRestore();
    }
  }, [restoreData, existingBackupNames, handleConfirmRestore]);

  const actionButton = (
    <Button
      variant={ButtonVariant.primary}
      isDisabled={!isFormValid || isSubmitting}
      isLoading={isSubmitting}
      onClick={handleRestoreClick}
      data-testid="restore-submit-button"
    >
      Restore Workspace
    </Button>
  );

  return (
    <React.Fragment>
      <Head pageName="Restore from Backup" />

      <PageSection variant={PageSectionVariants.default}>
        <Title headingLevel="h1">Restore from Backup</Title>
      </PageSection>

      <Divider />

      <PageSection variant={PageSectionVariants.default}>
        {submitError && (
          <Alert
            variant={AlertVariant.danger}
            title="Restore failed"
            isInline
            data-testid="restore-error-alert"
          >
            {submitError}
          </Alert>
        )}

        <RestoreModeAccordion
          data-testid="restore-from-backup-page"
          restoreMode={restoreMode}
          isBackupConfigured={isBackupConfigured}
          onChange={handleModeChange}
          backups={backups}
          existingWorkspaceNames={existingWorkspaceNames}
          existingBackupNames={existingBackupNames}
          onDefaultRegistryValidationChange={handleValidationChange}
          initialBackupImageUrl={initialBackupImageUrl}
          initialExternalImageUrl={initialExternalImageUrl}
          onExternalRegistryValidationChange={handleValidationChange}
          actionButton={actionButton}
        />

        <Spacer />

        <ResourceLimitsPanel
          memoryLimit={memoryLimit}
          cpuLimit={cpuLimit}
          onMemoryLimitChange={setMemoryLimit}
          onCpuLimitChange={setCpuLimit}
        />

        <Spacer />

        <EditorSelector defaultEditorId={defaultEditor} onSelect={handleEditorSelect} />
      </PageSection>

      {restoreData && (
        <ConfirmationModal
          isOpen={isConfirmModalOpen}
          restoreMode={restoreMode}
          workspaceName={restoreData.workspaceName}
          imageUrl={restoreData.imageUrl}
          hasBackupConflict={existingBackupNames.has(restoreData.workspaceName)}
          onConfirm={handleConfirmRestore}
          onCancel={handleConfirmCancel}
        />
      )}
    </React.Fragment>
  );
};

const mapStateToProps = (state: RootState) => {
  const defaultNamespace = selectDefaultNamespace(state);
  const namespace = defaultNamespace.name;
  const allWorkspaces = selectAllWorkspaces(state);
  const existingWorkspaceNames = new Set(allWorkspaces.map(ws => ws.name));

  const backups = selectNamespaceBackups(state, namespace);
  const existingBackupNames = new Set(backups.map(b => b.workspaceName));

  return {
    defaultNamespace,
    backups,
    defaultEditor: selectDefaultEditor(state),
    backupConfig: selectBackupConfig(state),
    existingWorkspaceNames,
    existingBackupNames,
  };
};

const mapDispatchToProps = (dispatch: AppDispatch) => ({
  fetchBackupList: (params: { namespace: string }) => dispatch(fetchBackupList(params)),
  fetchBackupConfig: (params: { namespace: string }) => dispatch(fetchBackupConfig(params)),
  restoreFromBackup: (
    namespace: string,
    workspaceName: string,
    backupImageUrl: string,
    editorId: string,
    memoryLimit?: number,
    cpuLimit?: number,
  ) =>
    dispatch(
      workspacesActionCreators.restoreFromBackup(
        namespace,
        workspaceName,
        backupImageUrl,
        editorId,
        memoryLimit,
        cpuLimit,
      ),
    ),
});

const connector = connect(mapStateToProps, mapDispatchToProps);

export default connector(RestoreFromBackupPage);
