/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by AI Assistant

import { ValidatedOptions } from '@patternfly/react-core';
import { useCallback, useState } from 'react';

import { sanitizeWorkspaceName, validateWorkspaceName } from '@/pages/RestoreFromBackup/helpers';

export type WorkspaceNameValidation = {
  workspaceName: string;
  workspaceNameValidated: ValidatedOptions;
  workspaceNameError: string;
  workspaceNameWarning: string;
  setWorkspaceName: (name: string) => void;
  handleWorkspaceNameChange: (value: string) => void;
};

export function useRestoreFormValidation(
  existingWorkspaceNames?: Set<string>,
  existingBackupNames?: Set<string>,
): WorkspaceNameValidation {
  const [workspaceName, setWorkspaceNameState] = useState('');
  const [workspaceNameValidated, setWorkspaceNameValidated] = useState<ValidatedOptions>(
    ValidatedOptions.default,
  );
  const [workspaceNameError, setWorkspaceNameError] = useState('');
  const [workspaceNameWarning, setWorkspaceNameWarning] = useState('');

  const setWorkspaceName = useCallback(
    (name: string) => {
      const { validated, error } = validateWorkspaceName(name);

      // Check for name conflict if existingWorkspaceNames is provided
      if (validated === ValidatedOptions.success && existingWorkspaceNames?.has(name)) {
        setWorkspaceNameState(name);
        setWorkspaceNameValidated(ValidatedOptions.error);
        setWorkspaceNameError('A workspace with this name already exists.');
        setWorkspaceNameWarning('');
        return;
      }

      // Check for backup name conflict (warning, not error — user can proceed)
      if (validated === ValidatedOptions.success && existingBackupNames?.has(name)) {
        setWorkspaceNameState(name);
        setWorkspaceNameValidated(ValidatedOptions.warning);
        setWorkspaceNameError('');
        setWorkspaceNameWarning(
          `A backup named "${name}" already exists. The new workspace will be associated with that backup.`,
        );
        return;
      }

      setWorkspaceNameState(name);
      setWorkspaceNameValidated(validated);
      setWorkspaceNameError(error);
      setWorkspaceNameWarning('');
    },
    [existingWorkspaceNames, existingBackupNames],
  );

  const handleWorkspaceNameChange = useCallback(
    (value: string) => {
      const sanitized = sanitizeWorkspaceName(value);
      setWorkspaceName(sanitized);
    },
    [setWorkspaceName],
  );

  return {
    workspaceName,
    workspaceNameValidated,
    workspaceNameError,
    workspaceNameWarning,
    setWorkspaceName,
    handleWorkspaceNameChange,
  };
}
