/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupStatus } from '@eclipse-che/common';
import { configureStore } from '@reduxjs/toolkit';

import * as BackupApi from '@/services/backend-client/backupApi';
import {
  fetchBackupConfig,
  fetchBackupList,
  fetchWorkspaceBackupStatus,
  validateBackupImage,
} from '@/store/Backups/actions';
import { reducer, unloadedState } from '@/store/Backups/reducer';

jest.mock('@/services/backend-client/backupApi');
const mockedBackupApi = BackupApi as jest.Mocked<typeof BackupApi>;

function createTestStore() {
  return configureStore({
    reducer: { backups: reducer },
    preloadedState: { backups: unloadedState },
  }) as any;
}

describe('Backup Actions', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('fetchBackupConfig', () => {
    const namespace = 'user-che';

    it('should fetch backup config successfully', async () => {
      const mockConfig = {
        enabled: true,
        schedule: '0 1 * * *',
        registry: 'image-registry.openshift-image-registry.svc:5000',
        backupSchedule: '0 1 * * *',
      };
      mockedBackupApi.getBackupConfig.mockResolvedValueOnce(mockConfig);

      const store = createTestStore();
      const result = await store.dispatch(fetchBackupConfig({ namespace }));

      expect(result.type).toBe('backups/fetchBackupConfig/fulfilled');
      expect(result.payload).toEqual(mockConfig);
      expect(store.getState().backups.backupConfig).toEqual(mockConfig);
      expect(store.getState().backups.loading.configLoadingCount).toBe(0);
    });

    it('should handle API error', async () => {
      mockedBackupApi.getBackupConfig.mockRejectedValueOnce(
        new Error('Failed to fetch backup configuration'),
      );

      const store = createTestStore();
      const result = await store.dispatch(fetchBackupConfig({ namespace }));

      expect(result.type).toBe('backups/fetchBackupConfig/rejected');
      expect(store.getState().backups.backupConfig).toBeUndefined();
      expect(store.getState().backups.loading.configLoadingCount).toBe(0);
    });

    it('should set configLoadingCount during request', async () => {
      let resolvePromise!: (value: any) => void;
      const pending = new Promise(resolve => {
        resolvePromise = resolve;
      });
      mockedBackupApi.getBackupConfig.mockReturnValueOnce(pending as any);

      const store = createTestStore();
      const dispatchPromise = store.dispatch(fetchBackupConfig({ namespace }));

      expect(store.getState().backups.loading.configLoadingCount).toBe(1);

      resolvePromise({
        enabled: false,
        schedule: '',
        registry: '',
      });
      await dispatchPromise;

      expect(store.getState().backups.loading.configLoadingCount).toBe(0);
    });
  });

  describe('fetchWorkspaceBackupStatus', () => {
    const namespace = 'user-che';
    const workspaceName = 'my-workspace';
    const workspaceUID = 'workspace-123';

    it('should fetch workspace backup status successfully', async () => {
      const mockBackupInfo = {
        status: BackupStatus.SUCCESS,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        backupSchedule: '0 1 * * *',
        backupImageUrl:
          'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
        sizeBytes: 1024000,
      };

      mockedBackupApi.getWorkspaceBackupStatus.mockResolvedValueOnce(mockBackupInfo);

      const store = createTestStore();
      const result = await store.dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(mockedBackupApi.getWorkspaceBackupStatus).toHaveBeenCalledWith(
        namespace,
        workspaceName,
      );
      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/fulfilled');
      expect(result.payload).toEqual(mockBackupInfo);
    });

    it('should handle successful fetch with NEVER status', async () => {
      const mockBackupInfo = {
        status: BackupStatus.NEVER,
        backupSchedule: '0 1 * * *',
      };

      mockedBackupApi.getWorkspaceBackupStatus.mockResolvedValueOnce(mockBackupInfo);

      const store = createTestStore();
      const result = await store.dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.payload).toEqual(mockBackupInfo);
      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/fulfilled');
    });

    it('should handle API error', async () => {
      mockedBackupApi.getWorkspaceBackupStatus.mockRejectedValueOnce(
        new Error('Workspace not found'),
      );

      const store = createTestStore();
      const result = await store.dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/rejected');
      expect(result.payload).toBe('Workspace not found');
    });

    it('should handle error without message', async () => {
      mockedBackupApi.getWorkspaceBackupStatus.mockRejectedValueOnce('unknown error');

      const store = createTestStore();
      const result = await store.dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/rejected');
      expect(result.payload).toBe('Failed to fetch backup status');
    });

    it('should handle IN_PROGRESS status', async () => {
      const mockBackupInfo = {
        status: BackupStatus.IN_PROGRESS,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        backupImageUrl:
          'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
      };

      mockedBackupApi.getWorkspaceBackupStatus.mockResolvedValueOnce(mockBackupInfo);

      const store = createTestStore();
      const result = await store.dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.payload).toEqual(mockBackupInfo);
    });

    it('should handle FAILED status with error', async () => {
      const mockBackupInfo = {
        status: BackupStatus.FAILED,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        error: 'Backup job failed: insufficient storage',
      };

      mockedBackupApi.getWorkspaceBackupStatus.mockResolvedValueOnce(mockBackupInfo);

      const store = createTestStore();
      const result = await store.dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.payload).toEqual(mockBackupInfo);
      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/fulfilled');
    });

    it('should update store state on success', async () => {
      const mockBackupInfo = {
        status: BackupStatus.SUCCESS,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
      };

      mockedBackupApi.getWorkspaceBackupStatus.mockResolvedValueOnce(mockBackupInfo);

      const store = createTestStore();
      await store.dispatch(fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }));

      const state = store.getState().backups;
      expect(state.byWorkspace[workspaceUID]).toEqual(mockBackupInfo);
      expect(state.loading.loadingCount).toBe(0);
    });

    it('should set error state on failure', async () => {
      mockedBackupApi.getWorkspaceBackupStatus.mockRejectedValueOnce(new Error('API error'));

      const store = createTestStore();
      await store.dispatch(fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }));

      const state = store.getState().backups;
      expect(state.error).toBe('API error');
    });
  });

  describe('fetchBackupList', () => {
    const namespace = 'user-che';

    it('should fetch backup list successfully', async () => {
      const mockBackupItems = [
        {
          workspaceName: 'my-workspace',
          imageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          workspaceExists: true,
          labels: {},
        },
        {
          workspaceName: 'other-workspace',
          imageUrl:
            'image-registry.openshift-image-registry.svc:5000/user-che/other-workspace:latest',
          timestamp: '2026-02-09T12:00:00.000Z',
          sizeBytes: 2048000,
          workspaceExists: false,
          labels: {},
        },
      ];

      mockedBackupApi.listBackups.mockResolvedValueOnce(mockBackupItems);

      const store = createTestStore();
      const result = await store.dispatch(fetchBackupList({ namespace }));

      expect(mockedBackupApi.listBackups).toHaveBeenCalledWith(namespace, undefined);
      expect(result.type).toBe('backups/fetchBackupList/fulfilled');
      expect(result.payload).toEqual(mockBackupItems);
    });

    it('should fetch backup list with workspace name filter', async () => {
      const workspaceName = 'my-workspace';
      const mockBackupItems = [
        {
          workspaceName: 'my-workspace',
          imageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          workspaceExists: true,
          labels: {},
        },
      ];

      mockedBackupApi.listBackups.mockResolvedValueOnce(mockBackupItems);

      const store = createTestStore();
      const result = await store.dispatch(fetchBackupList({ namespace, workspaceName }));

      expect(mockedBackupApi.listBackups).toHaveBeenCalledWith(namespace, workspaceName);
      expect(result.payload).toHaveLength(1);
    });

    it('should handle empty backup list', async () => {
      mockedBackupApi.listBackups.mockResolvedValueOnce([]);

      const store = createTestStore();
      const result = await store.dispatch(fetchBackupList({ namespace }));

      expect(result.type).toBe('backups/fetchBackupList/fulfilled');
      expect(result.payload).toEqual([]);
    });

    it('should handle API error', async () => {
      mockedBackupApi.listBackups.mockRejectedValueOnce(new Error('Namespace not found'));

      const store = createTestStore();
      const result = await store.dispatch(fetchBackupList({ namespace }));

      expect(result.type).toBe('backups/fetchBackupList/rejected');
      expect(result.payload).toBe('Namespace not found');
    });

    it('should handle error without message', async () => {
      mockedBackupApi.listBackups.mockRejectedValueOnce('unknown error');

      const store = createTestStore();
      const result = await store.dispatch(fetchBackupList({ namespace }));

      expect(result.type).toBe('backups/fetchBackupList/rejected');
      expect(result.payload).toBe('Failed to fetch backup list');
    });

    it('should update store state with backup list', async () => {
      const mockBackupItems = [
        {
          workspaceName: 'ws1',
          imageUrl: 'registry/ws1:latest',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024,
          workspaceExists: true,
          labels: {},
        },
      ];

      mockedBackupApi.listBackups.mockResolvedValueOnce(mockBackupItems);

      const store = createTestStore();
      await store.dispatch(fetchBackupList({ namespace }));

      const state = store.getState().backups;
      expect(state.byNamespace[namespace]).toEqual(mockBackupItems);
    });
  });

  describe('validateBackupImage', () => {
    const namespace = 'user-che';
    const imageUrl =
      'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest';

    it('should validate accessible backup image successfully', async () => {
      const mockValidationResult = {
        valid: true,
        accessible: true,
        metadata: {
          workspaceName: 'my-workspace',
          namespace: 'user-che',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
        },
      };

      mockedBackupApi.validateBackupImage.mockResolvedValueOnce(mockValidationResult);

      const store = createTestStore();
      const result = await store.dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(mockedBackupApi.validateBackupImage).toHaveBeenCalledWith(namespace, imageUrl);
      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
      expect(result.payload).toEqual(mockValidationResult);
    });

    it('should validate inaccessible backup image', async () => {
      const mockValidationResult = {
        valid: true,
        accessible: false,
      };

      mockedBackupApi.validateBackupImage.mockResolvedValueOnce(mockValidationResult);

      const store = createTestStore();
      const result = await store.dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.payload).toEqual(mockValidationResult);
      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
    });

    it('should handle invalid backup image format', async () => {
      const mockValidationResult = {
        valid: false,
        accessible: false,
        error: 'Invalid image URL format',
      };

      mockedBackupApi.validateBackupImage.mockResolvedValueOnce(mockValidationResult);

      const store = createTestStore();
      const result = await store.dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.payload).toEqual(mockValidationResult);
      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
    });

    it('should handle API error', async () => {
      mockedBackupApi.validateBackupImage.mockRejectedValueOnce(new Error('Image not found'));

      const store = createTestStore();
      const result = await store.dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.type).toBe('backups/validateBackupImage/rejected');
      expect(result.payload).toBe('Image not found');
    });

    it('should handle error without message', async () => {
      mockedBackupApi.validateBackupImage.mockRejectedValueOnce('unknown error');

      const store = createTestStore();
      const result = await store.dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.type).toBe('backups/validateBackupImage/rejected');
      expect(result.payload).toBe('Failed to validate backup image');
    });

    it('should handle timeout result', async () => {
      const mockValidationResult = {
        valid: false,
        accessible: false,
        error: 'Registry query timed out while validating image',
      };

      mockedBackupApi.validateBackupImage.mockResolvedValueOnce(mockValidationResult);

      const store = createTestStore();
      const result = await store.dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
      if (typeof result.payload === 'object' && 'error' in result.payload) {
        expect(result.payload.error).toContain('timed out');
      }
    });
  });
});
