/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupStatus } from '@eclipse-che/common';

import { RootState } from '@/store';
import { unloadedState } from '@/store/Backups/reducer';
import {
  selectAllBackupsByWorkspace,
  selectBackupConfig,
  selectBackupSchedule,
  selectBackupsError,
  selectIsLoadingBackups,
  selectIsUpdatingBackups,
  selectNamespaceBackups,
  selectWorkspaceBackupInfo,
} from '@/store/Backups/selectors';

describe('Backups selectors', () => {
  describe('Basic selectors', () => {
    describe('selectAllBackupsByWorkspace', () => {
      it('should return the byWorkspace map', () => {
        const byWorkspace = {
          'workspace-1': {
            status: BackupStatus.SUCCESS,
            lastBackupTime: '2026-02-10T12:00:00Z',
          },
          'workspace-2': {
            status: BackupStatus.IN_PROGRESS,
          },
        };
        const mockState = {
          backups: {
            ...unloadedState,
            byWorkspace,
          },
        } as Partial<RootState> as RootState;

        const result = selectAllBackupsByWorkspace(mockState);
        expect(result).toEqual(byWorkspace);
      });

      it('should return empty object when no workspaces have backup info', () => {
        const mockState = {
          backups: unloadedState,
        } as Partial<RootState> as RootState;

        const result = selectAllBackupsByWorkspace(mockState);
        expect(result).toEqual({});
      });

      it('should be memoized - return same reference for same input', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            byWorkspace: {
              'workspace-1': {
                status: BackupStatus.SUCCESS,
              },
            },
          },
        } as Partial<RootState> as RootState;

        const result1 = selectAllBackupsByWorkspace(mockState);
        const result2 = selectAllBackupsByWorkspace(mockState);
        expect(result1).toBe(result2);
      });
    });

    it('should select error message', () => {
      const mockState = {
        backups: {
          ...unloadedState,
          error: 'Test error message',
        },
      } as Partial<RootState> as RootState;

      const result = selectBackupsError(mockState);
      expect(result).toBe('Test error message');
    });

    it('should return undefined when no error', () => {
      const mockState = {
        backups: unloadedState,
      } as Partial<RootState> as RootState;

      const result = selectBackupsError(mockState);
      expect(result).toBeUndefined();
    });
  });

  describe('Workspace selectors', () => {
    const workspaceUID = 'workspace-123';
    const backupInfo = {
      status: BackupStatus.SUCCESS,
      lastBackupTime: '2026-02-10T12:00:00Z',
      backupImageUrl: 'registry/namespace/workspace:latest',
      sizeBytes: 1024000,
    };

    describe('selectWorkspaceBackupInfo', () => {
      it('should return backup info for existing workspace', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            byWorkspace: {
              [workspaceUID]: backupInfo,
            },
          },
        } as Partial<RootState> as RootState;

        const result = selectWorkspaceBackupInfo(mockState, workspaceUID);
        expect(result).toEqual(backupInfo);
      });

      it('should return undefined for non-existent workspace', () => {
        const mockState = {
          backups: unloadedState,
        } as Partial<RootState> as RootState;

        const result = selectWorkspaceBackupInfo(mockState, 'unknown-workspace');
        expect(result).toBeUndefined();
      });

      it('should return undefined when byWorkspace is empty', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            byWorkspace: {},
          },
        } as Partial<RootState> as RootState;

        const result = selectWorkspaceBackupInfo(mockState, workspaceUID);
        expect(result).toBeUndefined();
      });
    });
  });

  describe('Namespace selectors', () => {
    const namespace = 'user-che';
    const backupItems = [
      {
        workspaceName: 'workspace-1',
        imageUrl: 'registry/user-che/workspace-1:latest',
        timestamp: '2026-02-10T12:00:00Z',
        sizeBytes: 1024000,
        workspaceExists: true,
        labels: {},
      },
      {
        workspaceName: 'workspace-2',
        imageUrl: 'registry/user-che/workspace-2:latest',
        timestamp: '2026-02-09T12:00:00Z',
        sizeBytes: 2048000,
        workspaceExists: false,
        labels: {},
      },
    ];

    describe('selectNamespaceBackups', () => {
      it('should return backups for existing namespace', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            byNamespace: {
              [namespace]: backupItems,
            },
          },
        } as Partial<RootState> as RootState;

        const result = selectNamespaceBackups(mockState, namespace);
        expect(result).toEqual(backupItems);
      });

      it('should return empty array for non-existent namespace', () => {
        const mockState = {
          backups: unloadedState,
        } as Partial<RootState> as RootState;

        const result = selectNamespaceBackups(mockState, 'unknown-namespace');
        expect(result).toEqual([]);
      });

      it('should return empty array when byNamespace is empty', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            byNamespace: {},
          },
        } as Partial<RootState> as RootState;

        const result = selectNamespaceBackups(mockState, namespace);
        expect(result).toEqual([]);
      });
    });
  });

  describe('Individual loading state selectors', () => {
    it('should select isLoading flag', () => {
      const mockState = {
        backups: {
          ...unloadedState,
          loading: {
            loadingCount: 2,
            updatingCount: 0,
            configLoadingCount: 0,
          },
        },
      } as Partial<RootState> as RootState;

      expect(selectIsLoadingBackups(mockState)).toBe(true);
    });

    it('should select isUpdating flag', () => {
      const mockState = {
        backups: {
          ...unloadedState,
          loading: {
            loadingCount: 0,
            updatingCount: 1,
            configLoadingCount: 0,
          },
        },
      } as Partial<RootState> as RootState;

      expect(selectIsUpdatingBackups(mockState)).toBe(true);
    });

    it('should return false for all loading flags in unloaded state', () => {
      const mockState = {
        backups: unloadedState,
      } as Partial<RootState> as RootState;

      expect(selectIsLoadingBackups(mockState)).toBe(false);
      expect(selectIsUpdatingBackups(mockState)).toBe(false);
    });
  });

  describe('Backup config selectors', () => {
    describe('selectBackupConfig', () => {
      it('should return undefined when not loaded', () => {
        const mockState = {
          backups: unloadedState,
        } as Partial<RootState> as RootState;

        expect(selectBackupConfig(mockState)).toBeUndefined();
      });

      it('should return backup config when loaded', () => {
        const config = {
          enabled: true,
          schedule: '0 1 * * *',
          registry: 'image-registry.openshift-image-registry.svc:5000',
          backupSchedule: '0 1 * * *',
        };
        const mockState = {
          backups: {
            ...unloadedState,
            backupConfig: config,
          },
        } as Partial<RootState> as RootState;

        expect(selectBackupConfig(mockState)).toEqual(config);
      });
    });

    describe('selectBackupSchedule', () => {
      it('should return undefined when config is not loaded', () => {
        const mockState = {
          backups: unloadedState,
        } as Partial<RootState> as RootState;

        expect(selectBackupSchedule(mockState)).toBeUndefined();
      });

      it('should return undefined when backup is disabled', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            backupConfig: {
              enabled: false,
              schedule: '0 1 * * *',
              registry: 'image-registry.svc:5000',
              backupSchedule: '0 1 * * *',
            },
          },
        } as Partial<RootState> as RootState;

        expect(selectBackupSchedule(mockState)).toBeUndefined();
      });

      it('should return schedule when backup is enabled', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            backupConfig: {
              enabled: true,
              schedule: '0 1 * * *',
              registry: 'image-registry.svc:5000',
            },
          },
        } as Partial<RootState> as RootState;

        expect(selectBackupSchedule(mockState)).toBe('0 1 * * *');
      });

      it('should return undefined when enabled but schedule is empty', () => {
        const mockState = {
          backups: {
            ...unloadedState,
            backupConfig: {
              enabled: true,
              schedule: '',
              registry: '',
            },
          },
        } as Partial<RootState> as RootState;

        expect(selectBackupSchedule(mockState)).toBe('');
      });
    });
  });
});
