/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import common from '@eclipse-che/common';
import { AxiosError } from 'axios';
import mockAxios from 'axios';

import { DevfileSchema, fetchDevfileSchema } from '@/services/backend-client/devfileSchemaApi';

const mockGet = mockAxios.get as jest.Mock;

const mockSchema: DevfileSchema = {
  definitions: {
    component: { type: 'object' },
  },
  properties: {
    schemaVersion: { type: 'string' },
    metadata: { type: 'object' },
  },
};

describe('fetchDevfileSchema', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should fetch the devfile schema for a given version', async () => {
    mockGet.mockResolvedValueOnce({ data: mockSchema });

    const result = await fetchDevfileSchema('2.2.2');

    expect(mockGet).toHaveBeenCalledWith('/dashboard/api/devfile', {
      params: { version: '2.2.2' },
    });
    expect(result).toEqual(mockSchema);
  });

  it('should pass the correct version parameter', async () => {
    mockGet.mockResolvedValueOnce({ data: mockSchema });

    await fetchDevfileSchema('2.1.0');

    expect(mockGet).toHaveBeenCalledWith('/dashboard/api/devfile', {
      params: { version: '2.1.0' },
    });
  });

  it('should return a schema with definitions and properties', async () => {
    const schemaWithExtras: DevfileSchema = {
      definitions: {
        container: { type: 'object', properties: {} },
        volume: { type: 'object' },
      },
      properties: {
        schemaVersion: { type: 'string', enum: ['2.2.2'] },
      },
      additionalField: 'extra-value',
    };
    mockGet.mockResolvedValueOnce({ data: schemaWithExtras });

    const result = await fetchDevfileSchema('2.2.2');

    expect(result.definitions).toBeDefined();
    expect(result.properties).toBeDefined();
    expect(result['additionalField']).toBe('extra-value');
  });

  it('should throw an error when the request fails', async () => {
    mockGet.mockRejectedValueOnce({
      code: '500',
      message: 'Server Error',
    } as AxiosError);

    let errorMessage: string | undefined;
    try {
      await fetchDevfileSchema('2.2.2');
    } catch (err) {
      errorMessage = common.helpers.errors.getMessage(err);
    }

    expect(errorMessage).toBe('Failed to fetch devfile schema. Server Error');
  });

  it('should throw an error with a descriptive message on network failure', async () => {
    mockGet.mockRejectedValueOnce({
      code: 'ERR_NETWORK',
      message: 'Network Error',
    } as AxiosError);

    await expect(fetchDevfileSchema('2.2.2')).rejects.toThrow(
      'Failed to fetch devfile schema. Network Error',
    );
  });
});
