/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by AI Assistant

import React from 'react';

import { Props } from '@/pages/RestoreFromBackup/DefaultRegistryForm/ImagePreviewField';

export class ImagePreviewField extends React.PureComponent<Props> {
  public render(): React.ReactNode {
    const { imageUrl } = this.props;

    return (
      <div data-testid="image-preview-field">
        <span data-testid="image-preview-url">{imageUrl}</span>
      </div>
    );
  }
}
