httpRetry: 3

httpTimeout: 600000

packageExtensions:
  "@patternfly/react-icons@*":
    dependencies:
      tslib: "*"
  "@types/react-tooltip@*":
    dependencies:
      react: "*"
      react-dom: "*"
  connected-react-router@*:
    dependencies:
      immutable: "*"
      seamless-immutable: "*"
  monaco-languageclient@*:
    dependencies:
      vscode-languageserver-protocol: "*"
  react-pluralize@*:
    dependencies:
      prop-types: "*"
  redux-mock-store@*:
    dependencies:
      redux: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
