compressionLevel: mixed

enableGlobalCache: false

# Support all target architectures for multi-platform builds
# This ensures optional native dependencies are downloaded for all platforms
supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64
    - s390x
    - ppc64

httpRetry: 3

httpTimeout: 600000

nodeLinker: node-modules

packageExtensions:
  "@patternfly/react-icons@*":
    dependencies:
      tslib: "*"
  "@types/react-tooltip@*":
    dependencies:
      react: "*"
      react-dom: "*"
  connected-react-router@*:
    dependencies:
      immutable: "*"
      seamless-immutable: "*"
  react-pluralize@*:
    dependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-4.9.0.cjs
