yarnPath: ".yarn/releases/yarn-berry.cjs"

httpRetry: 3

httpTimeout: 600000

packageExtensions:
  "@patternfly/react-icons@*":
    dependencies:
      tslib: "*"
  "@types/react-tooltip@*":
    dependencies:
      react: "*"
      react-dom: "*"
  connected-react-router@*:
    dependencies:
      immutable: "*"
      seamless-immutable: "*"
  monaco-languageclient@*:
    dependencies:
      vscode-languageserver-protocol: "*"
  react-pluralize@*:
    dependencies:
      prop-types: "*"
  redux-mock-store@*:
    dependencies:
      redux: "*"
