httpRetry: 3

httpTimeout: 600000

nodeLinker: node-modules

packageExtensions:
  "@patternfly/react-icons@*":
    dependencies:
      tslib: "*"
  "@types/react-tooltip@*":
    dependencies:
      react: "*"
      react-dom: "*"
  connected-react-router@*:
    dependencies:
      immutable: "*"
      seamless-immutable: "*"
  react-pluralize@*:
    dependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-3.8.3.cjs
