yarnPath: .yarn/releases/yarn-2.4.1.cjs
packageExtensions:
  "@patternfly/react-icons@*":
    dependencies:
      "tslib": "*"
  "@types/react-tooltip@*":
    dependencies:
      "react": "*"
      "react-dom": "*"
  "connected-react-router@*":
    dependencies:
      "immutable": "*"
      "seamless-immutable": "*"
  "react-pluralize@*":
    dependencies:
      "prop-types": "*"
httpTimeout: 600000
httpRetry: 3
