/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import {
  Button,
  Content,
  Divider,
  EmptyState,
  EmptyStateBody,
  EmptyStateVariant,
  FormGroup,
  FormHelperText,
  HelperText,
  HelperTextItem,
  InputGroup,
  InputGroupItem,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalVariant,
  PageSection,
  PageSectionVariants,
  SearchInput,
  TextInput,
  Toolbar,
  ToolbarContent,
  ToolbarItem,
} from '@patternfly/react-core';
import { CubesIcon, PlusCircleIcon, TrashIcon } from '@patternfly/react-icons';
import {
  ActionsColumn,
  IAction,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  ThProps,
  Tr,
} from '@patternfly/react-table';
import React from 'react';
import { NavigateFunction } from 'react-router-dom';

import Head from '@/components/Head';
import ProgressIndicator from '@/components/Progress';
import { DeleteConfirmation } from '@/pages/DevfileDetails/DeleteConfirmation';
import { DEVFILE_FALLBACK } from '@/pages/DevfilesList/const';
import styles from '@/pages/DevfilesList/index.module.css';
import match from '@/services/helpers/filter';
import { LocalDevfile } from '@/store/LocalDevfiles';

interface Props {
  devfiles: LocalDevfile[];
  defaultDevfileContent: string | undefined;
  error: string | undefined;
  isLoading: boolean;
  namespace: string;
  navigate: NavigateFunction;
  onCreateDevfile: (name: string, description: string, content: string) => Promise<string>;
  onDeleteDevfile: (id: string) => void;
}

type SortColumn = 'id' | 'name' | 'description';
type SortDirection = 'asc' | 'desc';

interface State {
  isCreating: boolean;
  isModalOpen: boolean;
  newName: string;
  newDescription: string;
  nameError: string | undefined;
  selected: string[];
  isDeleting: boolean;
  filterValue: string;
  sortColumn: SortColumn;
  sortDirection: SortDirection;
  deleteConfirmIds: string[];
  deleteConfirmName: string;
}

export default class DevfilesList extends React.PureComponent<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      isCreating: false,
      isModalOpen: false,
      newName: '',
      newDescription: '',
      nameError: undefined,
      selected: [],
      isDeleting: false,
      filterValue: '',
      sortColumn: 'name',
      sortDirection: 'asc',
      deleteConfirmIds: [],
      deleteConfirmName: '',
    };
  }

  private handleFilterChange = (_event: React.FormEvent<HTMLInputElement>, value: string) => {
    this.setState({ filterValue: value });
  };

  private handleFilterClear = () => {
    this.setState({ filterValue: '' });
  };

  private handleSort = (column: SortColumn) => {
    this.setState(prev => ({
      sortColumn: column,
      sortDirection: prev.sortColumn === column && prev.sortDirection === 'asc' ? 'desc' : 'asc',
    }));
  };

  private getFilteredAndSortedDevfiles(): LocalDevfile[] {
    const { devfiles } = this.props;
    const { filterValue, sortColumn, sortDirection } = this.state;

    let filtered = devfiles;
    if (filterValue.trim()) {
      filtered = devfiles.filter(
        d =>
          match(d.id, filterValue) ||
          match(d.name, filterValue) ||
          match(d.description || '', filterValue),
      );
    }

    const sorted = [...filtered].sort((a, b) => {
      let valA: string;
      let valB: string;
      if (sortColumn === 'id') {
        valA = a.id;
        valB = b.id;
      } else if (sortColumn === 'name') {
        valA = a.name;
        valB = b.name;
      } else {
        valA = a.description || '';
        valB = b.description || '';
      }
      const cmp = valA.localeCompare(valB);
      return sortDirection === 'asc' ? cmp : -cmp;
    });

    return sorted;
  }

  private getSortParams(column: SortColumn): ThProps['sort'] {
    const { sortColumn, sortDirection } = this.state;
    const columnIndexMap: Record<SortColumn, number> = { id: 1, name: 2, description: 3 };
    const columnIndex = columnIndexMap[column];
    return {
      sortBy: {
        index: columnIndexMap[sortColumn],
        direction: sortDirection,
      },
      onSort: () => this.handleSort(column),
      columnIndex,
    };
  }

  private handleOpenModal = () => {
    this.setState({
      isModalOpen: true,
      newName: '',
      newDescription: '',
      nameError: undefined,
    });
  };

  private handleCloseModal = () => {
    this.setState({ isModalOpen: false });
  };

  private handleNameChange = (_event: React.FormEvent, value: string) => {
    const nameError = this.validateName(value);
    this.setState({ newName: value, nameError });
  };

  private handleDescriptionChange = (_event: React.FormEvent, value: string) => {
    this.setState({ newDescription: value });
  };

  private validateName(name: string): string | undefined {
    const trimmed = name.trim();
    if (trimmed.length === 0) {
      return 'Name is required';
    }
    return undefined;
  }

  private handleCreateDevfile = async () => {
    const { defaultDevfileContent, namespace, navigate, onCreateDevfile } = this.props;
    const { newName, newDescription } = this.state;

    const trimmedName = newName.trim();
    const nameError = this.validateName(trimmedName);
    if (nameError) {
      this.setState({ nameError });
      return;
    }

    this.setState({ isCreating: true });
    try {
      const baseContent = defaultDevfileContent || DEVFILE_FALLBACK;
      // Inject name, description, and generateName into the devfile content
      const content = injectMetadata(baseContent, trimmedName, newDescription.trim());
      const data = await onCreateDevfile(trimmedName, newDescription.trim(), content);
      this.setState({ isModalOpen: false });
      navigate(`/devfile/${namespace}/${encodeURIComponent(data)}`);
    } catch (e) {
      console.error('Failed to create devfile:', e);
    } finally {
      this.setState({ isCreating: false });
    }
  };

  private handleOpenDevfile = (id: string) => {
    const { namespace, navigate } = this.props;
    navigate(`/devfile/${namespace}/${encodeURIComponent(id)}`);
  };

  private handleDownloadDevfile = (devfile: LocalDevfile) => {
    const blob = new Blob([devfile.content], { type: 'application/x-yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${devfile.name}.devfile.yaml`;
    a.click();
    URL.revokeObjectURL(url);
  };

  private handleSelect = (id: string, isSelected: boolean) => {
    this.setState(prev => {
      const selected = isSelected ? [...prev.selected, id] : prev.selected.filter(s => s !== id);
      return { selected };
    });
  };

  private handleSelectAll = (isSelected: boolean) => {
    if (isSelected) {
      this.setState({ selected: this.props.devfiles.map(d => d.id) });
    } else {
      this.setState({ selected: [] });
    }
  };

  private handleBulkDelete = () => {
    const { selected } = this.state;
    const { devfiles } = this.props;
    const names = devfiles.filter(d => selected.includes(d.id)).map(d => d.name);
    const label = names.length === 1 ? names[0] : `${names.length} devfiles`;
    this.setState({ deleteConfirmIds: selected, deleteConfirmName: label });
  };

  private handleDeleteConfirm = () => {
    const { onDeleteDevfile } = this.props;
    const { deleteConfirmIds } = this.state;
    for (const id of deleteConfirmIds) {
      onDeleteDevfile(id);
    }
    this.setState({ deleteConfirmIds: [], deleteConfirmName: '', selected: [] });
  };

  private handleDeleteConfirmClose = () => {
    this.setState({ deleteConfirmIds: [], deleteConfirmName: '' });
  };

  private getRowActions = (devfile: LocalDevfile): IAction[] => [
    {
      title: 'Devfile Details',
      onClick: () => this.handleOpenDevfile(devfile.id),
    },
    {
      title: 'Download',
      onClick: () => this.handleDownloadDevfile(devfile),
    },
    {
      title: 'Copy Link',
      onClick: () => {
        const url = `${window.location.origin}/dashboard/api/devfiles/namespace/${this.props.namespace}/${devfile.id}/raw`;
        navigator.clipboard.writeText(url);
      },
    },
    {
      title: 'Delete',
      onClick: () =>
        this.setState({ deleteConfirmIds: [devfile.id], deleteConfirmName: devfile.name }),
      isDanger: true,
    },
  ];

  private renderModal(): React.ReactElement {
    const { isModalOpen, newName, newDescription, nameError, isCreating } = this.state;

    return (
      <Modal
        variant={ModalVariant.small}
        isOpen={isModalOpen}
        onClose={this.handleCloseModal}
        aria-label="Add Devfile"
      >
        <ModalHeader title="Add Devfile" />
        <ModalBody>
          <FormGroup label="Name" isRequired fieldId="devfile-name">
            <TextInput
              id="devfile-name"
              isRequired
              value={newName}
              onChange={this.handleNameChange}
              validated={nameError ? 'error' : 'default'}
              placeholder="my-devfile"
            />
            {nameError && (
              <FormHelperText>
                <HelperText>
                  <HelperTextItem variant="error">{nameError}</HelperTextItem>
                </HelperText>
              </FormHelperText>
            )}
          </FormGroup>
          <br />
          <FormGroup label="Description" fieldId="devfile-description">
            <TextInput
              id="devfile-description"
              value={newDescription}
              onChange={this.handleDescriptionChange}
              placeholder="Optional description for this devfile"
            />
          </FormGroup>
        </ModalBody>
        <ModalFooter>
          <Button
            key="create"
            variant="primary"
            onClick={this.handleCreateDevfile}
            isDisabled={isCreating || !!nameError || newName.trim().length === 0}
            isLoading={isCreating}
          >
            Create
          </Button>
          <Button key="cancel" variant="link" onClick={this.handleCloseModal}>
            Cancel
          </Button>
        </ModalFooter>
      </Modal>
    );
  }

  render(): React.ReactElement {
    const { devfiles } = this.props;
    const { isCreating, selected, isDeleting, filterValue } = this.state;
    const filteredDevfiles = this.getFilteredAndSortedDevfiles();
    const isSelectedAll = selected.length > 0 && selected.length === filteredDevfiles.length;

    return (
      <React.Fragment>
        <Head pageName="Devfiles" />
        <PageSection variant={PageSectionVariants.default}>
          <Content>
            <Content component="h1">Devfiles</Content>
            <Content component="p">
              Create and manage local devfiles. Build devfiles for your projects, then use them to
              create workspaces.
            </Content>
          </Content>
        </PageSection>
        <div className={styles.progressIndicator}>
          <ProgressIndicator isLoading={this.props.isLoading} />
        </div>
        <PageSection
          padding={{ default: 'noPadding' }}
          variant={PageSectionVariants.default}
          isFilled={false}
          style={
            devfiles.length > 0
              ? { borderBottom: '1px solid var(--pf-t--global--border--color--default)' }
              : undefined
          }
        >
          <Divider component="div" className="pf-u-mt-xl" />
          <Toolbar id="devfile-creator-list-toolbar" style={{ paddingBlockStart: '1rem' }}>
            <ToolbarContent>
              {devfiles.length > 0 && (
                <ToolbarItem>
                  <InputGroup>
                    <InputGroupItem isFill>
                      <SearchInput
                        id="devfiles-filter-input"
                        aria-label="Filter devfiles"
                        placeholder="Filter by name or description"
                        value={filterValue}
                        onChange={this.handleFilterChange}
                        onClear={this.handleFilterClear}
                        style={{ marginLeft: '1rem' }}
                      />
                    </InputGroupItem>
                  </InputGroup>
                </ToolbarItem>
              )}
              {devfiles.length > 0 && (
                <ToolbarItem>
                  <Button
                    variant="secondary"
                    aria-label="Delete selected devfiles"
                    icon={<TrashIcon />}
                    iconPosition="left"
                    isDisabled={selected.length === 0 || isDeleting}
                    isLoading={isDeleting}
                    onClick={this.handleBulkDelete}
                    isDanger
                  >
                    Delete ({selected.length})
                  </Button>
                </ToolbarItem>
              )}
              <ToolbarItem align={{ default: 'alignEnd' }}>
                <Button
                  variant="link"
                  aria-label="Add Devfile"
                  icon={<PlusCircleIcon />}
                  iconPosition="left"
                  isLoading={isCreating}
                  isDisabled={isCreating}
                  onClick={this.handleOpenModal}
                >
                  Add Devfile
                </Button>
              </ToolbarItem>
            </ToolbarContent>
          </Toolbar>
          {devfiles.length === 0 ? (
            <EmptyState variant={EmptyStateVariant.sm} icon={CubesIcon} titleText="No Devfiles">
              <EmptyStateBody>
                <Button
                  aria-label="Add devfile"
                  variant="link"
                  isLoading={isCreating}
                  isDisabled={isCreating}
                  onClick={this.handleOpenModal}
                >
                  Add Devfile
                </Button>
              </EmptyStateBody>
            </EmptyState>
          ) : (
            <Table
              aria-label="Devfiles List Table"
              variant="compact"
              className={styles.devfileTable}
            >
              <Thead>
                <Tr>
                  <Th
                    select={{
                      onSelect: (_event, isSelected) => this.handleSelectAll(isSelected),
                      isSelected: isSelectedAll,
                    }}
                  />
                  <Th sort={this.getSortParams('id')}>ID</Th>
                  <Th sort={this.getSortParams('name')}>Name</Th>
                  <Th sort={this.getSortParams('description')}>Description</Th>
                  <Th>Projects</Th>
                  <Th screenReaderText="Actions" />
                </Tr>
              </Thead>
              <Tbody>
                {filteredDevfiles.length === 0 ? (
                  <Tr>
                    <Td colSpan={6}>
                      <EmptyState variant={EmptyStateVariant.sm} titleText="No results found">
                        <EmptyStateBody>
                          No devfiles match the filter criteria. Clear the filter to see all
                          devfiles.
                        </EmptyStateBody>
                      </EmptyState>
                    </Td>
                  </Tr>
                ) : (
                  filteredDevfiles.map((devfile, rowIndex) => (
                    <Tr
                      key={devfile.id}
                      isClickable
                      onRowClick={(event?: React.MouseEvent | React.KeyboardEvent) => {
                        if (!event) {
                          return;
                        }
                        const target = event.target as HTMLElement;
                        if (
                          target.closest('[data-action-cell]') ||
                          target.closest('.pf-v6-c-table__check') ||
                          target.closest('.pf-v6-c-menu-toggle') ||
                          target.closest('.pf-v6-c-menu') ||
                          target.tagName === 'INPUT'
                        ) {
                          return;
                        }
                        this.handleOpenDevfile(devfile.id);
                      }}
                      style={{ verticalAlign: 'middle' }}
                    >
                      <Td
                        select={{
                          rowIndex,
                          onSelect: (_event, isSelected) =>
                            this.handleSelect(devfile.id, isSelected),
                          isSelected: selected.includes(devfile.id),
                        }}
                      />
                      <Td dataLabel="ID" className={styles.cellId}>
                        {devfile.id}
                      </Td>
                      <Td dataLabel="Name">{devfile.name}</Td>
                      <Td dataLabel="Description" className={styles.cellEllipsis}>
                        {devfile.description || '-'}
                      </Td>
                      <Td dataLabel="Projects" className={styles.cellEllipsis}>
                        {devfile.projectNames?.length > 0 ? devfile.projectNames.join(', ') : '-'}
                      </Td>
                      <Td isActionCell data-action-cell>
                        <ActionsColumn items={this.getRowActions(devfile)} />
                      </Td>
                    </Tr>
                  ))
                )}
              </Tbody>
            </Table>
          )}
        </PageSection>
        {this.renderModal()}
        <DeleteConfirmation
          devfileName={this.state.deleteConfirmName}
          isOpen={this.state.deleteConfirmIds.length > 0}
          onConfirm={this.handleDeleteConfirm}
          onClose={this.handleDeleteConfirmClose}
        />
      </React.Fragment>
    );
  }
}

function injectMetadata(baseContent: string, name: string, description: string): string {
  let content = baseContent;

  // Remove existing name/generateName/description from metadata
  content = content.replace(/^\s*name:\s*.+$/m, '');
  content = content.replace(/^\s*generateName:\s*.+$/m, '');
  content = content.replace(/^\s*description:\s*.+$/m, '');

  // Clean up empty lines in metadata section
  content = content.replace(/metadata:\n(\s*\n)+/m, 'metadata:\n');

  // Add name, generateName, and description after metadata:
  const metadataLines = [`  name: ${name}`, `  generateName: ${name}-`];
  if (description) {
    metadataLines.push(`  description: ${description}`);
  }
  content = content.replace(/metadata:\n/, `metadata:\n${metadataLines.join('\n')}\n`);

  return content;
}
