/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import {
  Dropdown,
  DropdownItem,
  DropdownList,
  MenuToggle,
  MenuToggleElement,
  NavGroup,
  NavItem,
  NavList,
  Tooltip,
} from '@patternfly/react-core';
import { EllipsisVIcon } from '@patternfly/react-icons';
import React from 'react';
import { connect, ConnectedProps } from 'react-redux';

import { CheTooltip } from '@/components/CheTooltip';
import { useStatusIcon } from '@/components/Workspace/Status/getStatusIcon';
import statusStyles from '@/components/Workspace/Status/index.module.css';
import styles from '@/Layout/Navigation/index.module.css';
import { DevWorkspaceStatus } from '@/services/helpers/types';
import { RootState } from '@/store';
import { actionCreators, AgentPodStatus } from '@/store/LocalDevfiles';
import { selectAgentPodStatuses } from '@/store/LocalDevfiles/selectors';

function mapPhaseToStatus(phase: string, ready: boolean): DevWorkspaceStatus {
  if (phase === 'Running' && ready) return DevWorkspaceStatus.RUNNING;
  if (phase === 'Running' && !ready) return DevWorkspaceStatus.STARTING;
  if (phase === 'Pending') return DevWorkspaceStatus.STARTING;
  if (phase === 'Failed') return DevWorkspaceStatus.FAILED;
  if (phase === 'Stopped') return DevWorkspaceStatus.STOPPED;
  if (phase === 'Succeeded') return DevWorkspaceStatus.STOPPED;
  if (phase === 'Unknown') return DevWorkspaceStatus.FAILED;
  return DevWorkspaceStatus.STARTING;
}

function AgentStatusIndicator(props: { phase: string; ready: boolean }): React.ReactElement {
  const status = mapPhaseToStatus(props.phase, props.ready);
  const icon = useStatusIcon(status);
  return (
    <CheTooltip content={status.toLocaleUpperCase()}>
      <span className={statusStyles.statusIndicator} data-testid="agent-status-indicator">
        {icon}
      </span>
    </CheTooltip>
  );
}

interface AgentPodItemProps {
  status: AgentPodStatus;
  onStop: (agentId: string) => void;
}

interface AgentPodItemState {
  isDropdownOpen: boolean;
  isHovered: boolean;
  isFocused: boolean;
}

class AgentPodItem extends React.PureComponent<AgentPodItemProps, AgentPodItemState> {
  constructor(props: AgentPodItemProps) {
    super(props);
    this.state = {
      isDropdownOpen: false,
      isHovered: false,
      isFocused: false,
    };
  }

  private handleStop = () => {
    this.setState({ isDropdownOpen: false });
    this.props.onStop(this.props.status.agentId);
  };

  render(): React.ReactElement {
    const { status } = this.props;
    const { isDropdownOpen, isHovered, isFocused } = this.state;
    const displayName = status.name.replace(/^agent-/, '') || status.agentId;
    const isActionsVisible = isHovered || isFocused || isDropdownOpen;

    return (
      <NavItem
        className={styles.navItem}
        preventDefault={true}
        onMouseEnter={() => this.setState({ isHovered: true })}
        onMouseLeave={() => this.setState({ isHovered: false })}
        onFocus={() => this.setState({ isFocused: true })}
        onBlur={e => {
          if (!e.currentTarget.contains(e.relatedTarget as Node)) {
            this.setState({ isFocused: false });
          }
        }}
      >
        <span data-testid="agent-pod-item">
          <AgentStatusIndicator phase={status.phase} ready={status.ready} />
          {displayName.length > 25 ? (
            <Tooltip content={displayName}>
              <span className={styles.titleHover}>{displayName}</span>
            </Tooltip>
          ) : (
            <span className={styles.titleHover}>{displayName}</span>
          )}
        </span>
        <div
          style={{
            position: 'absolute',
            top: 0,
            right: 0,
            visibility: isActionsVisible ? 'visible' : 'hidden',
          }}
          onClick={e => e.stopPropagation()}
        >
          <Dropdown
            isOpen={isDropdownOpen}
            onOpenChange={open => this.setState({ isDropdownOpen: open })}
            toggle={(toggleRef: React.Ref<MenuToggleElement>) => (
              <MenuToggle
                ref={toggleRef}
                variant="plain"
                onClick={() => this.setState({ isDropdownOpen: !isDropdownOpen })}
                isExpanded={isDropdownOpen}
                aria-label="Agent actions"
              >
                <EllipsisVIcon />
              </MenuToggle>
            )}
            popperProps={{ position: 'right' }}
          >
            <DropdownList>
              <DropdownItem key="stop" onClick={this.handleStop}>
                Stop
              </DropdownItem>
            </DropdownList>
          </Dropdown>
        </div>
      </NavItem>
    );
  }
}

type Props = MappedProps & {
  activePath: string;
};

export class NavigationAgentList extends React.PureComponent<Props> {
  private handleStop = (agentId: string) => {
    this.props.stopAgent(agentId);
  };

  render(): React.ReactElement {
    const { agentPodStatuses } = this.props;

    if (agentPodStatuses.length === 0) {
      return <React.Fragment />;
    }

    return (
      <NavList>
        <NavGroup title="AGENT PODS" style={{ marginTop: '25px' }}>
          {agentPodStatuses.map(status => (
            <AgentPodItem key={status.agentId} status={status} onStop={this.handleStop} />
          ))}
        </NavGroup>
      </NavList>
    );
  }
}

const mapStateToProps = (state: RootState) => ({
  agentPodStatuses: selectAgentPodStatuses(state),
});

const mapDispatchToProps = {
  stopAgent: actionCreators.stopAgent,
};

const connector = connect(mapStateToProps, mapDispatchToProps);
type MappedProps = ConnectedProps<typeof connector>;

export default connector(NavigationAgentList);
