/*
 * Copyright (c) 2018-2026 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupItem } from '@eclipse-che/common';
import userEvent from '@testing-library/user-event';
import React from 'react';

import { DefaultRegistryRestoreForm } from '@/pages/RestoreFromBackup/DefaultRegistryForm';
import getComponentRenderer, { screen, waitFor } from '@/services/__mocks__/getComponentRenderer';

const mockOnValidationChange = jest.fn();

const mockBackups: BackupItem[] = [
  {
    workspaceName: 'active-ws',
    imageUrl: 'registry.example.com/ns/active-ws:latest',
    timestamp: '2026-02-11T12:00:00Z',
    sizeBytes: 1024,
    workspaceExists: true,
    labels: {},
  },
  {
    workspaceName: 'deleted-ws',
    imageUrl: 'registry.example.com/ns/deleted-ws:latest',
    timestamp: '2026-02-10T12:00:00Z',
    sizeBytes: 2048,
    workspaceExists: false,
    labels: {},
  },
];

const { renderComponent } = getComponentRenderer(getComponent);

describe('DefaultRegistryRestoreForm', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should call onValidationChange(false) initially', () => {
    renderComponent();

    expect(mockOnValidationChange).toHaveBeenCalledWith(false, null);
  });

  test('should call onValidationChange(true) when backup selected and name is valid', async () => {
    renderComponent();

    // Open dropdown and select a deleted backup (no name conflict)
    await userEvent.click(screen.getByText('Select a backup to restore'));
    await userEvent.click(screen.getByText('deleted-ws (Deleted)'));

    await waitFor(() => {
      expect(mockOnValidationChange).toHaveBeenCalledWith(
        true,
        expect.objectContaining({
          workspaceName: 'deleted-ws',
          imageUrl: 'registry.example.com/ns/deleted-ws:latest',
        }),
      );
    });
  });

  test('should show error when active backup selected with existing workspace name', async () => {
    renderComponent({ existingWorkspaceNames: new Set(['active-ws']) });

    await userEvent.click(screen.getByText('Select a backup to restore'));
    await userEvent.click(screen.getByText('active-ws (Active)'));

    await waitFor(() => {
      expect(screen.getByText('A workspace with this name already exists.')).toBeInTheDocument();
    });

    // Error state — user cannot proceed
    expect(mockOnValidationChange).toHaveBeenLastCalledWith(false, null);
  });

  test('should render workspace name input', () => {
    renderComponent();

    expect(screen.getByLabelText('Workspace name')).toBeInTheDocument();
  });

  test('should render backup selector when backups provided', () => {
    renderComponent();

    expect(screen.getByText('Select a backup to restore')).toBeInTheDocument();
  });

  test('should render action button', () => {
    renderComponent();

    expect(screen.getByTestId('test-action-button')).toBeInTheDocument();
  });
});

function getComponent(
  options: {
    backups?: BackupItem[];
    existingWorkspaceNames?: Set<string>;
  } = {},
) {
  return (
    <DefaultRegistryRestoreForm
      backups={options.backups ?? mockBackups}
      existingWorkspaceNames={options.existingWorkspaceNames ?? new Set()}
      existingBackupNames={new Set()}
      onValidationChange={mockOnValidationChange}
      actionButton={<button data-testid="test-action-button">Restore</button>}
    />
  );
}
