/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import {
  BackupConfig,
  BackupInfo,
  BackupStatus,
  DEVWORKSPACE_BACKUP_ANNOTATIONS,
  DEVWORKSPACE_BACKUP_LABELS,
} from '@eclipse-che/common';
import * as k8s from '@kubernetes/client-node';
import { V1JobList } from '@kubernetes/client-node';

import { dwoConfigName, dwoNamespace } from '@/constants/config';
import { createError } from '@/devworkspaceClient/services/helpers/createError';
import {
  BatchV1API,
  prepareBatchV1API,
} from '@/devworkspaceClient/services/helpers/prepareBatchV1API';
import {
  CustomObjectAPI,
  prepareCustomObjectAPI,
} from '@/devworkspaceClient/services/helpers/prepareCustomObjectAPI';

const BACKUP_CONFIG_ERROR_LABEL = 'BACKUP_CONFIG_ERROR';
const BACKUP_STATUS_ERROR_LABEL = 'BACKUP_STATUS_ERROR';

const DEVWORKSPACE_OPERATOR_CONFIG_GROUP = 'controller.devfile.io';
const DEVWORKSPACE_OPERATOR_CONFIG_VERSION = 'v1alpha1';
const DEVWORKSPACE_OPERATOR_CONFIG_PLURAL = 'devworkspaceoperatorconfigs';

const DEVWORKSPACE_GROUP = 'workspace.devfile.io';
const DEVWORKSPACE_VERSION = 'v1alpha2';
const DEVWORKSPACE_PLURAL = 'devworkspaces';

interface RegistryConfig {
  path?: string;
  authSecret?: string;
}

interface DevWorkspaceOperatorConfig {
  apiVersion: string;
  kind: string;
  metadata: {
    name: string;
  };
  config?: {
    workspace?: {
      backupCronJob?: {
        enable?: boolean; // Note: lowercase 'enable' per DWO API
        schedule?: string;
        registry?: RegistryConfig; // Nested object with path and authSecret
        image?: string; // Backup container image
        serviceAccount?: string; // Service account for backup jobs (no 'Name' suffix)
        backoffLimit?: number;
      };
    };
  };
}

interface DevWorkspaceResource {
  metadata?: {
    annotations?: Record<string, string>;
  };
}

function isDevWorkspaceOperatorConfig(obj: unknown): obj is DevWorkspaceOperatorConfig {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    (obj as DevWorkspaceOperatorConfig).kind === 'DevWorkspaceOperatorConfig'
  );
}

function isDevWorkspaceResource(obj: unknown): obj is DevWorkspaceResource {
  return (
    typeof obj === 'object' && obj !== null && (obj as { kind?: string }).kind === 'DevWorkspace'
  );
}

export class BackupApiService {
  private readonly batchV1API: BatchV1API;
  private readonly customObjectAPI: CustomObjectAPI;

  constructor(kubeConfig: k8s.KubeConfig) {
    this.batchV1API = prepareBatchV1API(kubeConfig);
    this.customObjectAPI = prepareCustomObjectAPI(kubeConfig);
  }

  /**
   * Get cluster-wide backup configuration from DevWorkspaceOperatorConfig
   */
  async getClusterBackupConfig(): Promise<BackupConfig> {
    try {
      const response = await this.customObjectAPI.getNamespacedCustomObject({
        group: DEVWORKSPACE_OPERATOR_CONFIG_GROUP,
        version: DEVWORKSPACE_OPERATOR_CONFIG_VERSION,
        namespace: dwoNamespace,
        plural: DEVWORKSPACE_OPERATOR_CONFIG_PLURAL,
        name: dwoConfigName,
      });

      if (!isDevWorkspaceOperatorConfig(response)) {
        throw new Error('Unexpected response format for DevWorkspaceOperatorConfig');
      }
      const backupCronJob = response.config?.workspace?.backupCronJob;
      const schedule = backupCronJob?.schedule ?? '';

      return {
        enabled: backupCronJob?.enable ?? false,
        schedule,
        registry: backupCronJob?.registry?.path ?? '',
        authSecretName: backupCronJob?.registry?.authSecret,
      };
    } catch (e) {
      throw createError(e, BACKUP_CONFIG_ERROR_LABEL, 'Unable to get cluster backup configuration');
    }
  }

  /**
   * Get backup status for a specific workspace.
   * Reads status from DevWorkspace annotations set by the DWO BackupCronJob controller.
   * Optionally checks for in-progress backup Jobs.
   */
  async getWorkspaceBackupStatus(namespace: string, workspaceName: string): Promise<BackupInfo> {
    try {
      const backupConfig = await this.getClusterBackupConfig();
      const backupSchedule = backupConfig.schedule || undefined;

      // Read DevWorkspace resource to get backup annotations
      const response = await this.customObjectAPI.getNamespacedCustomObject({
        group: DEVWORKSPACE_GROUP,
        version: DEVWORKSPACE_VERSION,
        namespace,
        plural: DEVWORKSPACE_PLURAL,
        name: workspaceName,
      });

      if (!isDevWorkspaceResource(response)) {
        throw new Error('Unexpected response format for DevWorkspace resource');
      }
      const annotations: Record<string, string> = response.metadata?.annotations || {};

      // Construct backup image URL from config (no annotation for this)
      const backupImageUrl = backupConfig.registry
        ? `${backupConfig.registry}/${namespace}/${workspaceName}:latest`
        : undefined;

      // Check for in-progress backup Jobs before reading annotations
      const hasActiveJob = await this.hasActiveBackupJob(namespace, workspaceName);
      if (hasActiveJob) {
        return {
          status: BackupStatus.IN_PROGRESS,
          backupSchedule,
          lastBackupTime: annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
          backupImageUrl,
        };
      }

      // Derive status from annotations
      return this.extractBackupInfoFromAnnotations(annotations, backupSchedule, backupImageUrl);
    } catch (e) {
      throw createError(
        e,
        BACKUP_STATUS_ERROR_LABEL,
        `Unable to get backup status for workspace ${workspaceName}`,
      );
    }
  }

  /**
   * Check if there is an active (in-progress) backup Job for the workspace.
   * Uses the DWO backup label to find relevant Jobs.
   */
  private async hasActiveBackupJob(namespace: string, workspaceName: string): Promise<boolean> {
    try {
      const labelSelector = `${DEVWORKSPACE_BACKUP_LABELS.DEVWORKSPACE_BACKUP}=true,${DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME}=${workspaceName}`;
      const jobList = await this.batchV1API.listNamespacedJob({
        namespace,
        labelSelector,
      });

      const jobs = (jobList as V1JobList).items || [];
      return jobs.some(job => (job.status?.active || 0) > 0);
    } catch {
      // If we can't query Jobs (permissions, etc.), don't block the status response
      return false;
    }
  }

  /**
   * Extract backup status from DevWorkspace annotations set by DWO BackupCronJob controller.
   * The backupImageUrl is constructed from cluster config, not from annotations.
   */
  private extractBackupInfoFromAnnotations(
    annotations: Record<string, string>,
    backupSchedule: string | undefined,
    backupImageUrl: string | undefined,
  ): BackupInfo {
    const lastBackupSuccessful =
      annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
    const lastBackupFinishedAt =
      annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT];

    // No backup annotations present - workspace has never been backed up
    if (lastBackupSuccessful === undefined && lastBackupFinishedAt === undefined) {
      return {
        status: BackupStatus.NEVER,
        backupSchedule,
      };
    }

    const status = lastBackupSuccessful === 'true' ? BackupStatus.SUCCESS : BackupStatus.FAILED;

    const backupInfo: BackupInfo = {
      status,
      backupSchedule,
      lastBackupTime: lastBackupFinishedAt,
      backupImageUrl,
    };

    if (status === BackupStatus.FAILED) {
      backupInfo.error =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] ||
        'Last backup was not successful';
    }

    return backupInfo;
  }
}
