/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import {
  BACKUP_ERROR_CODES,
  BACKUP_IMAGE_DEFAULT_TAG,
  BackupItem,
  BackupStatus,
  DEVWORKSPACE_BACKUP_ANNOTATIONS,
  DEVWORKSPACE_BACKUP_LABELS,
} from '@eclipse-che/common';
import { CustomObjectsApi, KubeConfig } from '@kubernetes/client-node';

import { backupRegistryTimeout, dwoConfigName, dwoNamespace } from '@/constants/config';
import {
  DEVWORKSPACE_GROUP,
  DEVWORKSPACE_OPERATOR_CONFIG_GROUP,
  DEVWORKSPACE_OPERATOR_CONFIG_PLURAL,
  DEVWORKSPACE_OPERATOR_CONFIG_VERSION,
  DEVWORKSPACE_PLURAL,
  DEVWORKSPACE_VERSION,
} from '@/constants/k8s';
import { createError } from '@/devworkspaceClient/services/helpers/createError';
import {
  createRegistryClient,
  detectRegistryType,
  IExternalRegistryClient,
} from '@/devworkspaceClient/services/helpers/externalRegistry';
import {
  CoreV1API,
  prepareCoreV1API,
} from '@/devworkspaceClient/services/helpers/prepareCoreV1API';

// ImageStream constants
const IMAGESTREAM_GROUP = 'image.openshift.io';
const IMAGESTREAM_VERSION = 'v1';

interface IBackupImage {
  workspaceName: string;
  imageUrl: string;
  timestamp: string | undefined;
  sizeBytes: number;
  labels: Record<string, string>;
}

interface DWOCResponse {
  kind: string;
  config?: {
    workspace?: {
      backupCronJob?: {
        registry?: {
          path?: string;
          authSecret?: string;
        };
      };
    };
  };
}

function isDWOCResponse(obj: unknown): obj is DWOCResponse {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    (obj as DWOCResponse).kind === 'DevWorkspaceOperatorConfig'
  );
}

/**
 * Validates Kubernetes DNS-1123 subdomain naming convention
 * Rules: lowercase alphanumeric, hyphens allowed, max 63 chars
 * Must start/end with alphanumeric character
 */
function validateK8sName(name: string, fieldName: string): void {
  const dns1123Pattern = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;

  if (!name || name.length === 0) {
    throw createError(
      new Error('Empty name'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} cannot be empty`,
    );
  }

  if (name.length > 63) {
    throw createError(
      new Error('Name too long'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} exceeds maximum length of 63 characters`,
    );
  }

  if (!dns1123Pattern.test(name)) {
    throw createError(
      new Error('Invalid name format'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} must follow Kubernetes DNS-1123 naming convention: lowercase alphanumeric characters or '-', must start and end with alphanumeric`,
    );
  }
}

export class RegistryApiService {
  private customObjectsApi: CustomObjectsApi;
  private saCustomObjectsApi: CustomObjectsApi;
  private coreV1Api: CoreV1API;
  private saCoreV1Api: CoreV1API;

  constructor(kubeConfig: KubeConfig, saKubeConfig: KubeConfig) {
    this.customObjectsApi = kubeConfig.makeApiClient(CustomObjectsApi);
    this.saCustomObjectsApi = saKubeConfig.makeApiClient(CustomObjectsApi);
    this.coreV1Api = prepareCoreV1API(kubeConfig);
    this.saCoreV1Api = prepareCoreV1API(saKubeConfig);
  }

  /**
   * List backup images from OpenShift ImageStream API.
   * sizeBytes is always 0 — no per-image ImageStreamTag query is made.
   */
  private async listImageStreams(namespace: string): Promise<IBackupImage[]> {
    const response = await this.customObjectsApi.listNamespacedCustomObject({
      group: IMAGESTREAM_GROUP,
      version: IMAGESTREAM_VERSION,
      namespace,
      plural: 'imagestreams',
    });

    const items = (response as unknown as { items: any[] }).items;
    const results: IBackupImage[] = [];

    for (const is of items) {
      const workspaceId = is.metadata?.labels?.[DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_ID];
      if (!workspaceId) continue;

      const workspaceName = is.metadata.name as string;
      const latestTag = is.status?.tags?.find((t: any) => t.tag === BACKUP_IMAGE_DEFAULT_TAG);

      if (!latestTag?.items?.length) {
        // ImageStream exists but no :latest — UNAVAILABLE
        results.push({
          workspaceName,
          imageUrl: '',
          timestamp: undefined,
          sizeBytes: 0,
          labels: {
            [DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL]: BackupStatus.UNAVAILABLE,
          },
        });
        continue;
      }

      const imageUrl = is.status?.dockerImageRepository
        ? `${is.status.dockerImageRepository}:${BACKUP_IMAGE_DEFAULT_TAG}`
        : '';

      results.push({
        workspaceName,
        imageUrl,
        timestamp: latestTag.items[0].created as string,
        sizeBytes: 0,
        labels: {},
      });
    }

    return results;
  }

  /**
   * Get backup registry path and auth secret name from DevWorkspaceOperatorConfig
   */
  private async getBackupRegistryPath(): Promise<{ registryPath: string; authSecret?: string }> {
    try {
      const response = await this.saCustomObjectsApi.getNamespacedCustomObject({
        group: DEVWORKSPACE_OPERATOR_CONFIG_GROUP,
        version: DEVWORKSPACE_OPERATOR_CONFIG_VERSION,
        namespace: dwoNamespace,
        plural: DEVWORKSPACE_OPERATOR_CONFIG_PLURAL,
        name: dwoConfigName,
      });

      if (!isDWOCResponse(response)) {
        throw new Error('Unexpected response format for DevWorkspaceOperatorConfig');
      }
      const registryPath = response.config?.workspace?.backupCronJob?.registry?.path;
      const authSecret = response.config?.workspace?.backupCronJob?.registry?.authSecret;

      if (!registryPath) {
        throw new Error('Backup registry path not configured');
      }

      return { registryPath: registryPath.replace(/\/+$/, ''), authSecret };
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        'Unable to get backup registry configuration',
      );
    }
  }

  /**
   * Reads the registry auth credentials from the DWOC authSecret.
   * Returns a pre-formed Authorization header value, or empty string.
   *
   * Lookup order:
   * 1. quay-api-token key → "Bearer <token>"  (OAuth/robot API token)
   * 2. .dockerconfigjson auths entry → "Basic <rawBase64>"  (standard docker creds)
   * 3. Neither present → ""  (public repos, no auth header sent)
   */
  private async getRegistryCredentials(secretName: string, registryHost: string): Promise<string> {
    try {
      const secret = await this.saCoreV1Api.readNamespacedSecret({
        name: secretName,
        namespace: dwoNamespace,
      });

      // 1. Preferred: dedicated OAuth/robot API token
      const apiTokenRaw = secret.data?.['quay-api-token'];
      if (apiTokenRaw) {
        return `Bearer ${Buffer.from(apiTokenRaw, 'base64').toString('utf-8').trim()}`;
      }

      // 2. Fallback: .dockerconfigjson
      const dockerConfigJson = secret.data?.['.dockerconfigjson'];
      if (!dockerConfigJson) {
        return '';
      }

      const dockerConfig = JSON.parse(Buffer.from(dockerConfigJson, 'base64').toString('utf-8'));
      const authEntry = dockerConfig?.auths?.[registryHost];
      if (!authEntry?.auth) {
        return '';
      }

      return `Basic ${authEntry.auth.trim()}`;
    } catch {
      return '';
    }
  }

  /**
   * List all DevWorkspaces in the namespace (unfiltered)
   */
  private async listAllDevWorkspaces(namespace: string): Promise<any[]> {
    try {
      const response = await this.customObjectsApi.listNamespacedCustomObject({
        group: DEVWORKSPACE_GROUP,
        version: DEVWORKSPACE_VERSION,
        namespace,
        plural: DEVWORKSPACE_PLURAL,
      });

      return (response as unknown as { items: any[] }).items;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list DevWorkspaces in namespace ${namespace}`,
      );
    }
  }

  /**
   * Build BackupItem from DevWorkspace annotations
   * Used for external registry backups where ImageStream is not available
   */
  private buildBackupItemFromAnnotations(
    devworkspace: any,
    registryPath: string,
    namespace: string,
  ): BackupItem {
    const workspaceName = devworkspace.metadata.name;
    const annotations = devworkspace.metadata.annotations || {};

    const imageUrl = `${registryPath}/${namespace}/${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`;

    const backupLabels: Record<string, string> = {};
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
    }
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
    }

    return {
      workspaceName,
      imageUrl,
      timestamp: annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
      sizeBytes: 0, // Unknown for external registry
      workspaceExists: true, // DevWorkspace exists (we're querying it)
      labels: backupLabels,
    };
  }

  /**
   * Lists backup images for a namespace, optionally filtered by workspace name.
   */
  async listBackupImages(namespace: string, workspaceName?: string): Promise<BackupItem[]> {
    validateK8sName(namespace, 'namespace');
    if (workspaceName) {
      validateK8sName(workspaceName, 'workspaceName');
    }

    try {
      // Step 1: Read DWOC registry config. If backup is not configured (or DWOC is not
      // accessible), return an empty list immediately — no point querying user-namespace data.
      let registryPath: string;
      let authSecret: string | undefined;
      try {
        ({ registryPath, authSecret } = await this.getBackupRegistryPath());
      } catch {
        return [];
      }

      // Step 2: Get registry credentials for external registries
      const registryType = detectRegistryType(registryPath);
      let registryClient: IExternalRegistryClient | undefined;
      if (registryType !== 'openshift-internal') {
        const registryHost = registryPath.split('/')[0];
        const authHeader = authSecret
          ? await this.getRegistryCredentials(authSecret, registryHost)
          : '';
        registryClient = createRegistryClient(registryPath, authHeader);
      }

      // Step 3: Query exactly one registry source + DevWorkspaces concurrently.
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      type ListResult = [IBackupImage[] | string[], any[]];
      const [registryResults, allDevWorkspaces] = (await Promise.race([
        Promise.all([
          registryType === 'openshift-internal'
            ? this.listImageStreams(namespace).catch((): IBackupImage[] => [])
            : registryClient!.listWorkspaceBackups(namespace),
          this.listAllDevWorkspaces(namespace),
        ]),
        timeoutPromise,
      ])) as ListResult;

      const allWorkspaceNames = new Set<string>(
        allDevWorkspaces.map((dw: any) => dw.metadata?.name).filter(Boolean),
      );
      const devworkspacesWithBackups = allDevWorkspaces.filter(
        (dw: any) =>
          dw.metadata?.annotations?.[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
      );

      const backupMap = new Map<string, BackupItem>();

      if (registryType === 'openshift-internal') {
        // --- ImageStream merge logic ---
        const imageStreamResults = registryResults as IBackupImage[];
        for (const image of imageStreamResults) {
          const exists = allWorkspaceNames.has(image.workspaceName);
          const matchingDW = devworkspacesWithBackups.find(
            (dw: any) => dw.metadata.name === image.workspaceName,
          );
          const dwAnnotations = matchingDW?.metadata?.annotations || {};
          const mergedLabels: Record<string, string> = { ...image.labels };
          mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
            dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] ??
            mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] ??
            'true';
          if (dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
            mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
              dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
          }
          const timestamp =
            dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT] ??
            image.timestamp;
          const resolvedImageUrl = image.imageUrl
            ? `${registryPath}/${namespace}/${image.workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`
            : image.imageUrl;
          const mapKey = resolvedImageUrl || `unavailable:${image.workspaceName}`;
          backupMap.set(mapKey, {
            ...image,
            imageUrl: resolvedImageUrl,
            timestamp,
            workspaceExists: exists,
            labels: mergedLabels,
          });
        }

        // Annotation-only workspaces not found in ImageStream
        const imageStreamWorkspaceNames = new Set(imageStreamResults.map(img => img.workspaceName));
        for (const dw of devworkspacesWithBackups) {
          if (imageStreamWorkspaceNames.has(dw.metadata.name)) continue;
          const backupItem = this.buildBackupItemFromAnnotations(dw, registryPath, namespace);
          backupMap.set(backupItem.imageUrl, backupItem);
        }
      } else {
        // --- External registry merge logic ---
        const externalWorkspaceNames = new Set<string>(registryResults as string[]);

        // 1. External registry discovered workspaces (includes deleted ones)
        for (const wsName of externalWorkspaceNames) {
          const matchingDW = devworkspacesWithBackups.find(
            (dw: any) => dw.metadata.name === wsName,
          );
          const dwAnnotations = matchingDW?.metadata?.annotations ?? {};
          const imageUrl = `${registryPath}/${namespace}/${wsName}:${BACKUP_IMAGE_DEFAULT_TAG}`;
          backupMap.set(imageUrl, {
            workspaceName: wsName,
            imageUrl,
            timestamp: dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
            sizeBytes: 0,
            workspaceExists: allWorkspaceNames.has(wsName),
            labels: {
              [DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL]: 'true',
              ...(dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR]
                ? {
                    [DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR]:
                      dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR],
                  }
                : {}),
            },
          });
        }

        // 2. Annotation-only DevWorkspaces not found in registry
        for (const dw of devworkspacesWithBackups) {
          const wsName = dw.metadata.name;
          const imageUrl = `${registryPath}/${namespace}/${wsName}:${BACKUP_IMAGE_DEFAULT_TAG}`;
          if (backupMap.has(imageUrl)) continue;

          const dwAnnotations = dw.metadata.annotations ?? {};
          backupMap.set(imageUrl, {
            workspaceName: wsName,
            imageUrl,
            timestamp: dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
            sizeBytes: 0,
            workspaceExists: true,
            labels: {
              [DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL]: BackupStatus.UNAVAILABLE,
              ...(dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR]
                ? {
                    [DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR]:
                      dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR],
                  }
                : {}),
            },
          });
        }
      }

      // Show entries that have either a confirmed image URL (registry-listed) or a recorded
      // timestamp (DW annotation). Filters out UNAVAILABLE ImageStream entries where no
      // backup has ever completed and no annotation exists — pure initialization artifacts.
      const backupsWithEvidence = Array.from(backupMap.values()).filter(
        backup => backup.imageUrl !== '' || backup.timestamp !== undefined,
      );
      const filteredBackups = workspaceName
        ? backupsWithEvidence.filter(backup => backup.workspaceName === workspaceName)
        : backupsWithEvidence;

      return filteredBackups;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list backup images in namespace '${namespace}'`,
      );
    }
  }
}
