/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import {
  BACKUP_ERROR_CODES,
  BACKUP_IMAGE_DEFAULT_TAG,
  BackupItem,
  BackupListResponse,
  BackupValidationResult,
  DEVWORKSPACE_BACKUP_ANNOTATIONS,
} from '@eclipse-che/common';
import { KubeConfig } from '@kubernetes/client-node';
import { CustomObjectsApi } from '@kubernetes/client-node';

import { backupRegistryTimeout } from '@/constants/config';
import { createError } from '@/devworkspaceClient/services/helpers/createError';
import { IRegistryAdapter } from '@/devworkspaceClient/services/helpers/registryAdapters';

// DevWorkspaceOperatorConfig constants
const DWOC_GROUP = 'controller.devfile.io';
const DWOC_VERSION = 'v1alpha1';
const DWOC_PLURAL = 'devworkspaceoperatorconfigs';
const DWOC_NAME = 'devworkspace-operator-config';
const DWOC_NAMESPACE = 'openshift-operators';

// DevWorkspace constants
const DEVWORKSPACE_GROUP = 'workspace.devfile.io';
const DEVWORKSPACE_VERSION = 'v1alpha2';
const DEVWORKSPACE_PLURAL = 'devworkspaces';

/**
 * Validates Kubernetes DNS-1123 subdomain naming convention
 * Rules: lowercase alphanumeric, hyphens allowed, max 63 chars
 * Must start/end with alphanumeric character
 */
function validateK8sName(name: string, fieldName: string): void {
  const dns1123Pattern = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;

  if (!name || name.length === 0) {
    throw createError(
      new Error('Empty name'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} cannot be empty`,
    );
  }

  if (name.length > 63) {
    throw createError(
      new Error('Name too long'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} exceeds maximum length of 63 characters`,
    );
  }

  if (!dns1123Pattern.test(name)) {
    throw createError(
      new Error('Invalid name format'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} must follow Kubernetes DNS-1123 naming convention: lowercase alphanumeric characters or '-', must start and end with alphanumeric`,
    );
  }
}

export class RegistryApiService {
  private adapter: IRegistryAdapter;
  private customObjectsApi: CustomObjectsApi;

  constructor(kubeConfig: KubeConfig, adapter: IRegistryAdapter) {
    this.adapter = adapter;
    this.customObjectsApi = kubeConfig.makeApiClient(CustomObjectsApi);
  }

  /**
   * Check if a DevWorkspace exists in the namespace
   */
  private async doesWorkspaceExist(namespace: string, workspaceName: string): Promise<boolean> {
    try {
      await this.customObjectsApi.getNamespacedCustomObject({
        group: DEVWORKSPACE_GROUP,
        version: DEVWORKSPACE_VERSION,
        namespace,
        plural: DEVWORKSPACE_PLURAL,
        name: workspaceName,
      });
      return true;
    } catch (e) {
      // Handle both old HttpError (response.statusCode) and new ApiException (code) formats
      const statusCode = (e as any)?.response?.statusCode ?? (e as any)?.code;
      if (statusCode === 404) {
        return false;
      }
      // On error, assume workspace exists (fail-safe)
      return true;
    }
  }

  /**
   * Get backup registry path from DevWorkspaceOperatorConfig
   */
  private async getBackupRegistryPath(): Promise<string> {
    try {
      const response = await this.customObjectsApi.getNamespacedCustomObject({
        group: DWOC_GROUP,
        version: DWOC_VERSION,
        namespace: DWOC_NAMESPACE,
        plural: DWOC_PLURAL,
        name: DWOC_NAME,
      });

      const operatorConfig = (response as any).body || response;
      const registryPath = operatorConfig.config?.workspace?.backupCronJob?.registry?.path;

      if (!registryPath) {
        throw new Error('Backup registry path not configured');
      }

      return registryPath;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        'Unable to get backup registry configuration',
      );
    }
  }

  /**
   * List all DevWorkspaces in the namespace (unfiltered)
   */
  private async listAllDevWorkspaces(namespace: string): Promise<any[]> {
    try {
      const response = await this.customObjectsApi.listNamespacedCustomObject({
        group: DEVWORKSPACE_GROUP,
        version: DEVWORKSPACE_VERSION,
        namespace,
        plural: DEVWORKSPACE_PLURAL,
      });

      return (response as unknown as { items: any[] }).items;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list DevWorkspaces in namespace ${namespace}`,
      );
    }
  }

  /**
   * Build BackupItem from DevWorkspace annotations
   * Used for external registry backups where ImageStream is not available
   */
  private buildBackupItemFromAnnotations(
    devworkspace: any,
    registryPath: string,
    namespace: string,
  ): BackupItem {
    const workspaceName = devworkspace.metadata.name;
    const annotations = devworkspace.metadata.annotations || {};

    const imageUrl = `${registryPath}/${namespace}/${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`;

    const backupLabels: Record<string, string> = {};
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
    }
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
    }

    return {
      workspaceName,
      imageUrl,
      timestamp: annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
      sizeBytes: 0, // Unknown for external registry
      workspaceExists: true, // DevWorkspace exists (we're querying it)
      labels: backupLabels,
    };
  }

  /**
   * Lists backup images for a namespace, optionally filtered by workspace name.
   */
  async listBackupImages(namespace: string, workspaceName?: string): Promise<BackupListResponse> {
    validateK8sName(namespace, 'namespace');
    if (workspaceName) {
      validateK8sName(workspaceName, 'workspaceName');
    }

    try {
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      // Only two concurrent calls now — registry path is fetched lazily
      const imageStreamPromise = this.adapter.listBackupImages(namespace);
      const allDevWorkspacesPromise = this.listAllDevWorkspaces(namespace);

      const [imageStreamResults, allDevWorkspaces] = await Promise.race([
        Promise.all([imageStreamPromise, allDevWorkspacesPromise]),
        timeoutPromise,
      ]);

      if (!Array.isArray(imageStreamResults)) {
        throw createError(
          new Error('Invalid response from registry adapter'),
          BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
          'Expected array of backup images from ImageStreams',
        );
      }

      // Derive both structures from the single DW list fetch
      const devworkspacesWithBackups = allDevWorkspaces.filter(
        (dw: any) =>
          dw.metadata?.annotations?.[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
      );
      const allWorkspaceNames = new Set<string>(
        allDevWorkspaces.map((dw: any) => dw.metadata?.name).filter(Boolean),
      );

      const backupMap = new Map<string, BackupItem>();

      // Bug 4 fix: use Set lookup instead of per-image API call
      for (const image of imageStreamResults) {
        const exists = allWorkspaceNames.has(image.workspaceName);
        const matchingDW = devworkspacesWithBackups.find(
          (dw: any) => dw.metadata.name === image.workspaceName,
        );
        const dwAnnotations = matchingDW?.metadata?.annotations || {};
        const mergedLabels: Record<string, string> = { ...image.labels };
        // Precedence for LAST_BACKUP_SUCCESSFUL:
        // 1. DevWorkspace annotation (explicit, most authoritative)
        // 2. Adapter-set value (e.g., BackupStatus.UNAVAILABLE for tagless ImageStreams)
        // 3. 'true' default — :latest tag existing proves a backup completed successfully
        mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
          dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] ??
          mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] ??
          'true';
        if (dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
          mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
            dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
        }
        // Timestamp precedence:
        // 1. DevWorkspace annotation LAST_BACKUP_FINISHED_AT (authoritative backup completion time)
        // 2. Image timestamp from adapter (for ImageStreams with :latest tag, this is image creation time)
        const timestamp =
          dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT] ?? image.timestamp;
        // Bug 2 fix: use composite key for entries with empty imageUrl to avoid collision
        const mapKey = image.imageUrl || `unavailable:${image.workspaceName}`;
        backupMap.set(mapKey, {
          ...image,
          timestamp,
          workspaceExists: exists,
          labels: mergedLabels,
        });
      }

      // Bug 3 fix: only fetch registry path when annotation-only workspaces exist
      const imageStreamWorkspaceNames = new Set(imageStreamResults.map(img => img.workspaceName));
      const annotationOnlyDWs = devworkspacesWithBackups.filter(
        (dw: any) => !imageStreamWorkspaceNames.has(dw.metadata.name),
      );
      if (annotationOnlyDWs.length > 0) {
        const registryPath = await this.getBackupRegistryPath();
        for (const dw of annotationOnlyDWs) {
          const backupItem = this.buildBackupItemFromAnnotations(dw, registryPath, namespace);
          backupMap.set(backupItem.imageUrl, backupItem);
        }
      }

      const allBackups = Array.from(backupMap.values());
      // Filter out entries with no backup (empty timestamp = no backup ever completed)
      const backupsWithData = allBackups.filter(backup => backup.timestamp !== '');
      const filteredBackups = workspaceName
        ? backupsWithData.filter(backup => backup.workspaceName === workspaceName)
        : backupsWithData;

      return {
        backups: filteredBackups,
        total: filteredBackups.length,
        page: 1,
        perPage: filteredBackups.length,
      };
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list backup images in namespace '${namespace}'`,
      );
    }
  }

  /**
   * Validates if a backup image is accessible.
   */
  async validateBackupImage(imageUrl: string): Promise<BackupValidationResult> {
    if (!imageUrl || imageUrl.trim().length === 0) {
      throw createError(
        new Error('Empty image URL'),
        BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
        'Image URL cannot be empty',
      );
    }

    try {
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      const accessibilityPromise = this.adapter.validateImageAccessibility(imageUrl);
      const metadataPromise = this.adapter.getImageMetadata(imageUrl);

      const [accessible, metadata] = await Promise.race([
        Promise.all([accessibilityPromise, metadataPromise]),
        timeoutPromise,
      ]);

      return {
        valid: true,
        accessible,
        metadata: accessible
          ? {
              workspaceName: metadata.workspaceName,
              namespace: metadata.namespace,
              timestamp: metadata.timestamp,
              sizeBytes: metadata.sizeBytes,
            }
          : undefined,
      };
    } catch (e) {
      if ((e as Error).message === 'Registry query timeout') {
        return {
          valid: false,
          accessible: false,
          error: 'Registry query timed out while validating image',
        };
      }

      return {
        valid: false,
        accessible: false,
        error: (e as Error).message || 'Unknown error during validation',
      };
    }
  }

  /**
   * Retrieves metadata for a specific backup image.
   */
  async getImageMetadata(imageUrl: string): Promise<BackupItem> {
    if (!imageUrl || imageUrl.trim().length === 0) {
      throw createError(
        new Error('Empty image URL'),
        BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
        'Image URL cannot be empty',
      );
    }

    try {
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      const metadata = await Promise.race([
        this.adapter.getImageMetadata(imageUrl),
        timeoutPromise,
      ]);

      if (!metadata || typeof metadata !== 'object') {
        throw createError(
          new Error('Invalid metadata response'),
          BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
          'Expected image metadata object',
        );
      }

      const workspaceExists = await this.doesWorkspaceExist(
        metadata.namespace,
        metadata.workspaceName,
      );

      return {
        workspaceName: metadata.workspaceName,
        imageUrl,
        timestamp: metadata.timestamp,
        sizeBytes: metadata.sizeBytes,
        workspaceExists,
        labels: metadata.labels,
      };
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to retrieve metadata for backup image: ${imageUrl}`,
      );
    }
  }
}
