/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import {
  BACKUP_ERROR_CODES,
  BACKUP_IMAGE_DEFAULT_TAG,
  BACKUP_IMAGE_URL_PATTERN,
  BackupItem,
  BackupListResponse,
  BackupStatus,
  BackupValidationResult,
  DEVWORKSPACE_BACKUP_ANNOTATIONS,
  DEVWORKSPACE_BACKUP_LABELS,
} from '@eclipse-che/common';
import { CustomObjectsApi, KubeConfig } from '@kubernetes/client-node';

import { backupRegistryTimeout } from '@/constants/config';
import { createError } from '@/devworkspaceClient/services/helpers/createError';

// DevWorkspaceOperatorConfig constants
const DWOC_GROUP = 'controller.devfile.io';
const DWOC_VERSION = 'v1alpha1';
const DWOC_PLURAL = 'devworkspaceoperatorconfigs';
const DWOC_NAME = 'devworkspace-operator-config';
const DWOC_NAMESPACE = 'openshift-operators';

// DevWorkspace constants
const DEVWORKSPACE_GROUP = 'workspace.devfile.io';
const DEVWORKSPACE_VERSION = 'v1alpha2';
const DEVWORKSPACE_PLURAL = 'devworkspaces';

// ImageStream constants
const IMAGESTREAM_GROUP = 'image.openshift.io';
const IMAGESTREAM_VERSION = 'v1';

interface IBackupImage {
  workspaceName: string;
  imageUrl: string;
  timestamp: string;
  sizeBytes: number;
  labels: Record<string, string>;
}

/**
 * Validates Kubernetes DNS-1123 subdomain naming convention
 * Rules: lowercase alphanumeric, hyphens allowed, max 63 chars
 * Must start/end with alphanumeric character
 */
function validateK8sName(name: string, fieldName: string): void {
  const dns1123Pattern = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;

  if (!name || name.length === 0) {
    throw createError(
      new Error('Empty name'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} cannot be empty`,
    );
  }

  if (name.length > 63) {
    throw createError(
      new Error('Name too long'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} exceeds maximum length of 63 characters`,
    );
  }

  if (!dns1123Pattern.test(name)) {
    throw createError(
      new Error('Invalid name format'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} must follow Kubernetes DNS-1123 naming convention: lowercase alphanumeric characters or '-', must start and end with alphanumeric`,
    );
  }
}

export class RegistryApiService {
  private customObjectsApi: CustomObjectsApi;

  constructor(kubeConfig: KubeConfig) {
    this.customObjectsApi = kubeConfig.makeApiClient(CustomObjectsApi);
  }

  /**
   * List backup images from OpenShift ImageStream API.
   * sizeBytes is always 0 — no per-image ImageStreamTag query is made.
   */
  private async listImageStreams(namespace: string): Promise<IBackupImage[]> {
    const response = await this.customObjectsApi.listNamespacedCustomObject({
      group: IMAGESTREAM_GROUP,
      version: IMAGESTREAM_VERSION,
      namespace,
      plural: 'imagestreams',
    });

    const items = (response as unknown as { items: any[] }).items;
    const results: IBackupImage[] = [];

    for (const is of items) {
      const workspaceId = is.metadata?.labels?.[DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_ID];
      if (!workspaceId) continue;

      const workspaceName = is.metadata.name as string;
      const latestTag = is.status?.tags?.find((t: any) => t.tag === BACKUP_IMAGE_DEFAULT_TAG);

      if (!latestTag?.items?.length) {
        // ImageStream exists but no :latest — UNAVAILABLE
        results.push({
          workspaceName,
          imageUrl: '',
          timestamp: '',
          sizeBytes: 0,
          labels: {
            [DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL]: BackupStatus.UNAVAILABLE,
          },
        });
        continue;
      }

      const imageUrl = is.status?.dockerImageRepository
        ? `${is.status.dockerImageRepository}:${BACKUP_IMAGE_DEFAULT_TAG}`
        : '';

      results.push({
        workspaceName,
        imageUrl,
        timestamp: latestTag.items[0].created as string,
        sizeBytes: 0,
        labels: {},
      });
    }

    return results;
  }

  /**
   * Get backup registry path from DevWorkspaceOperatorConfig
   */
  private async getBackupRegistryPath(): Promise<string> {
    try {
      const response = await this.customObjectsApi.getNamespacedCustomObject({
        group: DWOC_GROUP,
        version: DWOC_VERSION,
        namespace: DWOC_NAMESPACE,
        plural: DWOC_PLURAL,
        name: DWOC_NAME,
      });

      const operatorConfig = (response as any).body || response;
      const registryPath = operatorConfig.config?.workspace?.backupCronJob?.registry?.path;

      if (!registryPath) {
        throw new Error('Backup registry path not configured');
      }

      return registryPath;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        'Unable to get backup registry configuration',
      );
    }
  }

  /**
   * List all DevWorkspaces in the namespace (unfiltered)
   */
  private async listAllDevWorkspaces(namespace: string): Promise<any[]> {
    try {
      const response = await this.customObjectsApi.listNamespacedCustomObject({
        group: DEVWORKSPACE_GROUP,
        version: DEVWORKSPACE_VERSION,
        namespace,
        plural: DEVWORKSPACE_PLURAL,
      });

      return (response as unknown as { items: any[] }).items;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list DevWorkspaces in namespace ${namespace}`,
      );
    }
  }

  /**
   * Build BackupItem from DevWorkspace annotations
   * Used for external registry backups where ImageStream is not available
   */
  private buildBackupItemFromAnnotations(
    devworkspace: any,
    registryPath: string,
    namespace: string,
  ): BackupItem {
    const workspaceName = devworkspace.metadata.name;
    const annotations = devworkspace.metadata.annotations || {};

    const imageUrl = `${registryPath}/${namespace}/${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`;

    const backupLabels: Record<string, string> = {};
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
    }
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
    }

    return {
      workspaceName,
      imageUrl,
      timestamp: annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
      sizeBytes: 0, // Unknown for external registry
      workspaceExists: true, // DevWorkspace exists (we're querying it)
      labels: backupLabels,
    };
  }

  /**
   * Lists backup images for a namespace, optionally filtered by workspace name.
   */
  async listBackupImages(namespace: string, workspaceName?: string): Promise<BackupListResponse> {
    validateK8sName(namespace, 'namespace');
    if (workspaceName) {
      validateK8sName(workspaceName, 'workspaceName');
    }

    try {
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      // All three fetched concurrently. Registry path is always needed: it is the
      // authoritative source for imageUrl (matches what DWO actually pushed to).
      // A failure is caught gracefully so a missing DWOC does not break listing.
      const imageStreamPromise = this.listImageStreams(namespace);
      const allDevWorkspacesPromise = this.listAllDevWorkspaces(namespace);
      const registryPathPromise = this.getBackupRegistryPath().catch(() => null);

      const [imageStreamResults, allDevWorkspaces, registryPath] = await Promise.race([
        Promise.all([imageStreamPromise, allDevWorkspacesPromise, registryPathPromise]),
        timeoutPromise,
      ]);

      // Derive both structures from the single DW list fetch
      const devworkspacesWithBackups = allDevWorkspaces.filter(
        (dw: any) =>
          dw.metadata?.annotations?.[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
      );
      const allWorkspaceNames = new Set<string>(
        allDevWorkspaces.map((dw: any) => dw.metadata?.name).filter(Boolean),
      );

      const backupMap = new Map<string, BackupItem>();

      for (const image of imageStreamResults) {
        const exists = allWorkspaceNames.has(image.workspaceName);
        const matchingDW = devworkspacesWithBackups.find(
          (dw: any) => dw.metadata.name === image.workspaceName,
        );
        const dwAnnotations = matchingDW?.metadata?.annotations || {};
        const mergedLabels: Record<string, string> = { ...image.labels };
        // Precedence for LAST_BACKUP_SUCCESSFUL:
        // 1. DevWorkspace annotation (explicit, most authoritative)
        // 2. ImageStream-set value (e.g., BackupStatus.UNAVAILABLE for tagless ImageStreams)
        // 3. 'true' default — :latest tag existing proves a backup completed successfully
        mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
          dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] ??
          mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] ??
          'true';
        if (dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
          mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
            dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
        }
        // Timestamp precedence:
        // 1. DevWorkspace annotation LAST_BACKUP_FINISHED_AT (authoritative backup completion time)
        // 2. Image timestamp from ImageStream (image creation time)
        const timestamp =
          dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT] ?? image.timestamp;
        // imageUrl precedence:
        // 1. DWOC registry.path — authoritative; matches the URL DWO pushed to
        // 2. ImageStream-provided URL (from ImageStream status.dockerImageRepository) — fallback
        // Keep '' for UNAVAILABLE images (imageUrl === '' means no backup image yet).
        const resolvedImageUrl =
          registryPath && image.imageUrl
            ? `${registryPath}/${namespace}/${image.workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`
            : image.imageUrl;
        const mapKey = resolvedImageUrl || `unavailable:${image.workspaceName}`;
        backupMap.set(mapKey, {
          ...image,
          imageUrl: resolvedImageUrl,
          timestamp,
          workspaceExists: exists,
          labels: mergedLabels,
        });
      }

      // Annotation-only workspaces: have backup annotations but no corresponding ImageStream.
      // Only surface them when registryPath is known — it is required to construct imageUrl.
      const imageStreamWorkspaceNames = new Set(imageStreamResults.map(img => img.workspaceName));
      const annotationOnlyDWs = devworkspacesWithBackups.filter(
        (dw: any) => !imageStreamWorkspaceNames.has(dw.metadata.name),
      );
      if (annotationOnlyDWs.length > 0 && registryPath) {
        for (const dw of annotationOnlyDWs) {
          const backupItem = this.buildBackupItemFromAnnotations(dw, registryPath, namespace);
          backupMap.set(backupItem.imageUrl, backupItem);
        }
      }

      const allBackups = Array.from(backupMap.values());
      // Filter out entries with no backup (empty timestamp = no backup ever completed)
      const backupsWithData = allBackups.filter(backup => backup.timestamp !== '');
      const filteredBackups = workspaceName
        ? backupsWithData.filter(backup => backup.workspaceName === workspaceName)
        : backupsWithData;

      return {
        backups: filteredBackups,
        total: filteredBackups.length,
        page: 1,
        perPage: filteredBackups.length,
      };
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list backup images in namespace '${namespace}'`,
      );
    }
  }

  /**
   * Validates if a backup image URL is valid and parses its components.
   */
  async validateBackupImage(imageUrl: string): Promise<BackupValidationResult> {
    if (!imageUrl || imageUrl.trim().length === 0) {
      throw createError(
        new Error('Empty image URL'),
        BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
        'Image URL cannot be empty',
      );
    }

    if (!BACKUP_IMAGE_URL_PATTERN.test(imageUrl)) {
      return { valid: false, accessible: false, error: 'Invalid image URL format' };
    }

    // Parse: registry[:port]/namespace/workspaceName:tag
    const parts = imageUrl.split('/');
    const workspaceName = parts[parts.length - 1].split(':')[0];
    const namespace = parts[parts.length - 2];

    return {
      valid: true,
      accessible: true,
      metadata: { workspaceName, namespace, timestamp: '', sizeBytes: 0 },
    };
  }
}
