/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import * as k8s from '@kubernetes/client-node';

import { createError } from '@/devworkspaceClient/services/helpers/createError';
import { ISccPermissionApi } from '@/devworkspaceClient/types';

const ERROR_LABEL = 'SCC_PERMISSION_API_ERROR';

export class SccPermissionApiService implements ISccPermissionApi {
  private readonly authorizationApi: k8s.AuthorizationV1Api;

  constructor(kc: k8s.KubeConfig) {
    this.authorizationApi = kc.makeApiClient(k8s.AuthorizationV1Api);
  }

  async checkSccPermission(namespace: string, sccName: string): Promise<boolean> {
    try {
      const review: k8s.V1SelfSubjectAccessReview = {
        apiVersion: 'authorization.k8s.io/v1',
        kind: 'SelfSubjectAccessReview',
        spec: {
          resourceAttributes: {
            namespace,
            verb: 'use',
            group: 'security.openshift.io',
            resource: 'securitycontextconstraints',
            name: sccName,
          },
        },
      };

      const response = await this.authorizationApi.createSelfSubjectAccessReview({
        body: review,
      });
      return response.status?.allowed === true;
    } catch (error) {
      throw createError(error, ERROR_LABEL, 'Unable to check SCC permission');
    }
  }
}
