/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by AI Assistant

import { render, screen } from '@testing-library/react';
import React from 'react';

import { AiSelectorDocsLink } from '@/components/AiSelector/DocsLink';

describe('AiSelectorDocsLink', () => {
  it('should render with default docs URL', () => {
    render(<AiSelectorDocsLink />);

    const link = screen.getByRole('link', { name: /learn more about ai providers/i });
    expect(link).toHaveAttribute(
      'href',
      'https://eclipse.dev/che/docs/stable/end-user-guide/ai-provider/',
    );
  });

  it('should render with custom docs URL', () => {
    render(<AiSelectorDocsLink docsUrl="https://example.com/docs" />);

    const link = screen.getByRole('link', { name: /learn more about ai providers/i });
    expect(link).toHaveAttribute('href', 'https://example.com/docs');
  });
});
