/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import common, { api } from '@eclipse-che/common';
import { createAction } from '@reduxjs/toolkit';

import { fetchAiAgentRegistry } from '@/services/backend-client/aiAgentRegistryApi';
import { AppThunk } from '@/store';

export const aiAgentRegistryRequestAction = createAction('aiAgentRegistry/request');
export const aiAgentRegistryReceiveAction =
  createAction<api.IAiAgentRegistry>('aiAgentRegistry/receive');
export const aiAgentRegistryErrorAction = createAction<string>('aiAgentRegistry/error');

export const actionCreators = {
  requestAiAgentRegistry:
    (): AppThunk =>
    async (dispatch): Promise<void> => {
      try {
        dispatch(aiAgentRegistryRequestAction());

        const registry = await fetchAiAgentRegistry();
        dispatch(aiAgentRegistryReceiveAction(registry));
      } catch (e) {
        const errorMessage =
          'Failed to fetch AI agent registry, reason: ' + common.helpers.errors.getMessage(e);
        dispatch(aiAgentRegistryErrorAction(errorMessage));
      }
    },
};
