/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { helpers } from '@eclipse-che/common';
import { createAction } from '@reduxjs/toolkit';

import { injectKubeConfig, podmanLogin } from '@/services/backend-client/devWorkspaceApi';
import { AppThunk } from '@/store';

export const kubeconfigRefreshRequestAction = createAction('kubeconfig/refreshRequest');

export const kubeconfigRefreshSuccessAction = createAction('kubeconfig/refreshSuccess');

export const kubeconfigRefreshErrorAction = createAction<string>('kubeconfig/refreshError');

export const actionCreators = {
  refreshKubeconfig:
    (namespace: string, devworkspaceId: string): AppThunk =>
    async dispatch => {
      dispatch(kubeconfigRefreshRequestAction());

      try {
        await injectKubeConfig(namespace, devworkspaceId);
        await podmanLogin(namespace, devworkspaceId);
        dispatch(kubeconfigRefreshSuccessAction());
      } catch (e) {
        const errorMessage = helpers.errors.getMessage(e);
        dispatch(kubeconfigRefreshErrorAction(errorMessage));
        throw e;
      }
    },
};
