apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-operators
spec:
  components:
    dashboard:
      deployment:
        containers:
          - image: che-dashboard
            imagePullPolicy: Always
