/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { FormGroup, HelperText, HelperTextItem } from '@patternfly/react-core';
import React from 'react';

export type Props = {
  imageUrl: string;
};

export class ImagePreviewField extends React.PureComponent<Props> {
  public render() {
    const { imageUrl } = this.props;

    if (!imageUrl) {
      return null;
    }

    return (
      <FormGroup fieldId="restore-image-preview" label="Backup image URL">
        {/* <div className={styles.imagePreview} data-testid="image-preview"> */}
        {imageUrl}
        {/* </div> */}
        <HelperText>
          <HelperTextItem>
            This URL will be used to locate the backup image in the cluster registry.
          </HelperTextItem>
        </HelperText>
      </FormGroup>
    );
  }
}
