/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { ValidatedOptions } from '@patternfly/react-core';
import userEvent from '@testing-library/user-event';
import React from 'react';

import { ImageUrlField } from '@/pages/RestoreFromBackup/ExternalRegistryForm/ImageUrlField';
import getComponentRenderer, { screen } from '@/services/__mocks__/getComponentRenderer';

const mockOnChange = jest.fn();

const { renderComponent } = getComponentRenderer(getComponent);

describe('ImageUrlField', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should render the input field with label', () => {
    renderComponent();

    expect(screen.getByLabelText('Backup image URL')).toBeInTheDocument();
  });

  test('should render the placeholder text', () => {
    renderComponent();

    const input = screen.getByLabelText('Backup image URL');
    expect(input).toHaveAttribute('placeholder', 'registry.example.com/namespace/workspace:latest');
  });

  test('should display the provided value', () => {
    renderComponent({ value: 'registry.example.com/ns/ws:tag' });

    expect(screen.getByLabelText('Backup image URL')).toHaveValue('registry.example.com/ns/ws:tag');
  });

  test('should call onChange when user types', async () => {
    renderComponent();

    const input = screen.getByLabelText('Backup image URL');
    await userEvent.type(input, 'r');

    expect(mockOnChange).toHaveBeenCalledWith('r');
  });

  test('should display default helper text in idle state', () => {
    renderComponent({ validated: ValidatedOptions.default });

    expect(
      screen.getByText('Enter the full URL of the backup image from the source cluster.'),
    ).toBeInTheDocument();
  });

  test('should display success indicator when valid', () => {
    renderComponent({
      validated: ValidatedOptions.success,
    });

    expect(screen.getByText(/Backup image URL is valid/)).toBeInTheDocument();
  });

  test('should display error text when validated is error', () => {
    renderComponent({
      validated: ValidatedOptions.error,
      error: 'Invalid image URL format.',
    });

    expect(screen.getByText('Invalid image URL format.')).toBeInTheDocument();
  });
});

type PartialProps = {
  value?: string;
  validated?: ValidatedOptions;
  error?: string;
};

function getComponent(overrides: PartialProps = {}) {
  return (
    <ImageUrlField
      value={overrides.value ?? ''}
      validated={overrides.validated ?? ValidatedOptions.default}
      error={overrides.error ?? ''}
      onChange={mockOnChange}
    />
  );
}
