/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import userEvent from '@testing-library/user-event';
import React from 'react';

import { WorkspaceNameField } from '@/pages/RestoreFromBackup/WorkspaceNameField';
import getComponentRenderer, { screen } from '@/services/__mocks__/getComponentRenderer';

const mockOnChange = jest.fn();

const { renderComponent } = getComponentRenderer(getComponent);

describe('WorkspaceNameField', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should render label and input', () => {
    renderComponent();

    expect(screen.getByText('Workspace name')).toBeInTheDocument();
    expect(screen.getByLabelText('Workspace name')).toBeInTheDocument();
  });

  test('should show helperText in default state', () => {
    renderComponent();

    expect(screen.getByText('Enter a workspace name.')).toBeInTheDocument();
  });

  test('should call onChange on input change', async () => {
    renderComponent();

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'test');

    expect(mockOnChange).toHaveBeenCalled();
  });

  test('should render actionButton', () => {
    renderComponent({
      actionButton: <button data-testid="custom-action">Action</button>,
    });

    expect(screen.getByTestId('custom-action')).toBeInTheDocument();
  });

  test('should not show required error on initial render with empty value', () => {
    renderComponent();

    expect(screen.queryByText('Workspace name is required.')).not.toBeInTheDocument();
  });

  test('should show required error after typing and clearing the field', async () => {
    renderComponent();

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'a');
    await userEvent.clear(input);

    expect(screen.getByText('Workspace name is required.')).toBeInTheDocument();
  });

  test('should show error when workspace name conflicts with existing workspace', async () => {
    renderComponent({
      existingWorkspaceNames: new Set(['my-workspace']),
    });

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'my-workspace');

    expect(screen.getByText('A workspace with this name already exists.')).toBeInTheDocument();
  });

  test('should show warning when workspace name conflicts with existing backup', async () => {
    renderComponent({
      existingBackupNames: new Set(['old-ws']),
    });

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'old-ws');

    expect(
      screen.getByText(
        'A backup named "old-ws" already exists. The new workspace will be associated with that backup.',
      ),
    ).toBeInTheDocument();
  });

  test('should follow parent value changes when untouched', () => {
    const { reRenderComponent } = renderComponent({ value: '' });

    reRenderComponent({ value: 'auto-detected' });

    const input = screen.getByLabelText('Workspace name');
    expect(input).toHaveValue('auto-detected');
  });

  test('should ignore parent value changes after user has typed', async () => {
    const { reRenderComponent } = renderComponent({ value: '' });

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'my-custom-name');

    reRenderComponent({ value: 'auto-detected' });

    expect(input).toHaveValue('my-custom-name');
  });

  test('should call onChange with isValid=true for valid workspace name', async () => {
    renderComponent();

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'valid-name');

    const lastCall = mockOnChange.mock.calls[mockOnChange.mock.calls.length - 1];
    expect(lastCall[0]).toBe('valid-name');
    expect(lastCall[1]).toBe(true);
  });

  test('should show error when name matches active workspace even if backup exists', async () => {
    renderComponent({
      existingWorkspaceNames: new Set(['old-ws']),
      existingBackupNames: new Set(['old-ws']),
    });

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'old-ws');

    expect(screen.getByText('A workspace with this name already exists.')).toBeInTheDocument();
    expect(
      screen.queryByText(/already exists. The new workspace will be associated/),
    ).not.toBeInTheDocument();
  });

  test('should call onChange with isValid=false for conflicting workspace name', async () => {
    renderComponent({
      existingWorkspaceNames: new Set(['taken-name']),
    });

    const input = screen.getByLabelText('Workspace name');
    await userEvent.type(input, 'taken-name');

    const lastCall = mockOnChange.mock.calls[mockOnChange.mock.calls.length - 1];
    expect(lastCall[0]).toBe('taken-name');
    expect(lastCall[1]).toBe(false);
  });
});

function getComponent(
  options: {
    value?: string;
    existingWorkspaceNames?: Set<string>;
    existingBackupNames?: Set<string>;
    actionButton?: React.ReactNode;
  } = {},
) {
  return (
    <WorkspaceNameField
      fieldId="test-workspace-name"
      helperText="Enter a workspace name."
      value={options.value ?? ''}
      existingWorkspaceNames={options.existingWorkspaceNames ?? new Set()}
      existingBackupNames={options.existingBackupNames}
      onChange={mockOnChange}
      actionButton={options.actionButton ?? <button>Restore</button>}
    />
  );
}
