/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import * as k8s from '@kubernetes/client-node';

import { exec, ServerConfig } from '@/devworkspaceClient/services/helpers/exec';
import { STRATEGIC_MERGE_PATCH_OPTIONS } from '@/devworkspaceClient/services/helpers/patchOptions';
import { getKubeConfig } from '@/routes/api/helpers/getDevWorkspaceClient';
import { logger } from '@/utils/logger';

const AGENT_LABEL_COMPONENT = 'app.kubernetes.io/component';
const AGENT_LABEL_PART_OF = 'app.kubernetes.io/part-of';
const AGENT_LABEL_AGENT_ID = 'che.eclipse.org/agent-id';
const HEARTBEAT_ANNOTATION = 'che.eclipse.org/last-heartbeat';
const AGENT_TTL_MINUTES = 10;
const INJECTION_TIMEOUT_MS = 60_000;

export interface AgentPodStatus {
  agentId: string;
  name: string;
  phase: string;
  ready: boolean;
  serviceUrl: string | undefined;
}

interface AgentConfig {
  image: string;
  tag: string;
  memoryLimit: string;
  cpuLimit: string;
  terminalPort: number;
  env: Array<{ name: string; value: string }>;
}

function normalizeAgentId(agentId: string): string {
  return agentId.replace(/\//g, '-').replace(/[^a-z0-9-]/g, '');
}

function agentPodName(agentId: string): string {
  return `agent-${normalizeAgentId(agentId)}`;
}

function agentServiceName(agentId: string): string {
  return `agent-${normalizeAgentId(agentId)}-svc`;
}

function agentLabels(agentId: string): Record<string, string> {
  return {
    [AGENT_LABEL_COMPONENT]: 'ai-agent',
    [AGENT_LABEL_PART_OF]: 'che.eclipse.org',
    [AGENT_LABEL_AGENT_ID]: normalizeAgentId(agentId),
  };
}

const DW_MOUNT_LABEL = 'controller.devfile.io/mount-to-devworkspace';
const DW_MOUNT_AS = 'controller.devfile.io/mount-as';
const DW_MOUNT_PATH = 'controller.devfile.io/mount-path';

interface DevWorkspaceMounts {
  volumes: k8s.V1Volume[];
  volumeMounts: k8s.V1VolumeMount[];
  envFrom: k8s.V1EnvFromSource[];
}

function getCoreV1Api(token: string): k8s.CoreV1Api {
  const kubeConfig = getKubeConfig(token);
  return kubeConfig.makeApiClient(k8s.CoreV1Api);
}

async function discoverDevWorkspaceMounts(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
): Promise<DevWorkspaceMounts> {
  const volumes: k8s.V1Volume[] = [];
  const volumeMounts: k8s.V1VolumeMount[] = [];
  const envFrom: k8s.V1EnvFromSource[] = [];

  try {
    const secrets = await coreV1Api.listNamespacedSecret({
      namespace,
      labelSelector: `${DW_MOUNT_LABEL}=true`,
    });

    for (const secret of secrets.items) {
      const name = secret.metadata?.name;
      if (!name) continue;

      const mountAs = secret.metadata?.annotations?.[DW_MOUNT_AS];
      const mountPath = secret.metadata?.annotations?.[DW_MOUNT_PATH];

      if (mountAs === 'file' && mountPath) {
        const volumeName = `secret-${name}`;
        volumes.push({ name: volumeName, secret: { secretName: name } });
        volumeMounts.push({ name: volumeName, mountPath, readOnly: true });
      } else if (mountAs === 'env') {
        envFrom.push({ secretRef: { name } });
      }
    }
  } catch (e) {
    logger.warn(e, 'Failed to discover DevWorkspace-mountable secrets');
  }

  try {
    const configMaps = await coreV1Api.listNamespacedConfigMap({
      namespace,
      labelSelector: `${DW_MOUNT_LABEL}=true`,
    });

    for (const cm of configMaps.items) {
      const name = cm.metadata?.name;
      if (!name) continue;

      const mountAs = cm.metadata?.annotations?.[DW_MOUNT_AS];
      const mountPath = cm.metadata?.annotations?.[DW_MOUNT_PATH];

      if (mountAs === 'env') {
        envFrom.push({ configMapRef: { name } });
      } else if (mountAs === 'file' && mountPath) {
        const volumeName = `cm-${name}`;
        volumes.push({ name: volumeName, configMap: { name } });
        volumeMounts.push({ name: volumeName, mountPath, readOnly: true });
      }
    }
  } catch (e) {
    logger.warn(e, 'Failed to discover DevWorkspace-mountable configmaps');
  }

  return { volumes, volumeMounts, envFrom };
}

export async function createAgentPod(
  token: string,
  namespace: string,
  agentId: string,
  config: AgentConfig,
): Promise<AgentPodStatus> {
  const coreV1Api = getCoreV1Api(token);
  const podName = agentPodName(agentId);
  const svcName = agentServiceName(agentId);
  const labels = agentLabels(agentId);

  const existing = await findAgentPod(coreV1Api, namespace, agentId);
  if (existing) {
    const phase = existing.status?.phase || 'Unknown';
    if (phase === 'Failed' || phase === 'Succeeded') {
      await coreV1Api.deleteNamespacedPod({ name: existing.metadata!.name!, namespace });
    } else {
      return podToStatus(existing, agentId, namespace, config.terminalPort);
    }
  }

  const dwMounts = await discoverDevWorkspaceMounts(coreV1Api, namespace);
  const now = new Date().toISOString();

  const pod = await coreV1Api.createNamespacedPod({
    namespace,
    body: {
      metadata: {
        name: podName,
        namespace,
        labels,
        annotations: {
          'che.eclipse.org/ai-agent-id': agentId,
          [HEARTBEAT_ANNOTATION]: now,
        },
      },
      spec: {
        automountServiceAccountToken: true,
        volumes: dwMounts.volumes.length > 0 ? dwMounts.volumes : undefined,
        containers: [
          {
            name: 'agent',
            image: `${config.image}:${config.tag}`,
            ports: [
              {
                containerPort: config.terminalPort,
                name: 'terminal',
                protocol: 'TCP',
              },
            ],
            resources: {
              limits: {
                memory: config.memoryLimit,
                cpu: config.cpuLimit,
              },
              requests: {
                memory: '128Mi',
                cpu: '100m',
              },
            },
            env: [...config.env, { name: 'AGENT_NAMESPACE', value: namespace }],
            envFrom: dwMounts.envFrom.length > 0 ? dwMounts.envFrom : undefined,
            volumeMounts: dwMounts.volumeMounts.length > 0 ? dwMounts.volumeMounts : undefined,
            securityContext: {
              allowPrivilegeEscalation: false,
              runAsUser: 1000,
              runAsNonRoot: true,
            },
          },
        ],
        restartPolicy: 'Never',
        terminationGracePeriodSeconds: 5,
      },
    },
  });

  const podUid = pod.metadata!.uid!;

  await coreV1Api.createNamespacedService({
    namespace,
    body: {
      metadata: {
        name: svcName,
        namespace,
        labels,
        ownerReferences: [
          {
            apiVersion: 'v1',
            kind: 'Pod',
            name: podName,
            uid: podUid,
          },
        ],
      },
      spec: {
        type: 'ClusterIP',
        selector: { [AGENT_LABEL_AGENT_ID]: normalizeAgentId(agentId) },
        ports: [
          {
            name: 'terminal',
            port: config.terminalPort,
            targetPort: config.terminalPort,
            protocol: 'TCP',
          },
        ],
      },
    },
  });

  return podToStatus(pod, agentId, namespace, config.terminalPort);
}

export async function getAgentPodStatus(
  token: string,
  namespace: string,
  agentId: string,
  terminalPort = 8080,
): Promise<AgentPodStatus | undefined> {
  const coreV1Api = getCoreV1Api(token);
  const pod = await findAgentPod(coreV1Api, namespace, agentId);
  if (!pod) return undefined;
  return podToStatus(pod, agentId, namespace, terminalPort);
}

export async function deleteAgentPod(
  token: string,
  namespace: string,
  agentId: string,
): Promise<void> {
  const coreV1Api = getCoreV1Api(token);
  const pod = await findAgentPod(coreV1Api, namespace, agentId);
  if (pod?.metadata?.name) {
    await coreV1Api.deleteNamespacedPod({
      name: pod.metadata.name,
      namespace,
      body: { gracePeriodSeconds: 5 },
    });
  }
}

export async function heartbeatAgentPod(
  token: string,
  namespace: string,
  agentId: string,
): Promise<void> {
  const coreV1Api = getCoreV1Api(token);
  const pod = await findAgentPod(coreV1Api, namespace, agentId);
  if (!pod?.metadata?.name) return;

  const now = new Date().toISOString();
  await coreV1Api.patchNamespacedPod(
    {
      name: pod.metadata.name,
      namespace,
      body: { metadata: { annotations: { [HEARTBEAT_ANNOTATION]: now } } },
    },
    STRATEGIC_MERGE_PATCH_OPTIONS,
  );
}

export async function cleanupExpiredAgentPods(token: string, namespace: string): Promise<string[]> {
  const coreV1Api = getCoreV1Api(token);
  const pods = await coreV1Api.listNamespacedPod({
    namespace,
    labelSelector: `${AGENT_LABEL_COMPONENT}=ai-agent`,
  });

  const now = Date.now();
  const ttlMs = AGENT_TTL_MINUTES * 60 * 1000;
  const deleted: string[] = [];

  for (const pod of pods.items) {
    const heartbeat = pod.metadata?.annotations?.[HEARTBEAT_ANNOTATION];
    if (!heartbeat) continue;

    const lastBeat = new Date(heartbeat).getTime();
    if (now - lastBeat > ttlMs) {
      const name = pod.metadata!.name!;
      logger.info('Cleaning up expired agent pod: %s (last heartbeat: %s)', name, heartbeat);
      try {
        await coreV1Api.deleteNamespacedPod({
          name,
          namespace,
          body: { gracePeriodSeconds: 5 },
        });
        deleted.push(name);
      } catch (e) {
        logger.error(e, 'Failed to delete expired agent pod: %s', name);
      }
    }
  }
  return deleted;
}

export function getAgentServiceUrl(
  namespace: string,
  agentId: string,
  terminalPort = 8080,
): string {
  const svcName = agentServiceName(agentId);
  return `http://${svcName}.${namespace}.svc:${terminalPort}`;
}

async function findAgentPod(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
  agentId: string,
): Promise<k8s.V1Pod | undefined> {
  const normalized = normalizeAgentId(agentId);
  const pods = await coreV1Api.listNamespacedPod({
    namespace,
    labelSelector: `${AGENT_LABEL_AGENT_ID}=${normalized}`,
  });
  return pods.items.find(pod => !pod.metadata?.deletionTimestamp);
}

function podToStatus(
  pod: k8s.V1Pod,
  agentId: string,
  namespace: string,
  terminalPort: number,
): AgentPodStatus {
  const phase = pod.status?.phase || 'Unknown';
  const containerReady = pod.status?.containerStatuses?.some(c => c.ready === true) || false;
  const isRunning = phase === 'Running' && containerReady;

  return {
    agentId,
    name: pod.metadata?.name || '',
    phase,
    ready: isRunning,
    serviceUrl: isRunning ? getAgentServiceUrl(namespace, agentId, terminalPort) : undefined,
  };
}

const activeAgentWatches = new Map<string, AbortController>();

export function watchAndInjectKubeConfig(token: string, namespace: string, agentId: string): void {
  const key = `${namespace}/${agentId}`;
  if (activeAgentWatches.has(key)) {
    return;
  }

  const kc = getKubeConfig(token);
  const watch = new k8s.Watch(kc);
  const podName = agentPodName(agentId);

  const cleanup = (ac?: AbortController) => {
    activeAgentWatches.delete(key);
    ac?.abort();
  };

  const timeoutHandle = setTimeout(() => {
    logger.warn('AgentPostStart: timed out waiting for %s to reach Running', key);
    const ac = activeAgentWatches.get(key);
    cleanup(ac);
  }, INJECTION_TIMEOUT_MS);

  const cleanupWithTimeout = (ac?: AbortController) => {
    clearTimeout(timeoutHandle);
    cleanup(ac);
  };

  const server = kc.getCurrentCluster()?.server || '';
  const opts: Record<string, unknown> = {};
  kc.applyToHTTPSOptions(opts);
  const serverConfig: ServerConfig = { opts, server };
  const kubeConfigYaml = kc.exportConfig();

  watch
    .watch(
      `/api/v1/watch/namespaces/${namespace}/pods/${podName}`,
      {},
      async (eventPhase: string, apiObj: k8s.V1Pod | k8s.V1Status) => {
        if (eventPhase === 'ERROR') {
          logger.warn('AgentPostStart: watch ERROR for %s', key);
          cleanupWithTimeout(activeAgentWatches.get(key));
          return;
        }

        const pod = apiObj as k8s.V1Pod;
        const phase = pod.status?.phase;
        const containerReady = pod.status?.containerStatuses?.some(c => c.ready === true) || false;

        if (phase === 'Failed') {
          logger.info('AgentPostStart: %s entered Failed phase, aborting', key);
          cleanupWithTimeout(activeAgentWatches.get(key));
          return;
        }

        if (phase === 'Running' && containerReady) {
          logger.info('AgentPostStart: %s is Running, injecting kubeconfig', key);
          try {
            await injectKubeConfigToAgent(podName, namespace, kubeConfigYaml, serverConfig);
            logger.info('AgentPostStart: kubeconfig injected into %s', key);
          } catch (e) {
            logger.error(e, 'AgentPostStart: failed to inject kubeconfig for %s', key);
          }
          cleanupWithTimeout(activeAgentWatches.get(key));
        }
      },
      (error: unknown) => {
        logger.warn(error, 'AgentPostStart: watch connection lost for %s', key);
        cleanupWithTimeout();
      },
    )
    .then((abortController: AbortController) => {
      if (!activeAgentWatches.has(key)) {
        abortController.abort();
      } else {
        activeAgentWatches.set(key, abortController);
      }
    })
    .catch((error: unknown) => {
      logger.error(error, 'AgentPostStart: failed to start watch for %s', key);
      cleanupWithTimeout();
    });

  activeAgentWatches.set(key, new AbortController());
}

async function injectKubeConfigToAgent(
  podName: string,
  namespace: string,
  kubeConfigYaml: string,
  serverConfig: ServerConfig,
): Promise<void> {
  const containerName = 'agent';

  const homeResult = await exec(
    podName,
    namespace,
    containerName,
    ['sh', '-c', 'printenv HOME'],
    serverConfig,
  );
  const homeDir = homeResult.stdOut.trim() || '/home/user';
  const kubeDir = homeDir.endsWith('/') ? `${homeDir}.kube` : `${homeDir}/.kube`;

  await exec(podName, namespace, containerName, ['sh', '-c', `mkdir -p ${kubeDir}`], serverConfig);

  const escapedConfig = kubeConfigYaml.replace(/'/g, "'\\''");
  await exec(
    podName,
    namespace,
    containerName,
    ['sh', '-c', `echo '${escapedConfig}' > ${kubeDir}/config`],
    serverConfig,
  );
}
