/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { QuayRegistryClient } from '@/devworkspaceClient/services/helpers/externalRegistry/QuayRegistryClient';

// Mock the https module used internally
jest.mock('https');

import * as https from 'https';

const mockHttpsGet = https.get as jest.Mock;

interface MockRes {
  statusCode: number;
  on: jest.Mock;
}

function buildMockRes(statusCode: number, body: string): MockRes {
  const res: MockRes = {
    statusCode,
    on: jest.fn((event: string, handler: (...args: unknown[]) => void) => {
      if (event === 'data') handler(body);
      if (event === 'end') handler();
      return res;
    }),
  };
  return res;
}

/**
 * Helper to simulate a successful https.get response with JSON body.
 */
function mockHttpResponse(statusCode: number, body: object): void {
  mockHttpsGet.mockImplementation(
    (_url: unknown, _opts: unknown, callback: (res: MockRes) => void) => {
      callback(buildMockRes(statusCode, JSON.stringify(body)));
      return { on: jest.fn() };
    },
  );
}

describe('QuayRegistryClient', () => {
  const registryPath = 'quay.io/my-org/backups';
  const namespace = 'user-che';
  const token = 'robot-token-value';

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should return workspace names for repos matching the namespace prefix', async () => {
    mockHttpResponse(200, {
      repositories: [
        { name: 'backups/user-che/my-workspace', last_modified: 1700000000 },
        { name: 'backups/user-che/another-ws', last_modified: 1700001000 },
        { name: 'backups/other-ns/unrelated', last_modified: 1700002000 },
      ],
      next_page: undefined,
    });

    const client = new QuayRegistryClient(registryPath, token);
    const result = await client.listWorkspaceBackups(namespace);

    expect(result).toEqual(expect.arrayContaining(['my-workspace', 'another-ws']));
    expect(result).not.toContain('unrelated');
    expect(result).toHaveLength(2);
  });

  it('should follow next_page cursor for paginated results', async () => {
    // First page
    mockHttpsGet.mockImplementationOnce(
      (_url: unknown, _opts: unknown, callback: (res: MockRes) => void) => {
        callback(
          buildMockRes(
            200,
            JSON.stringify({
              repositories: [{ name: 'backups/user-che/ws-1', last_modified: 1700000000 }],
              next_page: 'cursor-abc',
            }),
          ),
        );
        return { on: jest.fn() };
      },
    );
    // Second page
    mockHttpsGet.mockImplementationOnce(
      (_url: unknown, _opts: unknown, callback: (res: MockRes) => void) => {
        callback(
          buildMockRes(
            200,
            JSON.stringify({
              repositories: [{ name: 'backups/user-che/ws-2', last_modified: 1700001000 }],
              next_page: undefined,
            }),
          ),
        );
        return { on: jest.fn() };
      },
    );

    const client = new QuayRegistryClient(registryPath, token);
    const result = await client.listWorkspaceBackups(namespace);

    expect(result).toEqual(expect.arrayContaining(['ws-1', 'ws-2']));
    expect(mockHttpsGet).toHaveBeenCalledTimes(2);
  });

  it('should return empty array when no repos match the prefix', async () => {
    mockHttpResponse(200, {
      repositories: [{ name: 'other/path/ws', last_modified: 1700000000 }],
    });

    const client = new QuayRegistryClient(registryPath, token);
    const result = await client.listWorkspaceBackups(namespace);

    expect(result).toEqual([]);
  });

  it('should throw on non-200 response', async () => {
    mockHttpResponse(401, { message: 'Unauthorized' });

    const client = new QuayRegistryClient(registryPath, token);
    await expect(client.listWorkspaceBackups(namespace)).rejects.toThrow();
  });

  it('should include Authorization header with Bearer token', async () => {
    mockHttpResponse(200, { repositories: [] });

    const client = new QuayRegistryClient(registryPath, token);
    await client.listWorkspaceBackups(namespace);

    expect(mockHttpsGet).toHaveBeenCalledWith(
      expect.any(String),
      expect.objectContaining({
        headers: expect.objectContaining({
          Authorization: `Bearer ${token}`,
        }),
      }),
      expect.any(Function),
    );
  });
});
