/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { helpers } from '@eclipse-che/common';

import { injectKubeConfig, podmanLogin } from '@/services/backend-client/devWorkspaceApi';
import { constructWorkspace, Workspace } from '@/services/workspace-adapter';
import { DevWorkspaceBuilder } from '@/store/__mocks__/devWorkspaceBuilder';
import { refreshKubeconfig } from '@/store/Kubeconfig/actions';

jest.mock('@eclipse-che/common');
jest.mock('@/services/backend-client/devWorkspaceApi');

describe('Kubeconfig, actions', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  function buildWorkspace(phase: string, devworkspaceId?: string): Workspace {
    const builder = new DevWorkspaceBuilder().withNamespace('user-namespace').withStatus({ phase });
    if (devworkspaceId !== undefined) {
      builder.withId(devworkspaceId);
    }
    const dw = builder.build();
    if (devworkspaceId === undefined && dw.status) {
      dw.status = { phase: dw.status.phase } as unknown as typeof dw.status;
    }
    return constructWorkspace(dw);
  }

  describe('refreshKubeconfig', () => {
    it('should inject the kubeconfig and log in to podman when the workspace is running', async () => {
      const workspace = buildWorkspace('RUNNING', 'workspace1234');

      (injectKubeConfig as jest.Mock).mockResolvedValue(undefined);
      (podmanLogin as jest.Mock).mockResolvedValue(undefined);

      const result = await refreshKubeconfig(workspace);

      expect(injectKubeConfig).toHaveBeenCalledWith('user-namespace', 'workspace1234');
      expect(podmanLogin).toHaveBeenCalledWith('user-namespace', 'workspace1234');
      expect(result).toEqual({});
    });

    it('should throw without calling the backend when the workspace is not running', async () => {
      const workspace = buildWorkspace('STOPPED');

      await expect(refreshKubeconfig(workspace)).rejects.toThrow(
        'Workspace must be running to refresh the kubeconfig.',
      );

      expect(injectKubeConfig).not.toHaveBeenCalled();
      expect(podmanLogin).not.toHaveBeenCalled();
    });

    it('should reject and skip podman login when injectKubeConfig fails', async () => {
      const workspace = buildWorkspace('RUNNING', 'workspace1234');
      const errorMessage = 'Failed to inject kubeconfig.';

      (injectKubeConfig as jest.Mock).mockRejectedValue(new Error(errorMessage));

      await expect(refreshKubeconfig(workspace)).rejects.toThrow(errorMessage);

      expect(podmanLogin).not.toHaveBeenCalled();
    });

    it('should throw when the workspace is running but devworkspaceId is not yet populated', async () => {
      const workspace = buildWorkspace('RUNNING');

      await expect(refreshKubeconfig(workspace)).rejects.toThrow(
        'Workspace ID is not available yet. Try again in a moment.',
      );

      expect(injectKubeConfig).not.toHaveBeenCalled();
      expect(podmanLogin).not.toHaveBeenCalled();
    });

    it('should resolve with a podmanLoginWarning instead of rejecting when podman login fails', async () => {
      const workspace = buildWorkspace('RUNNING', 'workspace1234');
      const errorMessage = 'Failed to log in to the podman registry.';

      (injectKubeConfig as jest.Mock).mockResolvedValue(undefined);
      (podmanLogin as jest.Mock).mockRejectedValue(new Error(errorMessage));
      (helpers.errors.getMessage as jest.Mock).mockReturnValue(errorMessage);

      const result = await refreshKubeconfig(workspace);

      expect(result).toEqual({ podmanLoginWarning: errorMessage });
    });
  });
});
