/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { helpers } from '@eclipse-che/common';

import { injectKubeConfig, podmanLogin } from '@/services/backend-client/devWorkspaceApi';
import { createMockStore } from '@/store/__mocks__/mockActionsTestStore';
import {
  actionCreators,
  kubeconfigRefreshErrorAction,
  kubeconfigRefreshRequestAction,
  kubeconfigRefreshSuccessAction,
} from '@/store/Kubeconfig/actions';

jest.mock('@eclipse-che/common');
jest.mock('@/services/backend-client/devWorkspaceApi');

describe('Kubeconfig, actions', () => {
  let store: ReturnType<typeof createMockStore>;

  beforeEach(() => {
    store = createMockStore({
      kubeconfig: { isLoading: false, error: undefined },
    });
    jest.clearAllMocks();
  });

  describe('refreshKubeconfig', () => {
    it('should dispatch request and success actions', async () => {
      (injectKubeConfig as jest.Mock).mockResolvedValue(undefined);
      (podmanLogin as jest.Mock).mockResolvedValue(undefined);

      await store.dispatch(actionCreators.refreshKubeconfig('user-namespace', 'workspace1234'));

      expect(injectKubeConfig).toHaveBeenCalledWith('user-namespace', 'workspace1234');
      expect(podmanLogin).toHaveBeenCalledWith('user-namespace', 'workspace1234');

      const actions = store.getActions();
      expect(actions[0]).toEqual(kubeconfigRefreshRequestAction());
      expect(actions[1]).toEqual(kubeconfigRefreshSuccessAction());
    });

    it('should dispatch request and error actions on failure', async () => {
      const errorMessage = 'Failed to inject kubeconfig.';

      (injectKubeConfig as jest.Mock).mockRejectedValue(new Error(errorMessage));
      (helpers.errors.getMessage as jest.Mock).mockReturnValue(errorMessage);

      await expect(
        store.dispatch(actionCreators.refreshKubeconfig('user-namespace', 'workspace1234')),
      ).rejects.toThrow(errorMessage);

      expect(podmanLogin).not.toHaveBeenCalled();

      const actions = store.getActions();
      expect(actions[0]).toEqual(kubeconfigRefreshRequestAction());
      expect(actions[1]).toEqual(kubeconfigRefreshErrorAction(errorMessage));
    });
  });
});
