/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by AI Assistant

import { api } from '@eclipse-che/common';
import { FastifyInstance } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { getDevWorkspaceClient } from '@/routes/api/helpers/getDevWorkspaceClient';
import { getServiceAccountToken } from '@/routes/api/helpers/getServiceAccountToken';
import { getSchema } from '@/services/helpers';
import { logger } from '@/utils/logger';

const tags = ['AI Registry'];

const EMPTY_REGISTRY: api.IAiRegistry = {
  providers: [],
  tools: [],
  defaultAiProviders: [],
};

export function registerAiRegistryRoute(isLocalRun: boolean, instance: FastifyInstance) {
  instance.register(async server => {
    server.get(`${baseApiPath}/ai-registry`, getSchema({ tags }), async () => {
      if (isLocalRun) {
        return EMPTY_REGISTRY;
      }
      const token = getServiceAccountToken();
      const { aiRegistryApi, serverConfigApi } = getDevWorkspaceClient(token);
      const currentArch = await serverConfigApi.getCurrentArchitecture().catch(error => {
        logger.warn(
          error,
          'Failed to detect current architecture; serving all tools without arch filtering',
        );
        return undefined;
      });
      return aiRegistryApi.get(currentArch);
    });
  });
}
