/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

import { helpers } from '@eclipse-che/common';
import { AxiosResponse } from 'axios';
import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { dataResolverSchema } from '@/constants/schemas';
import { restParams } from '@/models';
import {
  axiosInstance,
  axiosInstanceNoCert,
  axiosInstanceNoProxy,
  axiosInstanceNoProxyNoCert,
} from '@/routes/api/helpers/getCertificateAuthority';
import { getSchema } from '@/services/helpers';

const tags = ['Data Resolver'];

const config = {
  headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET' },
};

// Retry without proxy when ENETUNREACH (e.g. IPv6 pod, unreachable IPv4 proxy). Generated by Cursor AI.
function isProxyUnreachableError(error: unknown): boolean {
  const code = (error as NodeJS.ErrnoException)?.code;
  const message = String((error as Error)?.message || '');
  return code === 'ENETUNREACH' || message.includes('ENETUNREACH');
}

async function fetchWithRetry(url: string): Promise<AxiosResponse> {
  try {
    try {
      return await axiosInstanceNoCert.get(url, config);
    } catch (error) {
      if (
        helpers.errors.includesAxiosResponse(error) &&
        (error as { response?: { status?: number } }).response?.status === 404
      ) {
        throw error;
      }
      return await axiosInstance.get(url, config);
    }
  } catch (error) {
    // When proxy is unreachable (e.g. IPv6 pod, IPv4 proxy), retry without proxy
    if (isProxyUnreachableError(error)) {
      try {
        return await axiosInstanceNoProxyNoCert.get(url, config);
      } catch {
        try {
          return await axiosInstanceNoProxy.get(url, config);
        } catch {
          throw error;
        }
      }
    }
    throw error;
  }
}

export function registerDataResolverRoute(instance: FastifyInstance) {
  instance.register(async server => {
    server.post(
      `${baseApiPath}/data/resolver`,
      getSchema({ tags, body: dataResolverSchema }),
      async function (request: FastifyRequest, reply: FastifyReply): Promise<string | void> {
        const { url } = request.body as restParams.IYamlResolverParams;

        try {
          const response = await fetchWithRetry(url);
          return response.data;
        } catch (error) {
          if (!helpers.errors.includesAxiosResponse(error)) {
            throw error;
          }
          const err = error as { response?: { status?: number; data?: unknown } };
          reply.code(err.response?.status ?? 500).send(err.response?.data);
        }
      },
    );
  });
}
