/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

import { helpers } from '@eclipse-che/common';
import { AxiosResponse } from 'axios';
import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { dataResolverSchema } from '@/constants/schemas';
import { restParams } from '@/models';
import {
  axiosInstance,
  axiosInstanceNoCert,
  axiosInstanceNoProxy,
  axiosInstanceNoProxyNoCert,
} from '@/routes/api/helpers/getCertificateAuthority';
import { getSchema } from '@/services/helpers';

const tags = ['Data Resolver'];

const config = {
  headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET' },
};

/**
 * Allowlisted domain suffixes for the data resolver endpoint.
 * Hosts must end with one of these suffixes or match in-cluster patterns.
 * Extend this list as needed for additional trusted devfile sources.
 */
const ALLOWED_DOMAIN_SUFFIXES = [
  '.devfile.io', // Devfile registry
  '.github.io', // GitHub Pages
  '.githubusercontent.com', // raw.githubusercontent.com, etc.
  '.github.com', // GitHub
];

/**
 * SSRF Protection: Validate and normalize URLs before making outbound requests.
 * User input must not control the request target arbitrarily. The host must match
 * an explicit allowlist of safe domains or in-cluster service patterns.
 *
 * @param rawUrl - User-provided URL to validate
 * @returns Normalized URL string safe to use in fetchWithRetry
 * @throws Error if URL is invalid or host is not allowlisted
 */
function validateAndNormalizeUrl(rawUrl: string): string {
  let parsed: URL;
  try {
    parsed = new URL(rawUrl);
  } catch {
    throw new Error('Invalid URL format');
  }

  // Only allow HTTP and HTTPS protocols
  const protocol = parsed.protocol.toLowerCase();
  if (protocol !== 'http:' && protocol !== 'https:') {
    throw new Error('Unsupported URL protocol. Only http and https are allowed');
  }

  // Reject URLs with username/password components
  if (parsed.username || parsed.password) {
    throw new Error('URL must not contain username or password');
  }

  const hostname = parsed.hostname.toLowerCase();

  // Allow internal Kubernetes cluster services
  if (
    hostname.endsWith('.cluster.local') ||
    hostname.endsWith('.svc.cluster') ||
    hostname.endsWith('.svc')
  ) {
    return parsed.toString();
  }

  // Allow IPv6 unique-local addresses (fd00::/8) for in-cluster services in IPv6-only clusters
  if (/^\[?fd[0-9a-f]{2}:/i.test(hostname)) {
    return parsed.toString();
  }

  // Block localhost, loopback, private and link-local addresses
  if (
    hostname === 'localhost' ||
    hostname === '127.0.0.1' ||
    hostname === '::1' ||
    hostname === '[::1]'
  ) {
    throw new Error('Access to localhost is not allowed');
  }
  if (
    /^10\./.test(hostname) ||
    /^192\.168\./.test(hostname) ||
    /^172\.(1[6-9]|2[0-9]|3[0-1])\./.test(hostname)
  ) {
    throw new Error('Access to private network addresses is not allowed');
  }
  if (/^169\.254\./.test(hostname) || /^\[?fe80:/i.test(hostname)) {
    throw new Error('Access to link-local addresses is not allowed');
  }

  // Block raw IP literals (IPv4 and IPv6) for external requests
  // Only allowlisted domain names are permitted; fd00::/8 is allowed above for in-cluster
  const isIpv4 = /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(hostname);
  const isIpv6 = hostname.includes(':');
  if (isIpv4 || isIpv6) {
    throw new Error('Access to IP addresses is not allowed. Use a domain name from the allowlist.');
  }

  // Host must match allowlisted domain suffixes
  const isAllowed = ALLOWED_DOMAIN_SUFFIXES.some(
    suffix => hostname === suffix.slice(1) || hostname.endsWith(suffix),
  );
  if (!isAllowed) {
    throw new Error(
      `URL host "${hostname}" is not in the allowlist. Allowed: ${ALLOWED_DOMAIN_SUFFIXES.join(', ')}`,
    );
  }

  return parsed.toString();
}

// Retry without proxy when ENETUNREACH (e.g. IPv6 pod, unreachable IPv4 proxy). Generated by Cursor AI.
function isProxyUnreachableError(error: unknown): boolean {
  const code = (error as NodeJS.ErrnoException)?.code;
  const message = String((error as Error)?.message || '');
  return code === 'ENETUNREACH' || message.includes('ENETUNREACH');
}

/**
 * Fetch with retry logic using different axios instances.
 * @param safeUrl - Sanitized URL (must have passed validateAndNormalizeUrl)
 */
async function fetchWithRetry(safeUrl: string): Promise<AxiosResponse> {
  try {
    try {
      // lgtm[js/request-forgery] - URL has been validated by validateAndNormalizeUrl()
      return await axiosInstanceNoCert.get(safeUrl, config);
    } catch (error) {
      if (
        helpers.errors.includesAxiosResponse(error) &&
        (error as { response?: { status?: number } }).response?.status === 404
      ) {
        throw error;
      }
      // lgtm[js/request-forgery] - URL has been validated by validateAndNormalizeUrl()
      return await axiosInstance.get(safeUrl, config);
    }
  } catch (error) {
    // When proxy is unreachable (e.g. IPv6 pod, IPv4 proxy), retry without proxy
    if (isProxyUnreachableError(error)) {
      try {
        // lgtm[js/request-forgery] - URL has been validated by validateAndNormalizeUrl()
        return await axiosInstanceNoProxyNoCert.get(safeUrl, config);
      } catch {
        try {
          // lgtm[js/request-forgery] - URL has been validated by validateAndNormalizeUrl()
          return await axiosInstanceNoProxy.get(safeUrl, config);
        } catch {
          throw error;
        }
      }
    }
    throw error;
  }
}

export function registerDataResolverRoute(instance: FastifyInstance) {
  instance.register(async server => {
    server.post(
      `${baseApiPath}/data/resolver`,
      getSchema({ tags, body: dataResolverSchema }),
      async function (request: FastifyRequest, reply: FastifyReply): Promise<string | void> {
        const { url } = request.body as restParams.IYamlResolverParams;

        // Validate and normalize URL to prevent SSRF; pass only sanitized URL to fetchWithRetry
        let safeUrl: string;
        try {
          safeUrl = validateAndNormalizeUrl(url);
        } catch (validationError) {
          const message =
            validationError instanceof Error ? validationError.message : 'Invalid URL';
          reply.code(400).send({ message });
          return;
        }

        try {
          const response = await fetchWithRetry(safeUrl);
          return response.data;
        } catch (error) {
          if (!helpers.errors.includesAxiosResponse(error)) {
            throw error;
          }
          const err = error as { response?: { status?: number; data?: unknown } };
          reply.code(err.response?.status ?? 500).send(err.response?.data);
        }
      },
    );
  });
}
