/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { FastifyInstance } from 'fastify';
import { JSONSchema7 } from 'json-schema';

import { baseApiPath } from '@/constants/config';
import * as devworkspaceSchema from '@/devworkspaceSchemas/devworkspace.json';
import { getSchema } from '@/services/helpers';

const tags = ['DevWorkspace'];

export function registerDevWorkspaceSchemaRoute(server: FastifyInstance) {
  server.get(
    `${baseApiPath}/devworkspace-schema`,
    getSchema({ tags }),
    async function (): Promise<JSONSchema7> {
      return devworkspaceSchema as unknown as JSONSchema7;
    },
  );
}
