/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { randomBytes } from 'node:crypto';

import { helpers } from '@eclipse-che/common';
import * as k8s from '@kubernetes/client-node';
import { load } from 'js-yaml';

import { getKubeConfig } from '@/routes/api/helpers/getDevWorkspaceClient';

export const CONFIGMAP_NAME = 'devfile-creator-storage';
const CONFIGMAP_LABELS = {
  'app.kubernetes.io/component': 'devfile-creator',
  'app.kubernetes.io/part-of': 'che.eclipse.org',
};

interface ParsedDevfile {
  metadata?: { name?: string; generateName?: string; description?: string };
  projects?: Array<{ name?: string }>;
}

export interface DevfileEntry {
  id: string;
  name: string;
  description: string;
  content: string;
  projectCount: number;
  lastModified: string;
}

export interface DevfileIdParams {
  namespace: string;
  id: string;
}

function parseDevfileYaml(content: string): ParsedDevfile {
  try {
    const parsed = load(content);
    if (typeof parsed === 'object' && parsed !== null) {
      return parsed as ParsedDevfile;
    }
  } catch {
    // invalid YAML
  }
  return {};
}

export function extractDevfileName(content: string): string {
  const parsed = parseDevfileYaml(content);
  const name = parsed.metadata?.name;
  if (typeof name === 'string' && name.length > 0) {
    return name;
  }
  const generateName = parsed.metadata?.generateName;
  if (typeof generateName === 'string' && generateName.length > 0) {
    return generateName;
  }
  return 'untitled';
}

export function extractDevfileDescription(content: string): string {
  const parsed = parseDevfileYaml(content);
  const description = parsed.metadata?.description;
  return typeof description === 'string' ? description : '';
}

export function generateDevfileId(content: string): string {
  const name = extractDevfileName(content);
  const sanitized = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 20);
  const suffix = randomBytes(4).toString('hex');
  return `${sanitized || 'devfile'}-${suffix}`;
}

export function countProjects(content: string): number {
  const parsed = parseDevfileYaml(content);
  if (!Array.isArray(parsed.projects)) return 0;
  return parsed.projects.filter(p => typeof p?.name === 'string').length;
}

export const MODIFIED_ANNOTATION_PREFIX = 'che.eclipse.org/modified-';

export function parseEntries(
  data: Record<string, string> | undefined,
  annotations?: Record<string, string>,
): DevfileEntry[] {
  if (!data) return [];
  return Object.entries(data).map(([id, content]) => {
    const parsed = parseDevfileYaml(content);
    const name = parsed.metadata?.name;
    const generateName = parsed.metadata?.generateName;
    const description = parsed.metadata?.description;
    const projects = Array.isArray(parsed.projects) ? parsed.projects : [];
    const storedTimestamp = annotations?.[`${MODIFIED_ANNOTATION_PREFIX}${id}`];
    const displayName =
      typeof name === 'string' && name.length > 0
        ? name
        : typeof generateName === 'string' && generateName.length > 0
          ? generateName
          : 'untitled';
    return {
      id,
      name: displayName,
      description: typeof description === 'string' ? description : '',
      content,
      projectCount: projects.filter(p => typeof p?.name === 'string').length,
      lastModified: storedTimestamp || new Date().toISOString(),
    };
  });
}

export async function getOrCreateConfigMap(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
): Promise<k8s.V1ConfigMap> {
  try {
    const response = await coreV1Api.readNamespacedConfigMap({
      name: CONFIGMAP_NAME,
      namespace,
    });
    return response;
  } catch (error: unknown) {
    if (helpers.errors.isKubeClientError(error) && error.code === 404) {
      const configMap: k8s.V1ConfigMap = {
        apiVersion: 'v1',
        kind: 'ConfigMap',
        metadata: {
          name: CONFIGMAP_NAME,
          namespace,
          labels: CONFIGMAP_LABELS,
        },
        data: {},
      };
      return coreV1Api.createNamespacedConfigMap({
        namespace,
        body: configMap,
      });
    }
    throw error;
  }
}

export function getCoreV1Api(token: string): k8s.CoreV1Api {
  const kubeConfig = getKubeConfig(token);
  return kubeConfig.makeApiClient(k8s.CoreV1Api);
}
