/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { helpers } from '@eclipse-che/common';
import * as k8s from '@kubernetes/client-node';

import { getKubeConfig } from '@/routes/api/helpers/getDevWorkspaceClient';

export const CONFIGMAP_NAME = 'devfile-creator-storage';
const CONFIGMAP_LABELS = {
  'app.kubernetes.io/component': 'devfile-creator',
  'app.kubernetes.io/part-of': 'che.eclipse.org',
};

export interface DevfileEntry {
  id: string;
  name: string;
  description: string;
  content: string;
  projectCount: number;
  lastModified: string;
}

export interface DevfileIdParams {
  namespace: string;
  id: string;
}

export function extractDevfileName(content: string): string {
  const match = content.match(/^\s*name:\s*(.+)$/m);
  return match ? match[1].trim() : 'untitled';
}

export function extractDevfileDescription(content: string): string {
  const match = content.match(/^\s*description:\s*(.+)$/m);
  return match ? match[1].trim() : '';
}

export function countProjects(content: string): number {
  const projectsSectionMatch = content.match(/^projects:\s*\n((?:\s+.+\n)*)/m);
  if (!projectsSectionMatch) return 0;
  const projectNames = projectsSectionMatch[1].match(/^\s+- name:/gm);
  return projectNames ? projectNames.length : 0;
}

export function parseEntries(data: Record<string, string> | undefined): DevfileEntry[] {
  if (!data) return [];
  return Object.entries(data).map(([id, content]) => ({
    id,
    name: extractDevfileName(content),
    description: extractDevfileDescription(content),
    content,
    projectCount: countProjects(content),
    lastModified: new Date().toISOString(),
  }));
}

export async function getOrCreateConfigMap(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
): Promise<k8s.V1ConfigMap> {
  try {
    const response = await coreV1Api.readNamespacedConfigMap({
      name: CONFIGMAP_NAME,
      namespace,
    });
    return response;
  } catch (error: unknown) {
    if (helpers.errors.isKubeClientError(error) && error.code === 404) {
      const configMap: k8s.V1ConfigMap = {
        apiVersion: 'v1',
        kind: 'ConfigMap',
        metadata: {
          name: CONFIGMAP_NAME,
          namespace,
          labels: CONFIGMAP_LABELS,
        },
        data: {},
      };
      return coreV1Api.createNamespacedConfigMap({
        namespace,
        body: configMap,
      });
    }
    throw error;
  }
}

export function getCoreV1Api(token: string): k8s.CoreV1Api {
  const kubeConfig = getKubeConfig(token);
  return kubeConfig.makeApiClient(k8s.CoreV1Api);
}
