/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by AI Assistant

import userEvent from '@testing-library/user-event';
import React from 'react';

import { RestoreMode } from '@/pages/RestoreFromBackup/helpers';
import { RestoreModeAccordion } from '@/pages/RestoreFromBackup/RestoreModeAccordion';
import getComponentRenderer, { screen } from '@/services/__mocks__/getComponentRenderer';

jest.mock('@/pages/RestoreFromBackup/DefaultRegistryForm', () => ({
  DefaultRegistryRestoreForm: (props: Record<string, unknown>) => (
    <div data-testid="default-registry-form">
      <span data-testid="default-initial-url">{String(props.initialImageUrl ?? '')}</span>
      {props.actionButton as React.ReactNode}
    </div>
  ),
}));

jest.mock('@/pages/RestoreFromBackup/ExternalRegistryForm', () => ({
  ExternalRegistryRestoreForm: (props: Record<string, unknown>) => (
    <div data-testid="external-registry-form">
      <span data-testid="external-initial-url">{String(props.initialImageUrl ?? '')}</span>
      {props.actionButton as React.ReactNode}
    </div>
  ),
}));

const mockOnChange = jest.fn();
const mockOnDefaultValidationChange = jest.fn();
const mockOnExternalValidationChange = jest.fn();

const { renderComponent } = getComponentRenderer(getComponent);

describe('RestoreModeAccordion', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should render both accordion toggles', () => {
    renderComponent();

    expect(screen.getByRole('button', { name: /Default registry/i })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /External registry/i })).toBeInTheDocument();
  });

  test('should have default-registry expanded by default', () => {
    renderComponent();

    const defaultBtn = screen.getByRole('button', { name: /Default registry/i });
    const externalBtn = screen.getByRole('button', { name: /External registry/i });

    expect(defaultBtn).toHaveAttribute('aria-expanded', 'true');
    expect(externalBtn).toHaveAttribute('aria-expanded', 'false');
  });

  test('should render default-registry form when expanded', () => {
    renderComponent();

    expect(screen.getByTestId('default-registry-form')).toBeInTheDocument();
    expect(screen.queryByTestId('external-registry-form')).not.toBeInTheDocument();
  });

  test('should expand external-registry and collapse default when clicked', async () => {
    renderComponent();

    const externalBtn = screen.getByRole('button', { name: /External registry/i });
    await userEvent.click(externalBtn);

    expect(externalBtn).toHaveAttribute('aria-expanded', 'true');
    expect(screen.getByRole('button', { name: /Default registry/i })).toHaveAttribute(
      'aria-expanded',
      'false',
    );
  });

  test('should render external-registry form when external is expanded', async () => {
    renderComponent();

    await userEvent.click(screen.getByRole('button', { name: /External registry/i }));

    expect(screen.getByTestId('external-registry-form')).toBeInTheDocument();
    expect(screen.queryByTestId('default-registry-form')).not.toBeInTheDocument();
  });

  test('should call onChange with correct mode when toggling', async () => {
    renderComponent();

    await userEvent.click(screen.getByRole('button', { name: /External registry/i }));
    expect(mockOnChange).toHaveBeenCalledWith('external-registry');

    await userEvent.click(screen.getByRole('button', { name: /Default registry/i }));
    expect(mockOnChange).toHaveBeenCalledWith('default-registry');
  });

  test('should pass initialBackupImageUrl only to DefaultRegistryRestoreForm', () => {
    renderComponent({
      initialBackupImageUrl: 'internal-registry.svc:5000/ns/ws:latest',
    });

    expect(screen.getByTestId('default-initial-url')).toHaveTextContent(
      'internal-registry.svc:5000/ns/ws:latest',
    );
  });

  test('should pass initialExternalImageUrl only to ExternalRegistryRestoreForm', async () => {
    renderComponent({
      restoreMode: 'external-registry',
      initialExternalImageUrl: 'quay.io/user/ws:latest',
    });

    expect(screen.getByTestId('external-initial-url')).toHaveTextContent('quay.io/user/ws:latest');
  });

  test('should render with external-registry expanded when restoreMode is external-registry', () => {
    renderComponent({ restoreMode: 'external-registry' });

    const externalBtn = screen.getByRole('button', { name: /External registry/i });
    const defaultBtn = screen.getByRole('button', { name: /Default registry/i });

    expect(externalBtn).toHaveAttribute('aria-expanded', 'true');
    expect(defaultBtn).toHaveAttribute('aria-expanded', 'false');
  });

  test('should render the action button', () => {
    renderComponent();

    expect(screen.getByTestId('test-action-button')).toBeInTheDocument();
  });

  test('should hide default registry when backup is not configured', () => {
    renderComponent({ isBackupConfigured: false, restoreMode: 'external-registry' });

    expect(screen.queryByRole('button', { name: /Default registry/i })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: /External registry/i })).toBeInTheDocument();
  });
});

type ComponentOptions = {
  restoreMode?: RestoreMode;
  isBackupConfigured?: boolean;
  initialBackupImageUrl?: string;
  initialExternalImageUrl?: string;
};

function getComponent(options: ComponentOptions = {}) {
  return (
    <RestoreModeAccordion
      restoreMode={options.restoreMode ?? 'default-registry'}
      isBackupConfigured={options.isBackupConfigured ?? true}
      onChange={mockOnChange}
      existingWorkspaceNames={new Set()}
      existingBackupNames={new Set()}
      backups={[]}
      onDefaultRegistryValidationChange={mockOnDefaultValidationChange}
      initialBackupImageUrl={options.initialBackupImageUrl}
      initialExternalImageUrl={options.initialExternalImageUrl}
      onExternalRegistryValidationChange={mockOnExternalValidationChange}
      actionButton={<button data-testid="test-action-button">Restore</button>}
    />
  );
}
