/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { Card, CardBody, CardTitle, Content, ContentVariants } from '@patternfly/react-core';
import React from 'react';

import styles from '@/pages/WorkspaceDetails/AdvancedTab/Section/index.module.css';

export type Props = {
  title: string;
  description?: React.ReactNode;
  children: React.ReactNode;
};

/**
 * Common card layout for a single power-user feature on the Advanced tab.
 * Wrap each feature's UI in this so new additions stay visually consistent.
 */
export function AdvancedTabSection(props: Props): React.ReactElement {
  return (
    <Card>
      <CardTitle>{props.title}</CardTitle>
      <CardBody>
        {props.description && (
          <Content className={styles.description} component={ContentVariants.small}>
            {props.description}
          </Content>
        )}
        {props.children}
      </CardBody>
    </Card>
  );
}

export default AdvancedTabSection;
