/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { BackupStatus } from '@eclipse-che/common';
import { FastifyInstance } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { getDevWorkspaceClient } from '@/routes/api/helpers/getDevWorkspaceClient';
import { setup, teardown } from '@/utils/appBuilder';

// Mock helpers
jest.mock('@/routes/api/helpers/getServiceAccountToken');
jest.mock('@/routes/api/helpers/getToken');
jest.mock('@/routes/api/helpers/getDevWorkspaceClient');

// Mock KubeConfigProvider
jest.mock('@/services/kubeclient/kubeConfigProvider');

const mockGetClusterBackupConfig = jest.fn();
const mockGetWorkspaceBackupStatus = jest.fn();

// Mock RegistryApiService
const mockListBackupImages = jest.fn();
const mockValidateBackupImage = jest.fn();

jest.mock('@/devworkspaceClient/services/registryApi', () => ({
  RegistryApiService: jest.fn().mockImplementation(() => ({
    listBackupImages: mockListBackupImages,
    validateBackupImage: mockValidateBackupImage,
  })),
}));

describe('Backup Routes', () => {
  let app: FastifyInstance;
  const namespace = 'user-che';
  const workspaceName = 'my-workspace';

  beforeAll(async () => {
    app = await setup();
  });

  afterAll(() => {
    teardown(app);
  });

  beforeEach(() => {
    (getDevWorkspaceClient as jest.Mock).mockImplementation(() => ({
      backupApi: {
        getClusterBackupConfig: mockGetClusterBackupConfig,
        getWorkspaceBackupStatus: mockGetWorkspaceBackupStatus,
      },
    }));
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('GET /api/namespace/:namespace/backup-config', () => {
    it('should return backup config', async () => {
      const mockConfig = {
        enabled: true,
        schedule: '0 1 * * *',
        registry: 'image-registry.openshift-image-registry.svc:5000',
        nextScheduledBackup: '2026-02-27T01:00:00.000Z',
      };
      mockGetClusterBackupConfig.mockResolvedValue(mockConfig);

      const response = await app.inject({
        method: 'GET',
        url: `${baseApiPath}/namespace/${namespace}/backup-config`,
      });

      expect(response.statusCode).toBe(200);
      expect(JSON.parse(response.body)).toEqual(mockConfig);
      expect(mockGetClusterBackupConfig).toHaveBeenCalledTimes(1);
    });

    it('should return config with disabled backup', async () => {
      const mockConfig = {
        enabled: false,
        schedule: '',
        registry: '',
      };
      mockGetClusterBackupConfig.mockResolvedValue(mockConfig);

      const response = await app.inject({
        method: 'GET',
        url: `${baseApiPath}/namespace/${namespace}/backup-config`,
      });

      expect(response.statusCode).toBe(200);
      expect(JSON.parse(response.body)).toEqual(mockConfig);
    });

    it('should return 500 when getClusterBackupConfig throws', async () => {
      mockGetClusterBackupConfig.mockRejectedValue(new Error('Operator config not found'));

      const response = await app.inject({
        method: 'GET',
        url: `${baseApiPath}/namespace/${namespace}/backup-config`,
      });

      expect(response.statusCode).toBe(500);
    });
  });

  describe('GET /api/namespace/:namespace/devworkspaces/:workspaceName/backup-status', () => {
    it('should return backup status for workspace with successful backup', async () => {
      const mockBackupInfo = {
        status: BackupStatus.SUCCESS,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
        backupImageUrl:
          'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
      };

      mockGetWorkspaceBackupStatus.mockResolvedValue(mockBackupInfo);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toEqual(mockBackupInfo);
      expect(mockGetWorkspaceBackupStatus).toHaveBeenCalledWith(namespace, workspaceName);
    });

    it('should return status for workspace that has never been backed up', async () => {
      const mockBackupInfo = {
        status: BackupStatus.NEVER,
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
      };

      mockGetWorkspaceBackupStatus.mockResolvedValue(mockBackupInfo);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toEqual(mockBackupInfo);
      expect(response.status).toEqual(BackupStatus.NEVER);
      expect(response.lastBackupTime).toBeUndefined();
      expect(response.backupImageUrl).toBeUndefined();
    });

    it('should return status for workspace with backup in progress', async () => {
      const mockBackupInfo = {
        status: BackupStatus.IN_PROGRESS,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
        backupImageUrl:
          'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
      };

      mockGetWorkspaceBackupStatus.mockResolvedValue(mockBackupInfo);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toEqual(BackupStatus.IN_PROGRESS);
      expect(response.lastBackupTime).toBeDefined();
    });

    it('should return status for workspace with failed backup', async () => {
      const mockBackupInfo = {
        status: BackupStatus.FAILED,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
        error: 'Backup job failed: insufficient storage',
      };

      mockGetWorkspaceBackupStatus.mockResolvedValue(mockBackupInfo);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toEqual(BackupStatus.FAILED);
      expect(response.error).toContain('insufficient storage');
    });

    it('should handle API errors gracefully', async () => {
      const apiError = new Error('Unable to query backup jobs');

      mockGetWorkspaceBackupStatus.mockRejectedValue(apiError);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toContain('Unable to query backup jobs');
    });

    it('should handle workspace not found', async () => {
      const notFoundError = new Error('Workspace not found');

      mockGetWorkspaceBackupStatus.mockRejectedValue(notFoundError);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toContain('Workspace not found');
    });

    it('should call BackupApiService with correct parameters', async () => {
      const mockBackupInfo = {
        status: BackupStatus.SUCCESS,
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
      };

      mockGetWorkspaceBackupStatus.mockResolvedValue(mockBackupInfo);

      await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(mockGetWorkspaceBackupStatus).toHaveBeenCalledWith(namespace, workspaceName);
    });
  });

  describe('GET /api/namespace/:namespace/backups', () => {
    it('should list backup images for namespace', async () => {
      const mockBackupList = {
        backups: [
          {
            workspaceName: 'my-workspace',
            imageUrl:
              'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
            timestamp: '2026-02-10T12:00:00.000Z',
            sizeBytes: 1024000,
            workspaceExists: true,
            labels: {},
          },
        ],
        total: 1,
        page: 1,
        perPage: 50,
      };

      mockListBackupImages.mockResolvedValue(mockBackupList);

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toEqual(mockBackupList);
      expect(mockListBackupImages).toHaveBeenCalledWith(namespace, undefined);
    });

    it('should list backup images with workspace name filter', async () => {
      const mockBackupList = {
        backups: [
          {
            workspaceName,
            imageUrl:
              'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
            timestamp: '2026-02-10T12:00:00.000Z',
            sizeBytes: 1024000,
            workspaceExists: true,
            labels: {},
          },
        ],
        total: 1,
        page: 1,
        perPage: 50,
      };

      mockListBackupImages.mockResolvedValue(mockBackupList);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/backups?workspaceName=${workspaceName}`);

      expect(res.statusCode).toEqual(200);
      expect(mockListBackupImages).toHaveBeenCalledWith(namespace, workspaceName);
    });

    it('should return empty list when no backups exist', async () => {
      const mockBackupList = {
        backups: [],
        total: 0,
        page: 1,
        perPage: 50,
      };

      mockListBackupImages.mockResolvedValue(mockBackupList);

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.backups).toHaveLength(0);
      expect(response.total).toBe(0);
    });

    it('should not crash with empty namespace', async () => {
      mockListBackupImages.mockResolvedValue({ backups: [], total: 0, page: 1, perPage: 50 });

      const res = await app.inject().get(`${baseApiPath}/namespace//backups`);

      expect(res.statusCode).toBeLessThan(500);
    });

    it('should handle API errors gracefully', async () => {
      const apiError = new Error('Unable to query backup images');

      mockListBackupImages.mockRejectedValue(apiError);

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toBeDefined();
    });
  });

  describe('POST /api/namespace/:namespace/backups/validate', () => {
    const imageUrl =
      'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest';

    it('should validate accessible backup image', async () => {
      const mockValidationResult = {
        valid: true,
        accessible: true,
        metadata: {
          workspaceName: 'my-workspace',
          namespace: 'user-che',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
        },
      };

      mockValidateBackupImage.mockResolvedValue(mockValidationResult);

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toEqual(mockValidationResult);
      expect(response.valid).toBe(true);
      expect(response.accessible).toBe(true);
      expect(mockValidateBackupImage).toHaveBeenCalledWith(imageUrl);
    });

    it('should validate inaccessible backup image', async () => {
      const mockValidationResult = {
        valid: true,
        accessible: false,
      };

      mockValidateBackupImage.mockResolvedValue(mockValidationResult);

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.valid).toBe(true);
      expect(response.accessible).toBe(false);
      expect(response.metadata).toBeUndefined();
    });

    it('should handle invalid image URL format', async () => {
      const mockValidationResult = {
        valid: false,
        accessible: false,
        error: 'Invalid image URL format',
      };

      mockValidateBackupImage.mockResolvedValue(mockValidationResult);

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: 'invalid-url' });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.valid).toBe(false);
      expect(response.error).toContain('Invalid image URL format');
    });

    it('should reject empty imageUrl', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: '' });

      expect(res.statusCode).toEqual(400);
      const response = res.json();

      expect(response.message).toContain('imageUrl');
    });

    it('should reject missing imageUrl', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({});

      expect(res.statusCode).toEqual(400);
      const response = res.json();

      expect(response.message).toContain('imageUrl');
    });

    it('should handle API errors gracefully', async () => {
      const apiError = new Error('Registry query failed');

      mockValidateBackupImage.mockRejectedValue(apiError);

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toBeDefined();
    });
  });
});
