/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { FormGroup, InputGroup, TextInput, ValidatedOptions } from '@patternfly/react-core';
import { ExclamationCircleIcon, ExclamationTriangleIcon } from '@patternfly/react-icons';
import React from 'react';

export type Props = {
  fieldId: string;
  helperText: string;
  value: string;
  validated: ValidatedOptions;
  error: string;
  warning?: string;
  onChange: (value: string) => void;
  actionButton: React.ReactNode;
};

export const WorkspaceNameField: React.FC<Props> = ({
  fieldId,
  helperText,
  value,
  validated,
  error,
  warning,
  onChange,
  actionButton,
}) => {
  const helperTextInvalid = error || warning || '';
  const helperTextInvalidIcon =
    validated === ValidatedOptions.warning ? (
      <ExclamationTriangleIcon />
    ) : (
      <ExclamationCircleIcon />
    );

  // PatternFly FormGroup only renders helperTextInvalid when validated='error'.
  // For validated='warning', it falls back to helperText, so we must put the
  // warning message there to ensure it is displayed.
  const effectiveHelperText =
    validated === ValidatedOptions.warning && warning ? warning : helperText;

  return (
    <FormGroup
      fieldId={fieldId}
      label="Workspace name"
      isRequired
      helperText={effectiveHelperText}
      helperTextInvalid={helperTextInvalid}
      helperTextInvalidIcon={helperTextInvalidIcon}
      validated={validated}
    >
      <InputGroup>
        <TextInput
          id={fieldId}
          aria-label="Workspace name"
          placeholder="my-workspace"
          value={value}
          validated={validated}
          onChange={(_value: string) => onChange(_value)}
        />
        {actionButton}
      </InputGroup>
    </FormGroup>
  );
};
