/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import {
  FormGroup,
  FormHelperText,
  HelperText,
  HelperTextItem,
  InputGroup,
  TextInput,
  ValidatedOptions,
} from '@patternfly/react-core';
import { ExclamationCircleIcon, ExclamationTriangleIcon } from '@patternfly/react-icons';
import React, { useCallback, useEffect, useState } from 'react';

import {
  sanitizeWorkspaceName,
  validateWorkspaceNameWithConflicts,
} from '@/pages/RestoreFromBackup/helpers';

export type Props = {
  fieldId: string;
  helperText: string;
  value: string;
  existingWorkspaceNames: Set<string>;
  existingBackupNames?: Set<string>;
  onChange: (value: string, isValid: boolean) => void;
  actionButton: React.ReactNode;
};

export const WorkspaceNameField: React.FC<Props> = ({
  fieldId,
  helperText,
  value,
  existingWorkspaceNames,
  existingBackupNames,
  onChange,
  actionButton,
}) => {
  const [internalValue, setInternalValue] = useState(value);
  const [dirty, setDirty] = useState(false);
  const [validated, setValidated] = useState<ValidatedOptions>(ValidatedOptions.default);
  const [error, setError] = useState('');
  const [warning, setWarning] = useState('');

  const applyValidation = useCallback(
    (name: string) => {
      const result = validateWorkspaceNameWithConflicts(
        name,
        existingWorkspaceNames,
        existingBackupNames,
      );
      setValidated(result.validated);
      setError(result.error);
      setWarning(result.warning);
      return result;
    },
    [existingWorkspaceNames, existingBackupNames],
  );

  // Accept parent's suggestion when untouched (GitProviderEndpoint pattern)
  useEffect(() => {
    if (!dirty) {
      setInternalValue(value);
      const result = applyValidation(value);
      onChange(value, result.isValid);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, applyValidation]);

  // Re-validate when conflict sets change (e.g. workspace created/deleted while form is open)
  useEffect(() => {
    if (internalValue) {
      const result = applyValidation(internalValue);
      onChange(internalValue, result.isValid);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [existingWorkspaceNames, existingBackupNames]);

  const isDirtyEmpty = dirty && !internalValue;
  const effectiveValidated = isDirtyEmpty ? ValidatedOptions.error : validated;

  const helperTextInvalid = error || warning || '';
  const helperTextInvalidIcon =
    effectiveValidated === ValidatedOptions.warning ? (
      <ExclamationTriangleIcon />
    ) : (
      <ExclamationCircleIcon />
    );
  const effectiveHelperText =
    effectiveValidated === ValidatedOptions.warning && warning ? warning : helperText;

  const getHelperContent = (): React.ReactNode => {
    if (isDirtyEmpty) {
      return (
        <HelperTextItem variant="error" icon={<ExclamationCircleIcon />}>
          Workspace name is required.
        </HelperTextItem>
      );
    }
    if (
      effectiveValidated === ValidatedOptions.error ||
      effectiveValidated === ValidatedOptions.warning
    ) {
      return (
        <HelperTextItem
          variant={effectiveValidated === ValidatedOptions.error ? 'error' : 'warning'}
          icon={helperTextInvalidIcon}
        >
          {helperTextInvalid}
        </HelperTextItem>
      );
    }
    return <HelperTextItem>{effectiveHelperText}</HelperTextItem>;
  };

  const handleChange = (_event: React.FormEvent, newValue: string) => {
    setDirty(true);
    const sanitized = sanitizeWorkspaceName(newValue);
    setInternalValue(sanitized);
    const result = applyValidation(sanitized);
    onChange(sanitized, result.isValid);
  };

  return (
    <FormGroup fieldId={fieldId} label="Workspace name" isRequired>
      <InputGroup>
        <TextInput
          id={fieldId}
          aria-label="Workspace name"
          placeholder="my-workspace"
          value={internalValue}
          validated={
            effectiveValidated === ValidatedOptions.error
              ? 'error'
              : effectiveValidated === ValidatedOptions.warning
                ? 'warning'
                : 'default'
          }
          onChange={handleChange}
        />
        {actionButton}
      </InputGroup>
      <FormHelperText>
        <HelperText>{getHelperContent()}</HelperText>
      </FormHelperText>
    </FormGroup>
  );
};
