/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupValidationResult } from '@eclipse-che/common';
import userEvent from '@testing-library/user-event';
import React from 'react';

import { ExternalRegistryRestoreForm } from '@/pages/RestoreFromBackup/ExternalRegistryForm';
import getComponentRenderer, { screen, waitFor } from '@/services/__mocks__/getComponentRenderer';

const mockOnValidateImage = jest.fn();
const mockOnValidationChange = jest.fn();

const { renderComponent } = getComponentRenderer(getComponent);

describe('ExternalRegistryRestoreForm', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });

  afterEach(() => {
    jest.useRealTimers();
    jest.clearAllMocks();
  });

  test('should call onValidationChange(false) on initial render', () => {
    renderComponent();

    expect(mockOnValidationChange).toHaveBeenCalledWith(false, null);
  });

  test('should render image URL input and workspace name input', () => {
    renderComponent();

    expect(screen.getByLabelText('Backup image URL')).toBeInTheDocument();
    expect(screen.getByLabelText('Workspace name')).toBeInTheDocument();
  });

  test('should render the action button', () => {
    renderComponent();

    expect(screen.getByTestId('test-action-button')).toBeInTheDocument();
  });

  test('should debounce validation when typing a valid URL', async () => {
    jest.useRealTimers();

    const validationResult: BackupValidationResult = {
      valid: true,
      accessible: true,
      metadata: {
        workspaceName: 'test-ws',
        namespace: 'test-ns',
        timestamp: '2026-02-11T12:00:00Z',
        sizeBytes: 1024,
      },
    };
    mockOnValidateImage.mockResolvedValue(validationResult);

    renderComponent();

    const input = screen.getByLabelText('Backup image URL');
    await userEvent.type(input, 'registry.example.com/ns/workspace:latest');

    // Debounce fires after 500ms — wait for validation call
    await waitFor(
      () => {
        expect(mockOnValidateImage).toHaveBeenCalledWith(
          'registry.example.com/ns/workspace:latest',
        );
      },
      { timeout: 2000 },
    );
  });

  test('should call onValidationChange(true) when validation succeeds', async () => {
    jest.useRealTimers();

    const validationResult: BackupValidationResult = {
      valid: true,
      accessible: true,
      metadata: {
        workspaceName: 'test-ws',
        namespace: 'test-ns',
        timestamp: '2026-02-11T12:00:00Z',
        sizeBytes: 1024,
      },
    };
    mockOnValidateImage.mockResolvedValue(validationResult);

    renderComponent();

    const input = screen.getByLabelText('Backup image URL');
    await userEvent.type(input, 'registry.example.com/ns/workspace:latest');

    await waitFor(
      () => {
        expect(mockOnValidationChange).toHaveBeenCalledWith(true, {
          workspaceName: 'test-ws',
          imageUrl: 'registry.example.com/ns/workspace:latest',
        });
      },
      { timeout: 2000 },
    );
  });

  test('should auto-populate workspace name from validation metadata', async () => {
    jest.useRealTimers();

    const validationResult: BackupValidationResult = {
      valid: true,
      accessible: true,
      metadata: {
        workspaceName: 'detected-name',
        namespace: 'test-ns',
        timestamp: '2026-02-11T12:00:00Z',
        sizeBytes: 1024,
      },
    };
    mockOnValidateImage.mockResolvedValue(validationResult);

    renderComponent();

    const input = screen.getByLabelText('Backup image URL');
    await userEvent.type(input, 'registry.example.com/ns/workspace:latest');

    await waitFor(
      () => {
        const nameInput = screen.getByLabelText('Workspace name');
        expect(nameInput).toHaveValue('detected-name');
      },
      { timeout: 2000 },
    );
  });

  test('should not trigger validation for invalid URL format', async () => {
    jest.useRealTimers();

    renderComponent();

    const input = screen.getByLabelText('Backup image URL');
    await userEvent.type(input, 'not-a-valid-url');

    // Wait a bit to ensure debounce would have fired
    await new Promise(resolve => setTimeout(resolve, 800));

    expect(mockOnValidateImage).not.toHaveBeenCalled();
  });

  test('should call onValidationChange(false) when validation fails', async () => {
    jest.useRealTimers();

    const failedResult: BackupValidationResult = {
      valid: false,
      accessible: false,
      error: 'Image not found',
    };
    mockOnValidateImage.mockResolvedValue(failedResult);

    // Clear initial call
    mockOnValidationChange.mockClear();

    renderComponent();

    const input = screen.getByLabelText('Backup image URL');
    await userEvent.type(input, 'registry.example.com/ns/workspace:latest');

    await waitFor(
      () => {
        expect(mockOnValidationChange).toHaveBeenCalledWith(false, null);
      },
      { timeout: 2000 },
    );
  });

  test('should trigger validation on mount when initialImageUrl is provided', async () => {
    jest.useRealTimers();

    const validationResult: BackupValidationResult = {
      valid: true,
      accessible: true,
      metadata: {
        workspaceName: 'initial-ws',
        namespace: 'test-ns',
        timestamp: '2026-02-11T12:00:00Z',
        sizeBytes: 1024,
      },
    };
    mockOnValidateImage.mockResolvedValue(validationResult);

    renderComponent({ initialImageUrl: 'registry.example.com/ns/initial:latest' });

    await waitFor(
      () => {
        expect(mockOnValidateImage).toHaveBeenCalledWith('registry.example.com/ns/initial:latest');
      },
      { timeout: 2000 },
    );
  });
});

type ComponentOptions = {
  initialImageUrl?: string;
  existingWorkspaceNames?: Set<string>;
};

function getComponent(options: ComponentOptions = {}) {
  return (
    <ExternalRegistryRestoreForm
      initialImageUrl={options.initialImageUrl}
      existingWorkspaceNames={options.existingWorkspaceNames ?? new Set()}
      onValidateImage={mockOnValidateImage}
      onValidationChange={mockOnValidationChange}
      actionButton={<button data-testid="test-action-button">Restore</button>}
    />
  );
}
