/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { CoreV1Event } from '@kubernetes/client-node';
import {
  Content,
  ContentVariants,
  EmptyState,
  EmptyStateBody,
  Flex,
  FlexItem,
  Stack,
  StackItem,
} from '@patternfly/react-core';
import { FileIcon } from '@patternfly/react-icons';
import React from 'react';
import Pluralize from 'react-pluralize';
import { connect, ConnectedProps } from 'react-redux';

import compareEventTime from '@/components/WorkspaceEvents/compareEventTime';
import styles from '@/components/WorkspaceEvents/index.module.css';
import { WorkspaceEventsItem } from '@/components/WorkspaceEvents/Item';
import { RootState } from '@/store';
import { selectAllEvents } from '@/store/Events/selectors';

export type Props = {
  podName: string | undefined;
} & MappedProps;

class AgentPodEvents extends React.PureComponent<Props> {
  private getEventItems(events: CoreV1Event[]): React.ReactNode[] {
    return events
      .filter(event => event.message)
      .sort(compareEventTime)
      .map((event, index) => {
        return (
          <StackItem key={`${event.message}${event.metadata.uid}` || index}>
            <div className={styles.fadeIn}>
              <WorkspaceEventsItem event={event} />
            </div>
          </StackItem>
        );
      });
  }

  render() {
    const { podName, allEvents } = this.props;

    if (!podName) {
      return (
        <EmptyState icon={FileIcon} titleText="No events to show.">
          <EmptyStateBody>Events will be streamed for a starting agent pod.</EmptyStateBody>
        </EmptyState>
      );
    }

    const podEvents = allEvents.filter(
      event => event.involvedObject.name === podName && event.involvedObject.kind === 'Pod',
    );

    const eventItems = this.getEventItems(podEvents);

    if (eventItems.length === 0) {
      return (
        <EmptyState icon={FileIcon} titleText="No events to show.">
          <EmptyStateBody>Events will be streamed for the agent pod.</EmptyStateBody>
        </EmptyState>
      );
    }

    return (
      <Stack hasGutter>
        <StackItem>
          <Flex>
            <FlexItem>
              <Content component={ContentVariants.small}>Streaming events...</Content>
            </FlexItem>
            <FlexItem align={{ default: 'alignRight' }}>
              <Content component={ContentVariants.small}>
                Showing <Pluralize singular={'event'} count={eventItems.length} />
              </Content>
            </FlexItem>
          </Flex>
        </StackItem>
        {eventItems}
        <StackItem>
          <Content component={ContentVariants.small}>Older events are not stored.</Content>
        </StackItem>
      </Stack>
    );
  }
}

const mapStateToProps = (state: RootState) => ({
  allEvents: selectAllEvents(state),
});

const connector = connect(mapStateToProps);

type MappedProps = ConnectedProps<typeof connector>;
export default connector(AgentPodEvents);
