#!/usr/bin/env bash
# Copyright (c) 2018-2025 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Prepares plugins for build:
#   1. Unpacks any *.zip files in plugins/
#   2. Creates symlinks from packages/{frontend,backend}/src/plugins/<id> to the plugin source
#   3. Auto-generates packages/dashboard-frontend/src/plugins/index.ts

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PLUGINS_DIR="$ROOT_DIR/plugins"
FRONTEND_PLUGINS="$ROOT_DIR/packages/dashboard-frontend/src/plugins"
BACKEND_PLUGINS="$ROOT_DIR/packages/dashboard-backend/src/plugins"

# --- Step 1: Unpack ZIP files ---
for zipfile in "$PLUGINS_DIR"/*.zip; do
  [ -f "$zipfile" ] || continue
  dirname="$PLUGINS_DIR/$(basename "$zipfile" .zip)"
  if [ ! -d "$dirname" ] || [ "$zipfile" -nt "$dirname" ]; then
    echo "Unpacking plugin: $(basename "$zipfile")"
    rm -rf "$dirname"
    unzip -q -o "$zipfile" -d "$dirname"
  fi
done

# --- Step 2: Create symlinks ---
mkdir -p "$FRONTEND_PLUGINS"

for plugindir in "$PLUGINS_DIR"/*/; do
  [ -f "$plugindir/plugin.json" ] || continue
  pluginname=$(basename "$plugindir")

  # Frontend symlink (skip if already a real directory, e.g. Docker copy)
  if [ -d "$plugindir/frontend" ]; then
    target="$FRONTEND_PLUGINS/$pluginname"
    if [ ! -L "$target" ] && [ ! -d "$target" ]; then
      ln -sfn "../../../../plugins/$pluginname/frontend" "$target"
      echo "Linked frontend: $pluginname"
    fi
  fi

  # Backend symlink (skip if already a real directory, e.g. Docker copy)
  if [ -d "$plugindir/backend" ]; then
    target="$BACKEND_PLUGINS/$pluginname"
    if [ ! -L "$target" ] && [ ! -d "$target" ]; then
      ln -sfn "../../../../plugins/$pluginname/backend" "$target"
      echo "Linked backend: $pluginname"
    fi
  fi
done

# --- Step 3: Auto-generate frontend plugin registration ---
REGISTRY_FILE="$FRONTEND_PLUGINS/index.ts"
{
  cat <<'HEADER'
/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// AUTO-GENERATED by scripts/prepare-plugins.sh — do not edit manually

import { registerFrontendPlugin } from '@/plugin-registry';

HEADER

  # Collect enabled plugins
  imports=""
  registrations=""
  for plugindir in "$PLUGINS_DIR"/*/; do
    [ -f "$plugindir/plugin.json" ] || continue
    pluginname=$(basename "$plugindir")

    enabled=$(python3 -c "import json; print(json.load(open('$plugindir/plugin.json')).get('enabled', False))" 2>/dev/null || echo "false")
    [ "$enabled" = "True" ] || continue

    has_frontend=$([ -f "$plugindir/frontend/plugin.ts" ] || [ -f "$plugindir/frontend/plugin.tsx" ] && echo "yes" || echo "no")
    [ "$has_frontend" = "yes" ] || continue

    # Convert plugin-name to camelCase variable name (e.g., ai-selector -> aiSelectorPlugin)
    varname=$(python3 -c "
import re
name = '$pluginname'
parts = name.split('-')
print(parts[0] + ''.join(w.capitalize() for w in parts[1:]) + 'Plugin')
")

    imports="${imports}import { ${varname} } from '@/plugins/${pluginname}/plugin';\n"
    registrations="${registrations}  registerFrontendPlugin(${varname});\n"
  done

  echo -e "$imports"
  echo "export function registerAllPlugins(): void {"
  echo -e "$registrations}"
} > "$REGISTRY_FILE"

echo "Generated: $REGISTRY_FILE"
echo "Plugin preparation complete."
