/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

/* eslint-disable @typescript-eslint/no-unused-vars */

// Generated by AI Assistant

import * as mockClient from '@kubernetes/client-node';
import { CoreV1Api, V1ConfigMap, V1ConfigMapList } from '@kubernetes/client-node';

import { AiRegistryApiService } from '@/devworkspaceClient/services/aiRegistryApi';
import { CoreV1API } from '@/devworkspaceClient/services/helpers/prepareCoreV1API';
import { logger } from '@/utils/logger';

jest.mock('@/devworkspaceClient/services/helpers/retryableExec.ts');

jest.mock('@/utils/logger', () => ({
  logger: {
    warn: jest.fn(),
    error: jest.fn(),
  },
}));

const mockCoreV1Api = {
  listNamespacedConfigMap: jest.fn(),
};

jest.mock('@/devworkspaceClient/services/helpers/prepareCoreV1API', () => ({
  prepareCoreV1API: jest.fn(() => mockCoreV1Api),
}));

const namespace = 'eclipse-che';
const AI_REGISTRY_LABEL_SELECTOR =
  'app.kubernetes.io/component=ai-tool-registry,app.kubernetes.io/part-of=che.eclipse.org';

const EMPTY_REGISTRY = {
  providers: [],
  tools: [],
  defaultAiProviders: [],
};

describe('AI Registry API Service', () => {
  let service: AiRegistryApiService;
  const originalEnv = process.env;

  beforeEach(() => {
    process.env = { ...originalEnv, CHECLUSTER_CR_NAMESPACE: namespace };

    const { KubeConfig } = mockClient;
    const kubeConfig = new KubeConfig();
    service = new AiRegistryApiService(kubeConfig);
  });

  afterEach(() => {
    process.env = originalEnv;
    jest.clearAllMocks();
  });

  describe('get', () => {
    it('should return empty registry when CHECLUSTER_CR_NAMESPACE is not set', async () => {
      delete process.env.CHECLUSTER_CR_NAMESPACE;

      const result = await service.get();

      expect(result).toEqual(EMPTY_REGISTRY);
      expect(logger.warn).toHaveBeenCalledWith(
        'Mandatory environment variables are not defined: $CHECLUSTER_CR_NAMESPACE',
      );
      expect(mockCoreV1Api.listNamespacedConfigMap).not.toHaveBeenCalled();
    });

    it('should return parsed registry from ConfigMap data', async () => {
      const registryData = {
        providers: [{ id: 'provider1', name: 'Provider 1' }],
        tools: [{ id: 'tool1', name: 'Tool 1', providerId: 'provider1' }],
        defaultAiProviders: ['provider1'],
      };

      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValueOnce({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify(registryData),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get();

      expect(mockCoreV1Api.listNamespacedConfigMap).toHaveBeenCalledWith({
        namespace,
        labelSelector: AI_REGISTRY_LABEL_SELECTOR,
      });
      expect(result).toEqual(registryData);
    });

    it('should return empty registry when no ConfigMaps found', async () => {
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValueOnce({
        items: [],
      } as V1ConfigMapList);

      const result = await service.get();

      expect(result).toEqual(EMPTY_REGISTRY);
    });

    it('should return empty registry when ConfigMap has no data', async () => {
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValueOnce({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: undefined,
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get();

      expect(result).toEqual(EMPTY_REGISTRY);
    });

    it('should skip ConfigMaps with undefined data', async () => {
      const registryData = {
        providers: [{ id: 'provider2', name: 'Provider 2' }],
        tools: [{ id: 'tool2', name: 'Tool 2', providerId: 'provider2' }],
        defaultAiProviders: ['provider2'],
      };

      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValueOnce({
        items: [
          {
            metadata: { name: 'empty-cm' },
            data: undefined,
          } as V1ConfigMap,
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify(registryData),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get();

      expect(result).toEqual(registryData);
    });

    it('should throw error when API call fails', async () => {
      mockCoreV1Api.listNamespacedConfigMap.mockRejectedValueOnce(new Error('Forbidden'));

      await expect(service.get()).rejects.toThrow('Unable to list AI tool registry ConfigMap');
    });

    it('should handle invalid JSON in ConfigMap data and return empty registry', async () => {
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValueOnce({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': 'not valid json{{{',
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get();

      expect(logger.error).toHaveBeenCalledWith(
        expect.objectContaining({ message: expect.stringContaining('') }),
        'Failed to parse AI tool registry data: %s',
        'registry.json',
      );
      expect(result).toEqual(EMPTY_REGISTRY);
    });

    it('should handle missing arrays in parsed data and return empty arrays', async () => {
      const incompleteData = {
        providers: 'not-an-array',
        tools: null,
        // defaultAiProviders is missing entirely
      };

      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValueOnce({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify(incompleteData),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get();

      expect(result).toEqual(EMPTY_REGISTRY);
    });

    it('should filter out tools without a string providerId', async () => {
      const registryData = {
        providers: [],
        tools: [{ foo: 42 }, { providerId: 123 }, { providerId: 'valid/provider', name: 'Valid' }],
        defaultAiProviders: [],
      };

      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValueOnce({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: { 'registry.json': JSON.stringify(registryData) },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get();

      expect(result.tools).toHaveLength(1);
      expect(result.tools[0]).toMatchObject({ providerId: 'valid/provider' });
    });
  });

  describe('arch filtering', () => {
    const toolNoArch = {
      providerId: 'google/gemini',
      tag: 'latest',
      name: 'Gemini CLI',
      url: 'https://example.com',
      binary: 'gemini',
      pattern: 'bundle',
      injectorImage: 'quay.io/test/gemini:latest',
    };
    const toolX86Only = {
      providerId: 'test/x86-only',
      tag: 'latest',
      name: 'X86 Only Tool',
      url: 'https://example.com',
      binary: 'x86tool',
      pattern: 'init',
      injectorImage: 'quay.io/test/x86tool:latest',
      arch: ['x86_64'],
    };
    const toolX86AndArm = {
      providerId: 'test/multi-arch',
      tag: 'latest',
      name: 'Multi Arch Tool',
      url: 'https://example.com',
      binary: 'multitool',
      pattern: 'init',
      injectorImage: 'quay.io/test/multitool:latest',
      arch: ['x86_64', 'arm64'],
    };

    const registryData = {
      providers: [{ id: 'provider1', name: 'Provider 1', publisher: 'Test' }],
      tools: [toolNoArch, toolX86Only, toolX86AndArm],
      defaultAiProviders: ['provider1'],
    };

    beforeEach(() => {
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValue({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify(registryData),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);
    });

    it('should return all tools when currentArch is not provided', async () => {
      const result = await service.get();

      expect(result.tools).toHaveLength(3);
      expect(result.tools).toEqual(registryData.tools);
    });

    it('should filter tools by architecture when currentArch is provided', async () => {
      const result = await service.get('arm64');

      expect(result.tools).toHaveLength(2);
      expect(result.tools).toContainEqual(toolNoArch);
      expect(result.tools).toContainEqual(toolX86AndArm);
      expect(result.tools).not.toContainEqual(toolX86Only);
    });

    it('should include tools with no arch field on any architecture', async () => {
      const result = await service.get('s390x');

      expect(result.tools).toHaveLength(1);
      expect(result.tools).toContainEqual(toolNoArch);
    });

    it('should return tools matching x86_64 architecture', async () => {
      const result = await service.get('x86_64');

      expect(result.tools).toHaveLength(3);
      expect(result.tools).toContainEqual(toolNoArch);
      expect(result.tools).toContainEqual(toolX86Only);
      expect(result.tools).toContainEqual(toolX86AndArm);
    });

    it('should skip null elements in tools and return remaining valid tools', async () => {
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValue({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify({
                providers: registryData.providers,
                tools: [null, toolNoArch, null, toolX86Only],
                defaultAiProviders: registryData.defaultAiProviders,
              }),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get('x86_64');

      expect(result.tools).toHaveLength(2);
      expect(result.tools).toContainEqual(toolNoArch);
      expect(result.tools).toContainEqual(toolX86Only);
    });

    it('should match tools using OCI alias "amd64" when cluster reports x86_64', async () => {
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValue({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify({
                providers: registryData.providers,
                tools: [{ ...toolX86Only, arch: ['amd64', 'arm64'] }],
                defaultAiProviders: registryData.defaultAiProviders,
              }),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get('x86_64');

      expect(result.tools).toHaveLength(1);
    });

    it('should match tools using OCI alias "aarch64" when cluster reports arm64', async () => {
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValue({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify({
                providers: registryData.providers,
                tools: [{ ...toolX86Only, arch: ['aarch64'] }],
                defaultAiProviders: registryData.defaultAiProviders,
              }),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get('arm64');

      expect(result.tools).toHaveLength(1);
    });

    it('should treat a non-array arch value as no restriction when filtering', async () => {
      const toolMalformedArch = {
        ...toolX86Only,
        providerId: 'test/malformed',
        arch: 'x86_64' as unknown as string[],
      };
      mockCoreV1Api.listNamespacedConfigMap.mockResolvedValue({
        items: [
          {
            metadata: { name: 'ai-tool-registry' },
            data: {
              'registry.json': JSON.stringify({
                providers: registryData.providers,
                tools: [toolMalformedArch],
                defaultAiProviders: registryData.defaultAiProviders,
              }),
            },
          } as V1ConfigMap,
        ],
      } as V1ConfigMapList);

      const result = await service.get('arm64');

      expect(result.tools).toHaveLength(1);
      expect(result.tools[0]).toMatchObject({ providerId: 'test/malformed' });
    });
  });
});
