/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { Button, Toolbar, ToolbarContent, ToolbarGroup, ToolbarItem } from '@patternfly/react-core';
import { RocketIcon } from '@patternfly/react-icons';
import React from 'react';

import { DevfileEditor } from '@/components/DevfileEditor';
import DevfileEditorTools from '@/components/DevfileEditorTools';
import styles from '@/pages/DevfileDetails/EditorPanel/index.module.css';
import { DevfileSchema } from '@/services/backend-client/devfileSchemaApi';

export interface Props {
  devfileName: string;
  editorTitle?: string;
  editorStatusLabel?: React.ReactNode;
  devfileSchema?: DevfileSchema | undefined;
  editorContent: string;
  isExpanded: boolean;
  readOnly?: boolean;
  isSaved?: boolean;
  hasValidationError?: boolean;
  onEditorChange?: (value: string) => void;
  onValidation?: (errorMessage: string) => void;
  onEditorFocusChange?: (focused: boolean) => void;
  onSave?: () => void;
  onRefresh?: () => void;
  onCreateWorkspace?: () => void;
  onExpandToggle: () => void;
  toolsReadOnly?: boolean;
  alwaysShowToolbar?: boolean;
  actionButtonLabel?: string;
  actionButtonIcon?: React.ReactNode;
  actionButtonDisabled?: boolean;
  actionButtonDanger?: boolean;
  onAction?: () => void;
}

export default class EditorPanel extends React.PureComponent<Props> {
  render(): React.ReactElement {
    const {
      devfileName,
      devfileSchema,
      editorContent,
      isSaved,
      hasValidationError,
      isExpanded,
      readOnly,
      onEditorChange,
      onValidation,
      onEditorFocusChange,
      onSave,
      onRefresh,
      onCreateWorkspace,
      onExpandToggle,
      toolsReadOnly,
      alwaysShowToolbar,
      actionButtonLabel,
      actionButtonIcon,
      actionButtonDisabled,
      actionButtonDanger,
      onAction,
    } = this.props;

    return (
      <div data-testid="editor-panel">
        <DevfileEditorTools
          contentText={editorContent}
          workspaceName={devfileName}
          title={this.props.editorTitle}
          statusLabel={this.props.editorStatusLabel}
          isExpanded={isExpanded}
          readOnly={toolsReadOnly !== undefined ? toolsReadOnly : readOnly}
          onToggleExpand={onExpandToggle}
        />
        <div className={styles.editorContainer}>
          <DevfileEditor
            id="devfile-editor-id"
            value={editorContent}
            schema={devfileSchema}
            readOnly={readOnly}
            onChange={onEditorChange}
            onValidation={onValidation}
            onFocusChange={onEditorFocusChange}
          />
        </div>
        {(!readOnly || alwaysShowToolbar) && (
          <Toolbar hasNoPadding className={styles.toolbar}>
            <ToolbarContent>
              <ToolbarGroup>
                <ToolbarItem>
                  <Button
                    variant="secondary"
                    onClick={onRefresh}
                    isDisabled={readOnly}
                    data-testid="refresh-button"
                  >
                    Refresh
                  </Button>
                </ToolbarItem>
                <ToolbarItem>
                  <Button
                    variant="primary"
                    onClick={onSave}
                    isDisabled={readOnly || isSaved || hasValidationError}
                    data-testid="save-button"
                  >
                    Save
                  </Button>
                </ToolbarItem>
              </ToolbarGroup>
              <ToolbarGroup align={{ default: 'alignEnd' }}>
                <ToolbarItem>
                  <Button
                    variant="secondary"
                    isDanger={actionButtonDanger}
                    icon={actionButtonIcon || <RocketIcon />}
                    iconPosition="left"
                    isDisabled={
                      actionButtonDisabled !== undefined
                        ? actionButtonDisabled
                        : !isSaved || hasValidationError
                    }
                    onClick={onAction || onCreateWorkspace}
                    data-testid="action-button"
                  >
                    {actionButtonLabel || 'Create Workspace'}
                  </Button>
                </ToolbarItem>
              </ToolbarGroup>
            </ToolbarContent>
          </Toolbar>
        )}
      </div>
    );
  }
}
