/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import {
  Button,
  HelperText,
  HelperTextItem,
  Toolbar,
  ToolbarContent,
  ToolbarGroup,
  ToolbarItem,
} from '@patternfly/react-core';
import { RocketIcon } from '@patternfly/react-icons';
import React from 'react';

import { DevfileEditor } from '@/components/DevfileEditor';
import DevfileEditorTools from '@/components/DevfileEditorTools';
import styles from '@/pages/DevfileDetails/EditorPanel/index.module.css';
import { DevfileSchema } from '@/services/backend-client/devfileSchemaApi';

export interface Props {
  devfileName: string;
  devfileSchema?: DevfileSchema | undefined;
  editorContent: string;
  isExpanded: boolean;
  readOnly?: boolean;
  isSaved?: boolean;
  saveError?: string | undefined;
  hasValidationError?: boolean;
  onEditorChange?: (value: string) => void;
  onValidation?: (errorMessage: string) => void;
  onEditorFocusChange?: (focused: boolean) => void;
  onSave?: () => void;
  onRefresh?: () => void;
  onCreateWorkspace?: () => void;
  onExpandToggle: () => void;
}

export default class EditorPanel extends React.PureComponent<Props> {
  render(): React.ReactElement {
    const {
      devfileName,
      devfileSchema,
      editorContent,
      isSaved,
      saveError,
      hasValidationError,
      isExpanded,
      readOnly,
      onEditorChange,
      onValidation,
      onEditorFocusChange,
      onSave,
      onRefresh,
      onCreateWorkspace,
      onExpandToggle,
    } = this.props;

    return (
      <div data-testid="editor-panel">
        {!readOnly && saveError && (
          <HelperText className={styles.saveError}>
            <HelperTextItem variant="error">{saveError}</HelperTextItem>
          </HelperText>
        )}
        <DevfileEditorTools
          contentText={editorContent}
          workspaceName={devfileName}
          isExpanded={isExpanded}
          readOnly={readOnly}
          onToggleExpand={onExpandToggle}
        />
        <div className={styles.editorContainer}>
          <DevfileEditor
            id="devfile-editor-id"
            value={editorContent}
            schema={devfileSchema}
            readOnly={readOnly}
            onChange={onEditorChange}
            onValidation={onValidation}
            onFocusChange={onEditorFocusChange}
          />
        </div>
        {!readOnly && (
          <Toolbar hasNoPadding className={styles.toolbar}>
            <ToolbarContent>
              <ToolbarGroup>
                <ToolbarItem>
                  <Button variant="secondary" onClick={onRefresh} data-testid="refresh-button">
                    Refresh
                  </Button>
                </ToolbarItem>
                <ToolbarItem>
                  <Button
                    variant="primary"
                    onClick={onSave}
                    isDisabled={isSaved || hasValidationError}
                    data-testid="save-button"
                  >
                    Save
                  </Button>
                </ToolbarItem>
              </ToolbarGroup>
              <ToolbarGroup align={{ default: 'alignEnd' }}>
                <ToolbarItem>
                  <Button
                    variant="secondary"
                    icon={<RocketIcon />}
                    iconPosition="left"
                    isDisabled={!isSaved || hasValidationError}
                    onClick={onCreateWorkspace}
                    data-testid="create-workspace-button"
                  >
                    Create Workspace
                  </Button>
                </ToolbarItem>
              </ToolbarGroup>
            </ToolbarContent>
          </Toolbar>
        )}
      </div>
    );
  }
}
