/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import {
  Drawer,
  DrawerContent,
  DrawerContentBody,
  DrawerPanelContent,
} from '@patternfly/react-core';
import React from 'react';

import styles from '@/components/LoaderAgentPanel/index.module.css';
import AgentPanel from '@/pages/DevfileDetails/AgentPanel';
import EditorPanel from '@/pages/DevfileDetails/EditorPanel';
import { AgentPodPhase, AgentPodStatus } from '@/store/LocalDevfiles';

export interface Props {
  agentPodStatus: AgentPodStatus | undefined;
  agentTerminalUrl: string | undefined;
  agentInstanceId: string | undefined;
  agentInitCommand: string | undefined;
  agentName: string | undefined;
  agentDescription: string | undefined;
  isDarkTheme: boolean;
  workspaceName: string;
  workspaceNamespace: string;
  workspaceContent: string;
  onStartAgent: () => Promise<void>;
  onStopAgent: () => void;
}

interface State {
  isEditorExpanded: boolean;
  isTerminalExpanded: boolean;
}

export default class LoaderAgentPanel extends React.PureComponent<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      isEditorExpanded: false,
      isTerminalExpanded: false,
    };
  }

  private handleEditorExpandToggle = () => {
    this.setState(prev => ({ isEditorExpanded: !prev.isEditorExpanded }));
  };

  private handleTerminalExpandToggle = () => {
    this.setState(prev => ({ isTerminalExpanded: !prev.isTerminalExpanded }));
  };

  private buildInitCommand(): string | undefined {
    const { agentInitCommand, workspaceName, workspaceNamespace } = this.props;
    if (!agentInitCommand) {
      return undefined;
    }
    const context =
      `'You are helping troubleshoot a DevWorkspace named "${workspaceName}" ` +
      `in namespace "${workspaceNamespace}". ` +
      `It failed to start. Check the DevWorkspace status, pod events, and container logs to diagnose the issue. ` +
      `Suggest fixes to the DevWorkspace spec or devfile.'`;
    return `${agentInitCommand} ${context}`;
  }

  render(): React.ReactElement {
    const {
      agentPodStatus,
      agentTerminalUrl,
      agentInstanceId,
      agentName,
      agentDescription,
      isDarkTheme,
      workspaceName,
      workspaceNamespace,
      workspaceContent,
      onStartAgent,
      onStopAgent,
    } = this.props;
    const { isEditorExpanded, isTerminalExpanded } = this.state;

    const isAgentConnected =
      agentPodStatus?.phase === AgentPodPhase.RUNNING &&
      agentPodStatus?.ready === true &&
      agentTerminalUrl !== undefined;

    let drawerPanelClass = styles.drawerPanel;
    if (isEditorExpanded) {
      drawerPanelClass = `${styles.drawerPanel} ${styles.drawerPanelHidden}`;
    } else if (isAgentConnected && isTerminalExpanded) {
      drawerPanelClass = `${styles.drawerPanel} ${styles.drawerPanelExpanded}`;
    }

    const panelContent = (
      <DrawerPanelContent
        isResizable={isAgentConnected}
        minSize="350px"
        defaultSize={isAgentConnected ? '50%' : '500px'}
        className={drawerPanelClass}
      >
        <AgentPanel
          agentPodStatus={agentPodStatus}
          agentTerminalUrl={agentTerminalUrl}
          agentInstanceId={agentInstanceId}
          agentName={agentName}
          agentDescription={agentDescription}
          agentInitCommand={this.buildInitCommand()}
          namespace={workspaceNamespace}
          devfileName={workspaceName}
          devfileId={workspaceName}
          isDarkTheme={isDarkTheme}
          isTerminalExpanded={isTerminalExpanded}
          onStartAgent={onStartAgent}
          onStopAgent={onStopAgent}
          onTerminalExpandToggle={this.handleTerminalExpandToggle}
        />
      </DrawerPanelContent>
    );

    return (
      <div className={styles.contentSection}>
        <Drawer isExpanded={true} isInline position="end">
          <DrawerContent panelContent={panelContent}>
            <DrawerContentBody>
              {!(isAgentConnected && isTerminalExpanded) && (
                <div className={styles.editorWrapper}>
                  <EditorPanel
                    devfileName={workspaceName}
                    editorContent={workspaceContent}
                    isExpanded={isEditorExpanded}
                    readOnly={true}
                    onExpandToggle={this.handleEditorExpandToggle}
                  />
                </div>
              )}
            </DrawerContentBody>
          </DrawerContent>
        </Drawer>
      </div>
    );
  }
}
