/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import {
  AlertVariant,
  Drawer,
  DrawerContent,
  DrawerContentBody,
  DrawerPanelContent,
} from '@patternfly/react-core';
import { PlayIcon, StopIcon } from '@patternfly/react-icons';
import { dump, load } from 'js-yaml';
import React from 'react';

import styles from '@/components/LoaderAgentPanel/index.module.css';
import { lazyInject } from '@/inversify.config';
import AgentPanel from '@/pages/DevfileDetails/AgentPanel';
import EditorPanel from '@/pages/DevfileDetails/EditorPanel';
import { AppAlerts } from '@/services/alerts/appAlerts';
import { DevfileSchema } from '@/services/backend-client/devfileSchemaApi';
import { DevWorkspaceStatus } from '@/services/helpers/types';
import { AgentPodPhase, AgentPodStatus } from '@/store/LocalDevfiles';

export interface Props {
  agentPodStatus: AgentPodStatus | undefined;
  agentTerminalUrl: string | undefined;
  agentInstanceId: string | undefined;
  agentInitCommand: string | undefined;
  agentName: string | undefined;
  agentDescription: string | undefined;
  isDarkTheme: boolean;
  workspaceName: string;
  workspaceNamespace: string;
  workspaceContent: string;
  workspaceStatus: DevWorkspaceStatus;
  devWorkspaceSchema: DevfileSchema | undefined;
  agentEnabled: boolean;
  onStartAgent: () => Promise<void>;
  onStopAgent: () => void;
  onStartWorkspace: () => void;
  onStopWorkspace: () => void;
  onSaveWorkspace: (content: string) => Promise<void>;
}

interface State {
  isEditorExpanded: boolean;
  isTerminalExpanded: boolean;
  editedContent: string;
  isSaved: boolean;
  hasValidationError: boolean;
}

export default class LoaderAgentPanel extends React.PureComponent<Props, State> {
  @lazyInject(AppAlerts)
  private readonly appAlerts: AppAlerts;

  private cachedSchema: DevfileSchema | undefined;
  private cachedSchemaInputs: string | undefined;

  constructor(props: Props) {
    super(props);
    this.state = {
      isEditorExpanded: false,
      isTerminalExpanded: false,
      editedContent: props.workspaceContent,
      isSaved: true,
      hasValidationError: false,
    };
  }

  componentDidUpdate(prevProps: Props): void {
    if (prevProps.workspaceContent !== this.props.workspaceContent && this.state.isSaved) {
      if (!this.isContentEqual(this.state.editedContent, this.props.workspaceContent)) {
        this.setState({
          editedContent: this.props.workspaceContent,
          isSaved: true,
        });
      }
    }
  }

  private isContentEqual(a: string, b: string): boolean {
    if (a === b) return true;
    try {
      const parsedA = load(a);
      const parsedB = load(b);
      if (parsedA === undefined || parsedB === undefined) return false;
      return JSON.stringify(parsedA) === JSON.stringify(parsedB);
    } catch {
      return a.trim() === b.trim();
    }
  }

  private handleEditorExpandToggle = () => {
    this.setState(prev => ({ isEditorExpanded: !prev.isEditorExpanded }));
  };

  private handleTerminalExpandToggle = () => {
    this.setState(prev => ({ isTerminalExpanded: !prev.isTerminalExpanded }));
  };

  private handleEditorChange = (value: string): void => {
    this.setState({ editedContent: value, isSaved: false });
  };

  private handleValidation = (errorMessage: string): void => {
    this.setState({ hasValidationError: errorMessage.length > 0 });
  };

  private handleSave = async (): Promise<void> => {
    const { editedContent } = this.state;
    const { workspaceName, workspaceNamespace } = this.props;
    try {
      const parsed = load(editedContent) as Record<string, unknown>;
      const metadata = (parsed.metadata || {}) as Record<string, unknown>;
      metadata.name = workspaceName;
      metadata.namespace = workspaceNamespace;
      parsed.metadata = metadata;

      const correctedContent = dump(parsed, { lineWidth: -1 });
      await this.props.onSaveWorkspace(correctedContent);
      this.setState({ isSaved: true });
      this.appAlerts.showAlert({
        key: 'workspace-save-success',
        title: 'DevWorkspace has been updated',
        variant: AlertVariant.success,
      });
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Failed to save DevWorkspace';
      this.appAlerts.showAlert({
        key: 'workspace-save-error',
        title: message,
        variant: AlertVariant.danger,
      });
    }
  };

  private handleRefresh = (): void => {
    this.setState({
      editedContent: this.props.workspaceContent,
      isSaved: true,
      hasValidationError: false,
    });
  };

  private buildModifiedSchema(): DevfileSchema | undefined {
    const { devWorkspaceSchema, workspaceName, workspaceNamespace } = this.props;
    if (!devWorkspaceSchema) {
      return undefined;
    }
    const cacheKey = `${workspaceName}:${workspaceNamespace}`;
    if (this.cachedSchema && this.cachedSchemaInputs === cacheKey) {
      return this.cachedSchema;
    }
    const schema = JSON.parse(JSON.stringify(devWorkspaceSchema)) as DevfileSchema;
    const metadataProps = schema?.properties?.metadata as
      | { properties?: Record<string, Record<string, unknown>> }
      | undefined;
    if (metadataProps?.properties) {
      if (metadataProps.properties.name) {
        metadataProps.properties.name = { ...metadataProps.properties.name, const: workspaceName };
      }
      if (metadataProps.properties.namespace) {
        metadataProps.properties.namespace = {
          ...metadataProps.properties.namespace,
          const: workspaceNamespace,
        };
      }
    }
    this.cachedSchema = schema;
    this.cachedSchemaInputs = cacheKey;
    return schema;
  }

  private buildInitCommand(): string | undefined {
    const { agentInitCommand, workspaceName, workspaceNamespace } = this.props;
    if (!agentInitCommand) {
      return undefined;
    }
    const context =
      `'You are helping troubleshoot a DevWorkspace named "${workspaceName}" ` +
      `in namespace "${workspaceNamespace}". ` +
      `It failed to start. Check the DevWorkspace status, pod events, and container logs to diagnose the issue. ` +
      `Suggest fixes to the DevWorkspace spec or devfile.'`;
    return `${agentInitCommand} ${context}`;
  }

  render(): React.ReactElement {
    const {
      agentPodStatus,
      agentTerminalUrl,
      agentInstanceId,
      agentName,
      agentDescription,
      isDarkTheme,
      workspaceName,
      workspaceNamespace,
      workspaceStatus,
      agentEnabled,
      onStartAgent,
      onStopAgent,
      onStartWorkspace,
      onStopWorkspace,
    } = this.props;
    const { isEditorExpanded, isTerminalExpanded, editedContent, isSaved, hasValidationError } =
      this.state;

    const isAgentConnected =
      agentPodStatus?.phase === AgentPodPhase.RUNNING &&
      agentPodStatus?.ready === true &&
      agentTerminalUrl !== undefined;

    const isEditable =
      workspaceStatus === DevWorkspaceStatus.STOPPED ||
      workspaceStatus === DevWorkspaceStatus.FAILED;

    const isWorkspaceActive =
      workspaceStatus === DevWorkspaceStatus.STARTING ||
      workspaceStatus === DevWorkspaceStatus.RUNNING;

    const actionButtonLabel = isWorkspaceActive ? 'Stop DevWorkspace' : 'Start DevWorkspace';
    const actionButtonIcon = isWorkspaceActive ? <StopIcon /> : <PlayIcon />;
    const handleAction = isWorkspaceActive ? onStopWorkspace : onStartWorkspace;
    const actionButtonDisabled = !isWorkspaceActive && hasValidationError;
    const actionButtonDanger = isWorkspaceActive;

    let drawerPanelClass = styles.drawerPanel;
    if (isEditorExpanded || !agentEnabled) {
      drawerPanelClass = `${styles.drawerPanel} ${styles.drawerPanelHidden}`;
    } else if (isAgentConnected && isTerminalExpanded) {
      drawerPanelClass = `${styles.drawerPanel} ${styles.drawerPanelExpanded}`;
    }

    const panelContent = agentEnabled ? (
      <DrawerPanelContent
        isResizable={isAgentConnected}
        minSize="350px"
        defaultSize={isAgentConnected ? '50%' : '500px'}
        className={drawerPanelClass}
      >
        <AgentPanel
          agentPodStatus={agentPodStatus}
          agentTerminalUrl={agentTerminalUrl}
          agentInstanceId={agentInstanceId}
          agentName={agentName}
          agentDescription={agentDescription}
          agentInitCommand={this.buildInitCommand()}
          emptyStateDescription="Launch an AI agent to help diagnose and fix issues with your DevWorkspace."
          namespace={workspaceNamespace}
          devfileName={workspaceName}
          devfileId={workspaceName}
          isDarkTheme={isDarkTheme}
          isTerminalExpanded={isTerminalExpanded}
          onStartAgent={onStartAgent}
          onStopAgent={onStopAgent}
          onTerminalExpandToggle={this.handleTerminalExpandToggle}
        />
      </DrawerPanelContent>
    ) : undefined;

    const modifiedSchema = this.buildModifiedSchema();

    const editorPanel = (
      <div className={styles.editorWrapper}>
        <EditorPanel
          devfileName={workspaceName}
          editorTitle={`DevWorkspace: ${workspaceName}`}
          devfileSchema={modifiedSchema}
          editorContent={editedContent}
          isExpanded={isEditorExpanded}
          readOnly={!isEditable}
          toolsReadOnly={true}
          alwaysShowToolbar={true}
          isSaved={isSaved}
          hasValidationError={hasValidationError}
          onEditorChange={this.handleEditorChange}
          onValidation={this.handleValidation}
          onSave={this.handleSave}
          onRefresh={this.handleRefresh}
          onExpandToggle={this.handleEditorExpandToggle}
          actionButtonLabel={actionButtonLabel}
          actionButtonIcon={actionButtonIcon}
          actionButtonDisabled={actionButtonDisabled}
          actionButtonDanger={actionButtonDanger}
          onAction={handleAction}
        />
      </div>
    );

    if (!agentEnabled) {
      return <div className={styles.contentSection}>{editorPanel}</div>;
    }

    return (
      <div className={styles.contentSection}>
        <Drawer isExpanded={true} isInline position="end">
          <DrawerContent panelContent={panelContent}>
            <DrawerContentBody>
              {!(isAgentConnected && isTerminalExpanded) && editorPanel}
            </DrawerContentBody>
          </DrawerContent>
        </Drawer>
      </div>
    );
  }
}
