/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import {
  Alert,
  Button,
  Content,
  ContentVariants,
  EmptyState,
  EmptyStateBody,
  EmptyStateVariant,
  Flex,
  FlexItem,
  Icon,
  Label,
  Spinner,
  Stack,
  StackItem,
  Tooltip,
} from '@patternfly/react-core';
import { InProgressIcon, ResourcesFullIcon } from '@patternfly/react-icons';
import React from 'react';

import AgentPodEvents from '@/components/AgentPodEvents';
import AgentTerminal from '@/components/AgentTerminal';
import styles from '@/components/LoaderAgentPanel/index.module.css';
import { StoppedIcon } from '@/components/Workspace/Status/StoppedIcon';
import { AgentPodStatus } from '@/store/LocalDevfiles';

export interface Props {
  agentPodStatus: AgentPodStatus | undefined;
  agentTerminalUrl: string | undefined;
  agentInstanceId: string | undefined;
  agentInitCommand: string | undefined;
  agentName: string | undefined;
  agentDescription: string | undefined;
  isDarkTheme: boolean;
  workspaceName: string;
  workspaceNamespace: string;
  onStartAgent: () => void;
  onStopAgent: () => void;
}

interface State {
  agentError: string | undefined;
}

export default class LoaderAgentPanel extends React.PureComponent<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      agentError: undefined,
    };
  }

  private handleStartAgent = async () => {
    this.setState({ agentError: undefined });
    try {
      await this.props.onStartAgent();
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : String(e);
      this.setState({ agentError: message });
    }
  };

  private buildInitContext(): string {
    const { workspaceName, workspaceNamespace } = this.props;
    return (
      `'You are helping troubleshoot a DevWorkspace named "${workspaceName}" ` +
      `in namespace "${workspaceNamespace}". ` +
      `It failed to start. Check the DevWorkspace status, pod events, and container logs to diagnose the issue. ` +
      `Suggest fixes to the DevWorkspace spec or devfile.'`
    );
  }

  private renderStartButton(): React.ReactElement {
    return (
      <Button variant="primary" onClick={this.handleStartAgent}>
        Start Agent
      </Button>
    );
  }

  private renderStopButton(): React.ReactElement {
    return (
      <Button variant="secondary" isDanger onClick={this.props.onStopAgent}>
        Stop
      </Button>
    );
  }

  private renderStatusLabel(phase: string, ready: boolean): React.ReactElement {
    const isRunning = phase === 'Running' && ready;
    const isPending = phase === 'Pending' || (phase === 'Running' && !ready);
    const isFailed = phase === 'Failed' || phase === 'Succeeded' || phase === 'Unknown';

    let color: 'green' | 'blue' | 'orange' | 'grey';
    let icon: React.ReactElement;
    let text: string;

    if (isRunning) {
      color = 'green';
      icon = (
        <Icon status="success" isInline>
          <ResourcesFullIcon />
        </Icon>
      );
      text = 'Running';
    } else if (isPending) {
      color = 'blue';
      icon = (
        <Icon status="info" isInline>
          <InProgressIcon className={styles.rotate} />
        </Icon>
      );
      text = 'Starting';
    } else if (isFailed) {
      color = 'orange';
      icon = (
        <Icon isInline color="var(--pf-t--global--text--color--subtle)">
          <StoppedIcon />
        </Icon>
      );
      text = 'Failed';
    } else {
      color = 'grey';
      icon = (
        <Icon isInline color="var(--pf-t--global--text--color--subtle)">
          <StoppedIcon />
        </Icon>
      );
      text = phase;
    }

    return (
      <Label color={color} icon={icon} className={styles.statusLabel}>
        {text}
      </Label>
    );
  }

  render(): React.ReactElement {
    const { agentPodStatus, agentTerminalUrl, isDarkTheme, agentInitCommand } = this.props;
    const { agentError } = this.state;

    if (agentPodStatus) {
      const phase = agentPodStatus.phase;
      const isRunning = phase === 'Running' && agentPodStatus.ready;
      const isFailed = phase === 'Failed' || phase === 'Succeeded' || phase === 'Unknown';
      const isPending = phase === 'Pending';

      if (isRunning && agentTerminalUrl) {
        const { agentName, agentDescription } = this.props;
        const agentDisplayId = this.props.agentInstanceId || agentPodStatus.agentId;
        const initCmd = agentInitCommand
          ? `${agentInitCommand} ${this.buildInitContext()}`
          : undefined;
        const tooltipContent = (
          <div>
            <div>
              <strong>{agentName || agentDisplayId}</strong>
            </div>
            {agentDescription && <div>{agentDescription}</div>}
          </div>
        );
        return (
          <div className={styles.terminalPanel}>
            <div className={styles.terminalToolbar}>
              <Tooltip content={tooltipContent}>
                <span className={styles.agentIdLabel}>{agentDisplayId}</span>
              </Tooltip>
              {this.renderStatusLabel(phase, agentPodStatus.ready)}
            </div>
            <AgentTerminal
              terminalUrl={agentTerminalUrl}
              namespace={this.props.workspaceNamespace}
              devfileName={this.props.workspaceName}
              isDarkTheme={isDarkTheme}
              initCommand={initCmd}
            />
            <div className={styles.terminalBottomToolbar}>{this.renderStopButton()}</div>
          </div>
        );
      }

      if (isFailed) {
        return (
          <div className={styles.eventsPanel}>
            <Stack hasGutter>
              <StackItem>
                <Alert
                  variant="danger"
                  isInline
                  title="Agent failed"
                  style={{ marginBottom: '8px' }}
                >
                  Agent pod status: {phase}
                </Alert>
              </StackItem>
              <StackItem>{this.renderStartButton()}</StackItem>
              <StackItem>
                <AgentPodEvents podName={agentPodStatus.name} />
              </StackItem>
            </Stack>
          </div>
        );
      }

      if (isPending || (phase === 'Running' && !agentPodStatus.ready)) {
        return (
          <div className={styles.eventsPanel}>
            <Stack hasGutter>
              <StackItem>
                <Flex alignItems={{ default: 'alignItemsCenter' }}>
                  <FlexItem>
                    <Spinner size="md" />
                  </FlexItem>
                  <FlexItem>
                    <Content component={ContentVariants.p}>Starting agent...</Content>
                  </FlexItem>
                  <FlexItem align={{ default: 'alignRight' }}>{this.renderStopButton()}</FlexItem>
                </Flex>
              </StackItem>
              <StackItem>
                <AgentPodEvents podName={agentPodStatus.name} />
              </StackItem>
            </Stack>
          </div>
        );
      }
    }

    return (
      <div className={styles.emptyState}>
        <div>
          {agentError && (
            <Alert
              variant="danger"
              isInline
              title="Agent error"
              style={{ marginBottom: '16px', maxHeight: '200px', overflowX: 'auto' }}
            >
              {agentError}
            </Alert>
          )}
          <EmptyState headingLevel="h3" titleText="AI Agent" variant={EmptyStateVariant.sm}>
            <EmptyStateBody>
              Start an AI agent to help troubleshoot your workspace startup failure.
            </EmptyStateBody>
            <div className={styles.spacer16} />
            {this.renderStartButton()}
          </EmptyState>
        </div>
      </div>
    );
  }
}
