/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { AlertVariant } from '@patternfly/react-core';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import React from 'react';

import LoaderAgentPanel, { Props } from '@/components/LoaderAgentPanel';
import { container } from '@/inversify.config';
import { AppAlerts } from '@/services/alerts/appAlerts';
import { DevfileSchema } from '@/services/backend-client/devfileSchemaApi';
import { AlertItem, DevWorkspaceStatus } from '@/services/helpers/types';
import { AgentPodPhase, AgentPodStatus } from '@/store/LocalDevfiles';

jest.mock('@/pages/DevfileDetails/AgentPanel', () => {
  return function MockAgentPanel(props: {
    agentPodStatus: AgentPodStatus | undefined;
    agentTerminalUrl: string | undefined;
    agentInstanceId: string | undefined;
    agentName: string | undefined;
    agentDescription: string | undefined;
    agentInitCommand: string | undefined;
    emptyStateDescription: string;
    namespace: string;
    devfileName: string;
    devfileId: string;
    isDarkTheme: boolean;
    isTerminalExpanded: boolean;
    onStartAgent: () => Promise<void>;
    onStopAgent: () => void;
    onTerminalExpandToggle: () => void;
  }) {
    return (
      <div data-testid="agent-panel">
        <span data-testid="agent-init-command">{props.agentInitCommand}</span>
        <span data-testid="agent-namespace">{props.namespace}</span>
        <span data-testid="agent-devfile-name">{props.devfileName}</span>
        <span data-testid="agent-is-terminal-expanded">{String(props.isTerminalExpanded)}</span>
        <button data-testid="agent-start" onClick={props.onStartAgent}>
          Start
        </button>
        <button data-testid="agent-stop" onClick={props.onStopAgent}>
          Stop
        </button>
        <button data-testid="agent-toggle-terminal" onClick={props.onTerminalExpandToggle}>
          Toggle Terminal
        </button>
      </div>
    );
  };
});

jest.mock('@/pages/DevfileDetails/EditorPanel', () => {
  return function MockEditorPanel(props: {
    devfileName: string;
    editorTitle?: string;
    devfileSchema?: DevfileSchema;
    editorContent: string;
    isExpanded: boolean;
    readOnly?: boolean;
    isSaved?: boolean;
    hasValidationError?: boolean;
    onEditorChange?: (value: string) => void;
    onValidation?: (errorMessage: string) => void;
    onSave?: () => void;
    onRefresh?: () => void;
    onExpandToggle: () => void;
    actionButtonLabel?: string;
    actionButtonIcon?: React.ReactNode;
    actionButtonDisabled?: boolean;
    actionButtonDanger?: boolean;
    onAction?: () => void;
  }) {
    return (
      <div data-testid="editor-panel">
        <span data-testid="editor-content">{props.editorContent}</span>
        <span data-testid="editor-title">{props.editorTitle}</span>
        <span data-testid="editor-read-only">{String(props.readOnly)}</span>
        <span data-testid="editor-is-saved">{String(props.isSaved)}</span>
        <span data-testid="editor-action-label">{props.actionButtonLabel}</span>
        <span data-testid="editor-action-disabled">{String(props.actionButtonDisabled)}</span>
        <span data-testid="editor-action-danger">{String(props.actionButtonDanger)}</span>
        <button
          data-testid="editor-change"
          onClick={() => props.onEditorChange?.('changed: true\n')}
        >
          Change Editor
        </button>
        <button
          data-testid="editor-validate-error"
          onClick={() => props.onValidation?.('validation error')}
        >
          Validate Error
        </button>
        <button data-testid="editor-validate-ok" onClick={() => props.onValidation?.('')}>
          Validate OK
        </button>
        <button data-testid="editor-save" onClick={props.onSave}>
          Save
        </button>
        <button data-testid="editor-refresh" onClick={props.onRefresh}>
          Refresh
        </button>
        <button data-testid="editor-expand-toggle" onClick={props.onExpandToggle}>
          Toggle Expand
        </button>
        <button data-testid="editor-action" onClick={props.onAction}>
          Action
        </button>
      </div>
    );
  };
});

const mockOnStartAgent = jest.fn();
const mockOnStopAgent = jest.fn();
const mockOnStartWorkspace = jest.fn();
const mockOnStopWorkspace = jest.fn();
const mockOnSaveWorkspace = jest.fn();

const workspaceContent =
  'apiVersion: workspace.devfile.io/v1alpha2\nkind: DevWorkspace\nmetadata:\n  name: test-workspace\n  namespace: test-ns\nspec:\n  started: false\n';

const defaultProps: Props = {
  agentPodStatus: undefined,
  agentTerminalUrl: undefined,
  agentInstanceId: undefined,
  agentInitCommand: undefined,
  agentName: 'Test Agent',
  agentDescription: 'AI Agent description',
  isDarkTheme: false,
  workspaceName: 'test-workspace',
  workspaceNamespace: 'test-ns',
  workspaceContent,
  workspaceStatus: DevWorkspaceStatus.STOPPED,
  devWorkspaceSchema: undefined,
  agentEnabled: true,
  onStartAgent: mockOnStartAgent,
  onStopAgent: mockOnStopAgent,
  onStartWorkspace: mockOnStartWorkspace,
  onStopWorkspace: mockOnStopWorkspace,
  onSaveWorkspace: mockOnSaveWorkspace,
};

function renderComponent(overrides?: Partial<Props>) {
  return render(<LoaderAgentPanel {...defaultProps} {...overrides} />);
}

describe('LoaderAgentPanel', () => {
  const mockShowAlert = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
    mockOnSaveWorkspace.mockResolvedValue(undefined);

    class MockAppAlerts extends AppAlerts {
      showAlert(alert: AlertItem): void {
        mockShowAlert(alert);
      }
    }

    container.snapshot();
    container.rebind(AppAlerts).to(MockAppAlerts).inSingletonScope();
  });

  afterEach(() => {
    container.restore();
  });

  describe('basic rendering', () => {
    it('should render the editor panel when agentEnabled is true', () => {
      renderComponent();
      expect(screen.getByTestId('editor-panel')).toBeDefined();
    });

    it('should render the agent panel when agentEnabled is true', () => {
      renderComponent();
      expect(screen.getByTestId('agent-panel')).toBeDefined();
    });

    it('should not render the agent panel when agentEnabled is false', () => {
      renderComponent({ agentEnabled: false });
      expect(screen.queryByTestId('agent-panel')).toBeNull();
    });

    it('should render editor panel even when agentEnabled is false', () => {
      renderComponent({ agentEnabled: false });
      expect(screen.getByTestId('editor-panel')).toBeDefined();
    });
  });

  describe('editor title', () => {
    it('should pass the workspace name in the editor title', () => {
      renderComponent();
      expect(screen.getByTestId('editor-title')).toHaveTextContent('DevWorkspace: test-workspace');
    });
  });

  describe('workspace status - stopped', () => {
    it('should show "Start DevWorkspace" action when workspace is stopped', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STOPPED });
      expect(screen.getByTestId('editor-action-label')).toHaveTextContent('Start DevWorkspace');
    });

    it('should have editor in editable mode when workspace is stopped', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STOPPED });
      expect(screen.getByTestId('editor-read-only')).toHaveTextContent('false');
    });

    it('should not be danger action when workspace is stopped', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STOPPED });
      expect(screen.getByTestId('editor-action-danger')).toHaveTextContent('false');
    });

    it('should call onStartWorkspace when action button is clicked', async () => {
      const user = userEvent.setup();
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STOPPED });

      await user.click(screen.getByTestId('editor-action'));
      expect(mockOnStartWorkspace).toHaveBeenCalledTimes(1);
    });
  });

  describe('workspace status - running', () => {
    it('should show "Stop DevWorkspace" action when workspace is running', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.RUNNING });
      expect(screen.getByTestId('editor-action-label')).toHaveTextContent('Stop DevWorkspace');
    });

    it('should have editor in read-only mode when workspace is running', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.RUNNING });
      expect(screen.getByTestId('editor-read-only')).toHaveTextContent('true');
    });

    it('should be a danger action when workspace is running', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.RUNNING });
      expect(screen.getByTestId('editor-action-danger')).toHaveTextContent('true');
    });

    it('should call onStopWorkspace when action button is clicked', async () => {
      const user = userEvent.setup();
      renderComponent({ workspaceStatus: DevWorkspaceStatus.RUNNING });

      await user.click(screen.getByTestId('editor-action'));
      expect(mockOnStopWorkspace).toHaveBeenCalledTimes(1);
    });
  });

  describe('workspace status - starting', () => {
    it('should show "Stop DevWorkspace" action when workspace is starting', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STARTING });
      expect(screen.getByTestId('editor-action-label')).toHaveTextContent('Stop DevWorkspace');
    });

    it('should have editor in read-only mode when workspace is starting', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STARTING });
      expect(screen.getByTestId('editor-read-only')).toHaveTextContent('true');
    });
  });

  describe('workspace status - failed', () => {
    it('should show "Start DevWorkspace" action when workspace has failed', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.FAILED });
      expect(screen.getByTestId('editor-action-label')).toHaveTextContent('Start DevWorkspace');
    });

    it('should have editor in editable mode when workspace has failed', () => {
      renderComponent({ workspaceStatus: DevWorkspaceStatus.FAILED });
      expect(screen.getByTestId('editor-read-only')).toHaveTextContent('false');
    });
  });

  describe('editor interactions', () => {
    it('should update isSaved to false when editor content changes', async () => {
      const user = userEvent.setup();
      renderComponent();

      expect(screen.getByTestId('editor-is-saved')).toHaveTextContent('true');

      await user.click(screen.getByTestId('editor-change'));

      expect(screen.getByTestId('editor-is-saved')).toHaveTextContent('false');
    });

    it('should refresh content from props when refresh is clicked', async () => {
      const user = userEvent.setup();
      renderComponent();

      await user.click(screen.getByTestId('editor-change'));
      expect(screen.getByTestId('editor-is-saved')).toHaveTextContent('false');

      await user.click(screen.getByTestId('editor-refresh'));
      expect(screen.getByTestId('editor-is-saved')).toHaveTextContent('true');
      expect(screen.getByTestId('editor-content').textContent).toContain('test-workspace');
      expect(screen.getByTestId('editor-content').textContent).toContain('started: false');
    });

    it('should disable action button when there is a validation error and workspace is not active', async () => {
      const user = userEvent.setup();
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STOPPED });

      await user.click(screen.getByTestId('editor-validate-error'));

      expect(screen.getByTestId('editor-action-disabled')).toHaveTextContent('true');
    });

    it('should not disable action button when workspace is active even with validation error', async () => {
      const user = userEvent.setup();
      renderComponent({ workspaceStatus: DevWorkspaceStatus.RUNNING });

      await user.click(screen.getByTestId('editor-validate-error'));

      expect(screen.getByTestId('editor-action-disabled')).toHaveTextContent('false');
    });

    it('should re-enable action button when validation error is cleared', async () => {
      const user = userEvent.setup();
      renderComponent({ workspaceStatus: DevWorkspaceStatus.STOPPED });

      await user.click(screen.getByTestId('editor-validate-error'));
      expect(screen.getByTestId('editor-action-disabled')).toHaveTextContent('true');

      await user.click(screen.getByTestId('editor-validate-ok'));
      expect(screen.getByTestId('editor-action-disabled')).toHaveTextContent('false');
    });
  });

  describe('save workspace', () => {
    it('should save and show success alert', async () => {
      const user = userEvent.setup();
      renderComponent();

      await user.click(screen.getByTestId('editor-change'));
      await user.click(screen.getByTestId('editor-save'));

      await waitFor(() => {
        expect(mockOnSaveWorkspace).toHaveBeenCalledTimes(1);
      });

      expect(mockShowAlert).toHaveBeenCalledWith(
        expect.objectContaining({
          key: 'workspace-save-success',
          title: 'DevWorkspace has been updated',
          variant: AlertVariant.success,
        }),
      );
    });

    it('should preserve metadata name and namespace on save', async () => {
      const user = userEvent.setup();
      renderComponent();

      await user.click(screen.getByTestId('editor-save'));

      await waitFor(() => {
        expect(mockOnSaveWorkspace).toHaveBeenCalledTimes(1);
      });

      const savedContent = mockOnSaveWorkspace.mock.calls[0][0] as string;
      expect(savedContent).toContain('name: test-workspace');
      expect(savedContent).toContain('namespace: test-ns');
    });

    it('should show error alert when save fails', async () => {
      mockOnSaveWorkspace.mockRejectedValue(new Error('Save failed'));

      const user = userEvent.setup();
      renderComponent();

      await user.click(screen.getByTestId('editor-save'));

      await waitFor(() => {
        expect(mockShowAlert).toHaveBeenCalledWith(
          expect.objectContaining({
            key: 'workspace-save-error',
            title: 'Save failed',
            variant: AlertVariant.danger,
          }),
        );
      });
    });

    it('should show generic error message for non-Error throws on save', async () => {
      mockOnSaveWorkspace.mockRejectedValue('unexpected');

      const user = userEvent.setup();
      renderComponent();

      await user.click(screen.getByTestId('editor-save'));

      await waitFor(() => {
        expect(mockShowAlert).toHaveBeenCalledWith(
          expect.objectContaining({
            key: 'workspace-save-error',
            title: 'Failed to save DevWorkspace',
            variant: AlertVariant.danger,
          }),
        );
      });
    });

    it('should set isSaved to true after successful save', async () => {
      const user = userEvent.setup();
      renderComponent();

      await user.click(screen.getByTestId('editor-change'));
      expect(screen.getByTestId('editor-is-saved')).toHaveTextContent('false');

      await user.click(screen.getByTestId('editor-save'));

      await waitFor(() => {
        expect(screen.getByTestId('editor-is-saved')).toHaveTextContent('true');
      });
    });
  });

  describe('agent panel integration', () => {
    it('should pass the workspace namespace to the agent panel', () => {
      renderComponent();
      expect(screen.getByTestId('agent-namespace')).toHaveTextContent('test-ns');
    });

    it('should pass the workspace name to the agent panel', () => {
      renderComponent();
      expect(screen.getByTestId('agent-devfile-name')).toHaveTextContent('test-workspace');
    });

    it('should toggle terminal expansion', async () => {
      const user = userEvent.setup();
      renderComponent();

      expect(screen.getByTestId('agent-is-terminal-expanded')).toHaveTextContent('false');

      await user.click(screen.getByTestId('agent-toggle-terminal'));

      expect(screen.getByTestId('agent-is-terminal-expanded')).toHaveTextContent('true');
    });
  });

  describe('buildInitCommand', () => {
    it('should not pass agentInitCommand when none is provided', () => {
      renderComponent({ agentInitCommand: undefined });
      expect(screen.getByTestId('agent-init-command')).toHaveTextContent('');
    });

    it('should build init command with workspace context', () => {
      renderComponent({ agentInitCommand: 'claude --chat' });
      const initCommand = screen.getByTestId('agent-init-command').textContent;
      expect(initCommand).toContain('claude --chat');
      expect(initCommand).toContain('test-workspace');
      expect(initCommand).toContain('test-ns');
    });
  });

  describe('buildModifiedSchema', () => {
    it('should pass undefined schema when devWorkspaceSchema is not provided', () => {
      renderComponent({ devWorkspaceSchema: undefined });
      expect(screen.getByTestId('editor-panel')).toBeDefined();
    });

    it('should modify schema metadata with workspace name and namespace', () => {
      const schema: DevfileSchema = {
        properties: {
          metadata: {
            properties: {
              name: { type: 'string' },
              namespace: { type: 'string' },
            },
          },
        },
      };
      renderComponent({ devWorkspaceSchema: schema });
      expect(screen.getByTestId('editor-panel')).toBeDefined();
    });
  });

  describe('agent connected and terminal expanded', () => {
    const connectedAgentProps: Partial<Props> = {
      agentPodStatus: {
        agentId: 'agent-123',
        name: 'agent-pod-123',
        phase: AgentPodPhase.RUNNING,
        ready: true,
        serviceUrl: 'http://agent-service:8080',
      },
      agentTerminalUrl: 'ws://terminal-url',
      agentEnabled: true,
    };

    it('should hide editor when agent is connected and terminal is expanded', async () => {
      const user = userEvent.setup();
      renderComponent(connectedAgentProps);

      await user.click(screen.getByTestId('agent-toggle-terminal'));

      expect(screen.queryByTestId('editor-panel')).toBeNull();
    });

    it('should show editor when agent is connected but terminal is not expanded', () => {
      renderComponent(connectedAgentProps);
      expect(screen.getByTestId('editor-panel')).toBeDefined();
    });
  });

  describe('componentDidUpdate', () => {
    it('should update editedContent when workspaceContent prop changes and content is saved', () => {
      const newContent =
        'apiVersion: workspace.devfile.io/v1alpha2\nkind: DevWorkspace\nmetadata:\n  name: updated\n  namespace: test-ns\nspec:\n  started: true\n';

      const { rerender } = render(<LoaderAgentPanel {...defaultProps} />);

      rerender(<LoaderAgentPanel {...defaultProps} workspaceContent={newContent} />);

      expect(screen.getByTestId('editor-content').textContent).toContain('name: updated');
      expect(screen.getByTestId('editor-content').textContent).toContain('started: true');
    });

    it('should not update editedContent when content is unsaved', async () => {
      const user = userEvent.setup();
      const { rerender } = render(<LoaderAgentPanel {...defaultProps} />);

      await user.click(screen.getByTestId('editor-change'));

      const newContent = 'apiVersion: workspace.devfile.io/v1alpha2\nnewstuff: true\n';
      rerender(<LoaderAgentPanel {...defaultProps} workspaceContent={newContent} />);

      expect(screen.getByTestId('editor-content')).toHaveTextContent('changed: true');
    });
  });

  describe('editor expand toggle', () => {
    it('should toggle editor expansion', async () => {
      const user = userEvent.setup();
      renderComponent();

      expect(screen.getByTestId('agent-panel')).toBeDefined();

      await user.click(screen.getByTestId('editor-expand-toggle'));

      // After editor is expanded, the agent panel should still exist in the DOM
      // but the drawer panel should have the hidden class
      expect(screen.getByTestId('editor-panel')).toBeDefined();
    });
  });
});
