/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import common, { api } from '@eclipse-che/common';
import { AxiosError } from 'axios';
import mockAxios from 'axios';

import { fetchAiAgentRegistry } from '@/services/backend-client/aiAgentRegistryApi';

const mockGet = mockAxios.get as jest.Mock;

const mockRegistry: api.IAiAgentRegistry = {
  agents: [
    {
      id: 'test-agent',
      name: 'Test Agent',
      publisher: 'test-publisher',
      description: 'A test AI agent',
      icon: 'https://example.com/icon.png',
      docsUrl: 'https://example.com/docs',
      image: 'quay.io/test/agent:latest',
      tag: 'latest',
      memoryLimit: '512Mi',
      cpuLimit: '500m',
      terminalPort: 8080,
      env: [{ name: 'KEY', value: 'value' }],
      initCommand: 'claude --init',
    },
  ],
  defaultAgentId: 'test-agent',
};

describe('fetchAiAgentRegistry', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should fetch the AI agent registry successfully', async () => {
    mockGet.mockResolvedValueOnce({ data: mockRegistry });

    const result = await fetchAiAgentRegistry();

    expect(mockGet).toHaveBeenCalledWith('/dashboard/api/ai-agent-registry');
    expect(result).toEqual(mockRegistry);
  });

  it('should return data with multiple agents', async () => {
    const multiAgentRegistry: api.IAiAgentRegistry = {
      agents: [
        ...mockRegistry.agents,
        {
          id: 'second-agent',
          name: 'Second Agent',
          publisher: 'test-publisher',
          description: 'Another agent',
          icon: 'https://example.com/icon2.png',
          docsUrl: 'https://example.com/docs2',
          image: 'quay.io/test/agent2:latest',
          tag: 'v2',
          memoryLimit: '1Gi',
          cpuLimit: '1',
          terminalPort: 9090,
          env: [],
          initCommand: 'agent --start',
        },
      ],
      defaultAgentId: 'test-agent',
    };
    mockGet.mockResolvedValueOnce({ data: multiAgentRegistry });

    const result = await fetchAiAgentRegistry();

    expect(result.agents).toHaveLength(2);
    expect(result.defaultAgentId).toBe('test-agent');
  });

  it('should throw an error when the request fails', async () => {
    mockGet.mockRejectedValueOnce({
      code: '500',
      message: 'Internal Server Error',
    } as AxiosError);

    let errorMessage: string | undefined;
    try {
      await fetchAiAgentRegistry();
    } catch (err) {
      errorMessage = common.helpers.errors.getMessage(err);
    }

    expect(errorMessage).toBe('Failed to fetch AI agent registry. Internal Server Error');
  });

  it('should throw an error with a network error message', async () => {
    mockGet.mockRejectedValueOnce({
      code: 'ERR_NETWORK',
      message: 'Network Error',
    } as AxiosError);

    await expect(fetchAiAgentRegistry()).rejects.toThrow(
      'Failed to fetch AI agent registry. Network Error',
    );
  });
});
