/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import React from 'react';

type Props = {
  memoryLimit: number;
  cpuLimit: number;
  onMemoryLimitChange: (value: number) => void;
  onCpuLimitChange: (value: number) => void;
};

export const ResourceLimitsPanel: React.FC<Props> = ({
  memoryLimit,
  cpuLimit,
  onMemoryLimitChange,
  onCpuLimitChange,
}) => {
  return (
    <div data-testid="resource-limits-panel">
      <span data-testid="resource-limits-memory">{memoryLimit}</span>
      <span data-testid="resource-limits-cpu">{cpuLimit}</span>
      <button
        data-testid="resource-limits-set-memory"
        onClick={() => onMemoryLimitChange(4294967296)}
      >
        Set Memory
      </button>
      <button data-testid="resource-limits-set-cpu" onClick={() => onCpuLimitChange(2)}>
        Set CPU
      </button>
    </div>
  );
};
