/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6

import { BackupValidationResult } from '@eclipse-che/common';
import { Form, ValidatedOptions } from '@patternfly/react-core';
import React, { useEffect, useRef, useState } from 'react';

import { ImageUrlField } from '@/pages/RestoreFromBackup/ExternalRegistryForm/ImageUrlField';
import { WorkspaceNameField } from '@/pages/RestoreFromBackup/ExternalRegistryForm/WorkspaceNameField';
import {
  sanitizeImageUrl,
  validateImageUrlFormat,
  ValidationState,
} from '@/pages/RestoreFromBackup/helpers';
import { useRestoreFormValidation } from '@/pages/RestoreFromBackup/useRestoreFormValidation';
import { Debounce } from '@/services/helpers/debounce';

export type ExternalRegistryRestoreData = {
  workspaceName: string;
  imageUrl: string;
};

type Props = {
  initialImageUrl?: string;
  existingWorkspaceNames: Set<string>;
  onValidateImage: (imageUrl: string) => Promise<BackupValidationResult>;
  onValidationChange: (isValid: boolean, data: ExternalRegistryRestoreData | null) => void;
  actionButton: React.ReactNode;
};

export const ExternalRegistryRestoreForm: React.FC<Props> = ({
  initialImageUrl,
  existingWorkspaceNames,
  onValidateImage,
  onValidationChange,
  actionButton,
}) => {
  const [imageUrl, setImageUrl] = useState(initialImageUrl || '');
  const [imageUrlValidated, setImageUrlValidated] = useState<ValidatedOptions>(
    ValidatedOptions.default,
  );
  const [imageUrlError, setImageUrlError] = useState('');
  const [validationState, setValidationState] = useState<ValidationState>('idle');
  const [validationResult, setValidationResult] = useState<BackupValidationResult | undefined>(
    undefined,
  );

  const {
    workspaceName,
    workspaceNameValidated,
    workspaceNameError,
    workspaceNameWarning,
    setWorkspaceName,
    handleWorkspaceNameChange,
  } = useRestoreFormValidation(existingWorkspaceNames);

  // Debounce for async validation
  const [debounce] = useState(() => new Debounce());
  const performValidationRef = useRef<() => Promise<void>>();

  performValidationRef.current = async () => {
    if (!imageUrl) {
      setValidationState('idle');
      return;
    }

    try {
      const payload = await onValidateImage(imageUrl);

      if (payload.valid && payload.accessible) {
        const detectedName = payload.metadata?.workspaceName;
        const shouldAutoFill = !workspaceName && !!detectedName;

        setValidationState('valid');
        setValidationResult(payload);
        setImageUrlValidated(ValidatedOptions.success);
        setImageUrlError('');

        if (shouldAutoFill) {
          setWorkspaceName(detectedName!);
        }
      } else {
        setValidationState('invalid');
        setValidationResult(payload);
        setImageUrlValidated(ValidatedOptions.error);
        setImageUrlError(payload.error || 'Backup image is not accessible.');
      }
    } catch (error: unknown) {
      setValidationState('invalid');
      setValidationResult(undefined);
      setImageUrlValidated(ValidatedOptions.error);
      setImageUrlError(typeof error === 'string' ? error : 'Failed to validate backup image.');
    }
  };

  useEffect(() => {
    const handler = () => {
      performValidationRef.current?.();
    };
    debounce.subscribe(handler);
    return () => {
      debounce.unsubscribe(handler);
    };
  }, [debounce]);

  // Trigger validation on mount if initial URL provided
  useEffect(() => {
    if (initialImageUrl) {
      setValidationState('validating');
      debounce.execute();
    }
  }, [debounce, initialImageUrl]);

  // Notify parent of validation state
  useEffect(() => {
    // Allow restore with both success and warning states
    const isValid =
      validationState === 'valid' &&
      (workspaceNameValidated === ValidatedOptions.success ||
        workspaceNameValidated === ValidatedOptions.warning);

    if (isValid) {
      onValidationChange(true, { workspaceName, imageUrl });
    } else {
      onValidationChange(false, null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [validationState, workspaceNameValidated, workspaceName, imageUrl]);

  const handleImageUrlChange = (value: string) => {
    const sanitized = sanitizeImageUrl(value);
    const { validated, error } = validateImageUrlFormat(sanitized);

    setImageUrl(sanitized);
    setImageUrlValidated(validated);
    setImageUrlError(error);
    setValidationState('idle');
    setValidationResult(undefined);
    setWorkspaceName('');

    if (validated !== ValidatedOptions.error && sanitized) {
      setValidationState('validating');
      debounce.execute();
    }
  };

  return (
    <Form isHorizontal={true} onSubmit={e => e.preventDefault()}>
      <ImageUrlField
        value={imageUrl}
        validated={imageUrlValidated}
        error={imageUrlError}
        validationState={validationState}
        validationResult={validationResult}
        onChange={handleImageUrlChange}
      />

      <WorkspaceNameField
        value={workspaceName}
        validated={workspaceNameValidated}
        error={workspaceNameError}
        warning={workspaceNameWarning}
        onChange={handleWorkspaceNameChange}
        actionButton={actionButton}
      />
    </Form>
  );
};
