/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { AiToolDefinition } from '@/devworkspaceClient/types';

const TOOLS_INJECTOR_REGISTRY = 'quay.io/okurinny/tools-injector';
const TOOLS_INJECTOR_TAG = 'next';
const ICON_CDN = 'https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@latest/icons';

export const DEFAULT_AI_TOOLS: AiToolDefinition[] = [
  {
    id: 'claude-code',
    providerId: 'anthropic/claude/latest',
    name: 'Claude Code',
    description:
      'Anthropic Claude AI coding assistant for terminal — autonomous coding, debugging, and codebase exploration.',
    url: 'https://claude.ai/code',
    binary: 'claude',
    pattern: 'init',
    injectorImage: `${TOOLS_INJECTOR_REGISTRY}/claude-code:${TOOLS_INJECTOR_TAG}`,
    envVarName: 'ANTHROPIC_API_KEY',
    runCommandLine: 'claude',
    icon: `${ICON_CDN}/claudecode-color.svg`,
  },
  {
    id: 'gemini-cli',
    providerId: 'google/gemini/latest',
    name: 'Gemini CLI',
    description:
      'Google Gemini AI assistant for the terminal — chat, code generation, and agentic workflows.',
    url: 'https://github.com/google-gemini/gemini-cli',
    binary: 'gemini',
    pattern: 'bundle',
    injectorImage: `${TOOLS_INJECTOR_REGISTRY}/gemini-cli:${TOOLS_INJECTOR_TAG}`,
    envVarName: 'GEMINI_API_KEY',
    setupCommand:
      'mkdir -p "$HOME/.gemini" && test -f "$HOME/.gemini/projects.json" || echo \'{"projects":{}}\' > "$HOME/.gemini/projects.json"',
    runCommandLine: 'gemini',
    icon: `${ICON_CDN}/geminicli.svg`,
  },
  {
    id: 'opencode',
    providerId: 'opencode',
    name: 'OpenCode',
    description:
      'Open-source terminal AI coding agent supporting 75+ LLM providers including Claude, GPT, Gemini, and local models.',
    url: 'https://opencode.ai',
    binary: 'opencode',
    pattern: 'init',
    injectorImage: `${TOOLS_INJECTOR_REGISTRY}/opencode:${TOOLS_INJECTOR_TAG}`,
    runCommandLine: 'opencode',
    icon: `${ICON_CDN}/opencode.svg`,
  },
  {
    id: 'goose',
    providerId: 'goose',
    name: 'Goose',
    description:
      'Open-source local AI developer agent by Block that autonomously automates engineering tasks with multi-LLM support.',
    url: 'https://block.github.io/goose/',
    binary: 'goose',
    pattern: 'init',
    injectorImage: `${TOOLS_INJECTOR_REGISTRY}/goose:${TOOLS_INJECTOR_TAG}`,
    runCommandLine: 'goose',
    icon: `${ICON_CDN}/goose.svg`,
  },
  {
    id: 'kilocode',
    providerId: 'kilocode',
    name: 'KiloCode',
    description:
      'Open-source AI coding agent supporting 500+ models with code, architect, and debug modes for VS Code and JetBrains.',
    url: 'https://kilo.ai',
    binary: 'kilo',
    pattern: 'bundle',
    injectorImage: `${TOOLS_INJECTOR_REGISTRY}/kilocode:${TOOLS_INJECTOR_TAG}`,
    runCommandLine: 'kilo',
    icon: `${ICON_CDN}/kilocode.svg`,
  },
];
