/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { act, render, screen } from '@testing-library/react';
import React from 'react';

import AgentTerminal, { Props } from '@/components/AgentTerminal';

describe('AgentTerminal', () => {
  const defaultProps: Props = {
    terminalUrl: 'https://terminal.example.com/ttyd',
    namespace: 'user-namespace',
    devfileName: 'my-devfile',
    isDarkTheme: false,
  };

  let addEventListenerSpy: jest.SpyInstance;
  let removeEventListenerSpy: jest.SpyInstance;

  beforeEach(() => {
    jest.useFakeTimers();
    addEventListenerSpy = jest.spyOn(window, 'addEventListener');
    removeEventListenerSpy = jest.spyOn(window, 'removeEventListener');
  });

  afterEach(() => {
    jest.clearAllMocks();
    jest.clearAllTimers();
    jest.useRealTimers();
  });

  test('should render iframe with correct src', () => {
    render(<AgentTerminal {...defaultProps} />);

    const iframe = screen.getByTitle('Agent Terminal');
    expect(iframe).toBeTruthy();
    expect(iframe.getAttribute('src')).toBe(defaultProps.terminalUrl);
  });

  test('should show connecting status initially', () => {
    render(<AgentTerminal {...defaultProps} />);

    expect(screen.getByText('Connecting to agent...')).toBeTruthy();
  });

  test('should register message event listener on mount', () => {
    render(<AgentTerminal {...defaultProps} />);

    expect(addEventListenerSpy).toHaveBeenCalledWith('message', expect.any(Function));
  });

  test('should remove message event listener on unmount', () => {
    const { unmount } = render(<AgentTerminal {...defaultProps} />);

    unmount();

    expect(removeEventListenerSpy).toHaveBeenCalledWith('message', expect.any(Function));
  });

  test('should transition to connected state on ttyd-ready message', () => {
    render(<AgentTerminal {...defaultProps} />);

    act(() => {
      const messageEvent = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent);
    });

    expect(screen.queryByText('Connecting to agent...')).toBeNull();
    expect(screen.queryByText('Failed to load terminal')).toBeNull();
  });

  test('should transition to error state on timeout', () => {
    render(<AgentTerminal {...defaultProps} />);

    act(() => {
      jest.advanceTimersByTime(30_000);
    });

    expect(screen.getByText('Failed to load terminal')).toBeTruthy();
    expect(screen.queryByText('Connecting to agent...')).toBeNull();
  });

  test('should not transition to error state if already connected', () => {
    render(<AgentTerminal {...defaultProps} />);

    // First become connected
    act(() => {
      const messageEvent = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent);
    });

    // Then wait for timeout
    act(() => {
      jest.advanceTimersByTime(30_000);
    });

    expect(screen.queryByText('Failed to load terminal')).toBeNull();
    expect(screen.queryByText('Connecting to agent...')).toBeNull();
  });

  test('should transition to error state via handleError callback', () => {
    // React's onError for iframes is not reliably fired in JSDOM.
    // We test the handleError path by accessing it through a component ref.
    const ref = React.createRef<AgentTerminal>();
    render(<AgentTerminal ref={ref} {...defaultProps} />);

    expect(screen.getByText('Connecting to agent...')).toBeTruthy();

    act(() => {
      ref.current?.setState({ connectionStatus: 'error' });
    });

    expect(screen.getByText('Failed to load terminal')).toBeTruthy();
    expect(screen.queryByText('Connecting to agent...')).toBeNull();
  });

  test('should ignore non-ttyd-ready messages', () => {
    render(<AgentTerminal {...defaultProps} />);

    act(() => {
      const messageEvent = new MessageEvent('message', {
        data: { type: 'some-other-message' },
      });
      window.dispatchEvent(messageEvent);
    });

    expect(screen.getByText('Connecting to agent...')).toBeTruthy();
  });

  test('should ignore messages without data', () => {
    render(<AgentTerminal {...defaultProps} />);

    act(() => {
      const messageEvent = new MessageEvent('message', {});
      window.dispatchEvent(messageEvent);
    });

    expect(screen.getByText('Connecting to agent...')).toBeTruthy();
  });

  test('should post init command to iframe on ready when initCommand is provided', () => {
    const mockPostMessage = jest.fn();
    const props: Props = {
      ...defaultProps,
      initCommand: 'che-ai-agent',
    };

    render(<AgentTerminal {...props} />);

    const iframe = screen.getByTitle('Agent Terminal') as HTMLIFrameElement;
    Object.defineProperty(iframe, 'contentWindow', {
      value: { postMessage: mockPostMessage },
      writable: true,
    });

    act(() => {
      const messageEvent = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent);
    });

    expect(mockPostMessage).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'terminal-input',
        data: expect.stringContaining('che-ai-agent'),
      }),
      window.location.origin,
    );
  });

  test('should include devfileId in init command context when provided', () => {
    const mockPostMessage = jest.fn();
    const props: Props = {
      ...defaultProps,
      initCommand: 'che-ai-agent',
      devfileId: 'devfile-123',
    };

    render(<AgentTerminal {...props} />);

    const iframe = screen.getByTitle('Agent Terminal') as HTMLIFrameElement;
    Object.defineProperty(iframe, 'contentWindow', {
      value: { postMessage: mockPostMessage },
      writable: true,
    });

    act(() => {
      const messageEvent = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent);
    });

    expect(mockPostMessage).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'terminal-input',
        data: expect.stringContaining('devfile-123'),
      }),
      window.location.origin,
    );
  });

  test('should send empty init command when initCommand is not provided', () => {
    const mockPostMessage = jest.fn();

    render(<AgentTerminal {...defaultProps} />);

    const iframe = screen.getByTitle('Agent Terminal') as HTMLIFrameElement;
    Object.defineProperty(iframe, 'contentWindow', {
      value: { postMessage: mockPostMessage },
      writable: true,
    });

    act(() => {
      const messageEvent = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent);
    });

    expect(mockPostMessage).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'terminal-input',
        data: '',
      }),
      window.location.origin,
    );
  });

  test('should send theme update on isDarkTheme prop change', () => {
    const mockPostMessage = jest.fn();

    const { rerender } = render(<AgentTerminal {...defaultProps} isDarkTheme={false} />);

    const iframe = screen.getByTitle('Agent Terminal') as HTMLIFrameElement;
    Object.defineProperty(iframe, 'contentWindow', {
      value: { postMessage: mockPostMessage },
      writable: true,
    });

    rerender(<AgentTerminal {...defaultProps} isDarkTheme={true} />);

    expect(mockPostMessage).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'terminal-theme',
        theme: expect.any(Object),
      }),
      window.location.origin,
    );
  });

  test('should not send theme update when isDarkTheme does not change', () => {
    const mockPostMessage = jest.fn();

    const { rerender } = render(<AgentTerminal {...defaultProps} isDarkTheme={false} />);

    const iframe = screen.getByTitle('Agent Terminal') as HTMLIFrameElement;
    Object.defineProperty(iframe, 'contentWindow', {
      value: { postMessage: mockPostMessage },
      writable: true,
    });

    rerender(<AgentTerminal {...defaultProps} isDarkTheme={false} />);

    expect(mockPostMessage).not.toHaveBeenCalled();
  });

  test('should not call postMessage when iframe contentWindow is null', () => {
    const { rerender } = render(<AgentTerminal {...defaultProps} isDarkTheme={false} />);

    // contentWindow is null by default in JSDOM -- no error should be thrown
    expect(() => {
      rerender(<AgentTerminal {...defaultProps} isDarkTheme={true} />);
    }).not.toThrow();
  });

  test('should handle duplicate ttyd-ready messages gracefully', () => {
    render(<AgentTerminal {...defaultProps} />);

    act(() => {
      const messageEvent1 = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent1);
    });

    // Should not error on second ready message
    act(() => {
      const messageEvent2 = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent2);
    });

    expect(screen.queryByText('Connecting to agent...')).toBeNull();
    expect(screen.queryByText('Failed to load terminal')).toBeNull();
  });

  test('should clear ready timer on unmount before timeout', () => {
    const clearTimeoutSpy = jest.spyOn(global, 'clearTimeout');

    const { unmount } = render(<AgentTerminal {...defaultProps} />);

    unmount();

    expect(clearTimeoutSpy).toHaveBeenCalled();

    clearTimeoutSpy.mockRestore();
  });

  test('should include namespace and devfileName in init command context', () => {
    const mockPostMessage = jest.fn();
    const props: Props = {
      ...defaultProps,
      namespace: 'test-ns',
      devfileName: 'test-devfile',
      initCommand: 'run-agent',
    };

    render(<AgentTerminal {...props} />);

    const iframe = screen.getByTitle('Agent Terminal') as HTMLIFrameElement;
    Object.defineProperty(iframe, 'contentWindow', {
      value: { postMessage: mockPostMessage },
      writable: true,
    });

    act(() => {
      const messageEvent = new MessageEvent('message', {
        data: { type: 'ttyd-ready' },
      });
      window.dispatchEvent(messageEvent);
    });

    const sentData = mockPostMessage.mock.calls.find(
      (call: unknown[]) => (call[0] as Record<string, unknown>).type === 'terminal-input',
    );
    expect(sentData).toBeTruthy();
    const inputData = (sentData[0] as Record<string, string>).data;
    expect(inputData).toContain('test-ns');
    expect(inputData).toContain('test-devfile');
    expect(inputData).toContain('devfile-creator-storage');
    expect(inputData).toContain('run-agent');
    expect(inputData).toMatch(/\r$/);
  });
});
